// xxl-boot-ui-vue/src/layout/components/Sidebar/index.vue
<!--
  组件：Sidebar（侧边栏）
  功能：左侧菜单容器，含 Logo、菜单树、折叠切换。
        混合模式下只显示当前顶级菜单的子路由。
-->
<template>
  <div :class="['sidebar-theme-wrapper', { 'has-logo': showLogo }, sideTheme]" class="sidebar-container">
    <!-- Logo -->
    <SidebarLogo v-if="showLogo" :collapse="isCollapse" />
    <!-- 菜单滚动容器 -->
    <el-scrollbar wrap-class="scrollbar-wrapper">
      <el-menu
        :default-active="activeMenu"
        :collapse="isCollapse"
        :background-color="getMenuBackground"
        :text-color="getMenuTextColor"
        :unique-opened="true"
        :active-text-color="theme"
        :collapse-transition="false"
        mode="vertical"
        :class="sideTheme"
      >
        <!-- 菜单项 -->
        <SidebarItem v-for="(route, index) in sidebarRouters" :key="(route.path || '') + index" :item="route" :base-path="route.path" />
      </el-menu>
    </el-scrollbar>
  </div>
</template>

<script setup lang="ts">
import SidebarLogo from './SidebarLogo.vue'
import SidebarItem from './SidebarItem.vue'
import variables from '@/assets/styles/variables.module.scss'
import { useAppStore, useRoutesStore, useSettingsStore } from '@/store'
import type { RouteData } from '@/store/modules/routes'

const route = useRoute()
const appStore = useAppStore()
const settingsStore = useSettingsStore()
const store = useRoutesStore()

/*
 * 侧边栏路由列表。
 *   - 混合模式（navType=2）且存在顶级作用域 _scope 时，只显示该顶级菜单下的子路由；
 *   - 否则全量展示。
 *
 * computed：
 *   - 自动追踪依赖（现有的响应式数据），当依赖变化时自动重新计算
 */
const sidebarRouters = computed<RouteData[]>(() => {
  const routes: RouteData[] = store.fullRoutes
  /*
   * _scope 由 TopBarMix 的 setScope 设置，标识当前激活的顶级菜单 path。
   * 默认scope为 ''/假值，不会过滤。
   */
  if (settingsStore.navType === 2 && store._scope) {
    const menu = routes.find((r) => r.path === store._scope)
    if (menu?.children) return menu.children
  }
  return routes
})

const showLogo = computed(() => settingsStore.sidebarLogo)
const sideTheme = computed(() => settingsStore.sideTheme)
const theme = computed(() => settingsStore.theme)
const isCollapse = computed(() => !appStore.sidebar.opened)

/*
 * 菜单背景色：深色模式 / theme-dark / theme-light
 */
const getMenuBackground = computed(() => {
  if (settingsStore.isDark) {
    return 'var(--sidebar-bg)'
  }
  return sideTheme.value === 'theme-dark' ? variables.menuBg : variables.menuLightBg
})

/*
 * 菜单文字色：深色模式 / theme-dark / theme-light
 */
const getMenuTextColor = computed(() => {
  if (settingsStore.isDark) {
    return 'var(--sidebar-text)'
  }
  return sideTheme.value === 'theme-dark' ? variables.menuText : variables.menuLightText
})

/*
 * 当前激活菜单：优先取 meta.activeMenu，否则取 route.path
 */
const activeMenu = computed(() => {
  const { meta, path } = route
  if (meta.activeMenu) {
    return meta.activeMenu
  }
  return path
})
</script>

<style lang="scss" scoped>
.sidebar-container {
  background-color: v-bind(getMenuBackground);

  .scrollbar-wrapper {
    background-color: v-bind(getMenuBackground);
  }

  .el-menu {
    border: none;
    height: 100%;
    width: 100% !important;

    .el-menu-item,
    .el-sub-menu__title {
      &:hover {
        background-color: var(--menu-hover, rgba(0, 0, 0, 0.06)) !important;
      }
    }

    .el-menu-item {
      color: v-bind(getMenuTextColor);

      &.is-active {
        color: var(--menu-active-text, #409eff);
        background-color: var(--menu-hover, rgba(0, 0, 0, 0.06)) !important;
      }
    }

    .el-sub-menu__title {
      color: v-bind(getMenuTextColor);
    }
  }
}
</style>

// xxl-boot-ui-react/src/layout/components/Sidebar/index.tsx
/**
 * 组件：Sidebar（侧边栏）
 * 功能：左侧菜单容器，含 Logo、菜单树、折叠切换。
 *       混合模式下只显示当前顶级菜单的子路由。
 */
import { useEffect, useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Menu } from 'antd'
import type { MenuProps } from 'antd'
import SidebarLogo from './SidebarLogo'
import { isExternal } from '@/utils/validate'
import { buildMenuItems } from '../menuUtil'
import { useAppStore, useRoutesStore, useSettingsStore } from '@/stores'
import variables from '@/assets/styles/variables'
import type { RouteData } from '@/stores/routes'
import './sidebar.scss'

/**
 * 侧边栏
 */
export default function Sidebar() {
  const location = useLocation()
  const navigate = useNavigate()
  const appStore = useAppStore()
  const settingsStore = useSettingsStore()
  const routesStore = useRoutesStore()

  // 当前激活菜单：优先取 meta.activeMenu，否则取 route.path
  const activeMenu = useMemo(() => {
    const meta = findRouteMetaByPath(location.pathname)
    if (meta && meta.activeMenu) {
      return meta.activeMenu
    }
    return location.pathname
  }, [location.pathname])
  // 折叠状态
  const isCollapse = !appStore.sidebar.opened
  // 展开的子菜单 key（unique-opened 单开）
  const [openKeys, setOpenKeys] = useState<string[]>([])

  // 当前路由匹配的前缀子菜单 key：用于自动展开
  useEffect(() => {
    const prefix = findTopPrefix(location.pathname)
    setOpenKeys(prefix ? [prefix] : [])
     
  }, [location.pathname])

  /*
   * 侧边栏路由列表：混合模式（navType=2）且存在 _scope 时只显示对应顶级菜单的子路由
   */
  const sidebarRouters = useMemo<RouteData[]>(() => {
    const routes = routesStore.fullRoutes
    if (settingsStore.navType === 2 && routesStore._scope) {
      const menu = routes.find((r) => r.path === routesStore._scope)
      if (menu && menu.children) return menu.children
    }
    return routes
  }, [routesStore.fullRoutes, settingsStore.navType, routesStore._scope])

  /*
   * 构建 antd 菜单项（递归）
   */
  const menuItems = useMemo<MenuProps['items']>(() => buildMenuItems(sidebarRouters, ''), [sidebarRouters])

  /*
   * 菜单背景色：深色模式 / theme-dark / theme-light
   */
  const getMenuBackground = () => {
    if (settingsStore.isDark) {
      return 'var(--sidebar-bg)'
    }
    return settingsStore.sideTheme === 'theme-dark' ? variables.menuBg : variables.menuLightBg
  }

  /*
   * 菜单文字色：深色模式 / theme-dark / theme-light
   */
  const getMenuTextColor = () => {
    if (settingsStore.isDark) {
      return 'var(--sidebar-text)'
    }
    return settingsStore.sideTheme === 'theme-dark' ? variables.menuText : variables.menuLightText
  }

  /*
   * 菜单点击：外部链接新窗口，内部路由跳转
   */
  const handleMenuClick: MenuProps['onClick'] = ({ key }) => {
    if (isExternal(String(key))) {
      window.open(String(key), '_blank')
    } else {
      navigate(String(key))
    }
  }

  /*
   * 展开变化：仅保留最后展开的子菜单（unique-opened 效果）
   */
  const handleOpenChange = (keys: string[]) => {
    const latestOpenKey = keys.find((key) => openKeys.indexOf(key) === -1)
    setOpenKeys(latestOpenKey ? [latestOpenKey] : [])
  }

  return (
    <div className={`sidebar-container ${settingsStore.sideTheme} ${settingsStore.sidebarLogo ? 'has-logo' : ''}`}>
      {settingsStore.sidebarLogo && <SidebarLogo collapse={isCollapse} />}
      <div
        className="sidebar-menu-scroll"
        style={{ background: getMenuBackground() }}
        onClick={(e) => {
          // 折叠态点击空白收起 popup 选择行为由 antd 处理
          e.stopPropagation()
        }}
      >
        <Menu
          className="sidebar-menu"
          theme={settingsStore.sideTheme === 'theme-dark' ? 'dark' : 'light'}
          mode="inline"
          inlineCollapsed={isCollapse}
          selectedKeys={[activeMenu]}
          openKeys={isCollapse ? undefined : openKeys}
          onOpenChange={handleOpenChange}
          items={menuItems}
          onClick={handleMenuClick}
          style={{ color: getMenuTextColor() }}
        />
      </div>
    </div>
  )
}

/**
 * 查找路由 meta（供侧边栏 activeMenu 使用）
 * @param path 当前路由路径
 * @returns meta 或 undefined
 */
function findRouteMetaByPath(path: string): { activeMenu?: string; [key: string]: unknown } | undefined {
  const allRoutes = useRoutesStore.getState().fullRoutes
  const stack = [...allRoutes]
  while (stack.length > 0) {
    const route = stack.pop()
    if (!route) continue
    if (route.children && route.children.length) {
      stack.push(...(route.children as RouteData[]))
    }
    if (route.path && (route.path === path || (path.startsWith(route.path) && route.path !== '*'))) {
      if (route.meta) {
        return route.meta
      }
    }
  }
  return undefined
}

/**
 * 查找当前路由对应顶级菜单前缀（用于自动展开子菜单）
 * @param path 当前路由路径
 * @returns 顶级菜单路径或空
 */
function findTopPrefix(path: string): string {
  const dynamicRoutes = useRoutesStore.getState().dynamicRoutes
  for (const route of dynamicRoutes) {
    if (route.hidden || route.path === '/') continue
    if (route.path && path.startsWith(route.path) && route.children && route.children.length > 0) {
      return route.path
    }
  }
  return ''
}
