// xxl-boot-ui/xxl-boot-ui-react/src/pages/tool/pagegen/CodeTypeDialog.tsx
/**
 * 组件：CodeTypeDialog（代码生成类型选择弹窗）
 * 功能：选择生成类型（页面/弹窗），导出时额外支持输入文件名
 */
import { App, Form, Input, Modal, Radio } from 'antd';
import React, { useEffect, useState } from 'react';

/** 生成类型配置 */
const typeOptions = [
  { label: '页面', value: 'file' },
  { label: '弹窗', value: 'dialog' },
];

/**
 * 生成类型选择弹窗
 * @param props.open        弹窗是否打开
 * @param props.onOpenChange 弹窗开关变化回调
 * @param props.showFileName 是否显示文件名输入（导出场景）
 * @param props.onConfirm    确认回调，参数为生成类型与文件名
 */
const CodeTypeDialog = ({
  open,
  onOpenChange,
  showFileName = false,
  onConfirm,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  showFileName?: boolean;
  onConfirm: (data: { type: string; fileName?: string }) => void;
}) => {
  const { message } = App.useApp();

  /* 生成类型选中值 */
  const [type, setType] = useState('file');
  /* 文件名 */
  const [fileName, setFileName] = useState('');

  /* 打开弹窗时重置表单，导出场景生成默认文件名 */
  useEffect(() => {
    if (open) {
      setType('file');
      setFileName(showFileName ? `${Date.now()}.tsx` : '');
    }
  }, [open, showFileName]);

  /** 关闭弹窗 */
  const handleClose = () => {
    onOpenChange(false);
  };

  /** 确认生成 */
  const handleConfirm = () => {
    if (showFileName && !fileName.trim()) {
      message.warning('请输入文件名');
      return;
    }
    onConfirm({ type, fileName: fileName.trim() });
    onOpenChange(false);
  };

  return (
    <Modal
      title="选择生成类型"
      width={500}
      open={open}
      onCancel={handleClose}
      onOk={handleConfirm}
      okText="确定"
      cancelText="取消"
      destroyOnHidden
    >
      <Form layout="vertical" style={{ marginTop: 8 }}>
        <Form.Item label="生成类型">
          <Radio.Group
            value={type}
            onChange={(e) => setType(e.target.value)}
            options={typeOptions}
            optionType="button"
          />
        </Form.Item>
        {showFileName && (
          <Form.Item label="文件名" required>
            <Input
              value={fileName}
              onChange={(e) => setFileName(e.target.value)}
              placeholder="请输入文件名"
              allowClear
            />
          </Form.Item>
        )}
      </Form>
    </Modal>
  );
};

export default CodeTypeDialog;

// xxl-boot-ui/src/views/tool/pagegen/CodeTypeDialog.vue
<!--
  组件：代码生成类型选择弹窗
  功能：选择生成页面或弹窗类型，可输入文件名
-->
<template>
  <el-dialog v-model="open" width="500px" title="选择生成类型" @open="onOpen" @close="onClose">
    <el-form ref="codeTypeForm" :model="formData" :rules="rules" label-width="100px">
      <el-form-item label="生成类型" prop="type">
        <el-radio-group v-model="formData.type">
          <el-radio-button v-for="(item, index) in typeOptions" :key="index" :label="item.value">
            {{ item.label }}
          </el-radio-button>
        </el-radio-group>
      </el-form-item>
      <el-form-item v-if="showFileName" label="文件名" prop="fileName">
        <el-input v-model="formData.fileName" placeholder="请输入文件名" clearable />
      </el-form-item>
    </el-form>

    <template #footer>
      <el-button type="primary" @click="handelConfirm">确定</el-button>
      <el-button @click="onClose">取消</el-button>
    </template>
  </el-dialog>
</template>

<script setup>
/** 生成类型弹窗 - 逻辑 */
const open = defineModel()
const props = defineProps({
  showFileName: Boolean   /* 是否显示文件名输入 */
})
const emit = defineEmits(['confirm'])
const formData = ref({
  fileName: undefined,
  type: 'file'            /* 默认生成页面 */
})
const codeTypeForm = ref()
const rules = {
  fileName: [{
    required: true,
    message: '请输入文件名',
    trigger: 'blur'
  }],
  type: [{
    required: true,
    message: '生成类型不能为空',
    trigger: 'change'
  }]
}
const typeOptions = ref([
  { label: '页面', value: 'file' },
  { label: '弹窗', value: 'dialog' }
])

/** 弹窗打开：需要文件名时设置默认值 */
function onOpen() {
  if (props.showFileName) {
    formData.value.fileName = `${+new Date()}.vue`
  }
}

/** 弹窗关闭 */
function onClose() {
  open.value = false
}

/** 确认生成 */
function handelConfirm() {
  codeTypeForm.value.validate(valid => {
    if (!valid) return
    emit('confirm', { ...formData.value })
    onClose()
  })
}
</script>
