// xxl-boot-ui/xxl-boot-ui-vue/src/layout/components/TagsView/index.vue
<!--
  组件：TagsView（多标签页）
  功能：顶部多标签页管理，支持标签切换、关闭、刷新、全屏显示，以及右键/下拉菜单操作。
        支持 card 和 chrome 两种标签样式。
-->
<template>
  <div id="tags-view-container" class="tags-view-container" :class="{ 'tags-view-container--chrome': tagsViewStyle === 'chrome' }">
    <!--  左箭头  -->
    <span class="tags-nav-btn tags-nav-btn--left" :class="{ disabled: !canScrollLeft }" @click="scrollLeft">
      <el-icon><ArrowLeft /></el-icon>
    </span>

    <!--  scroll pane  -->
    <ScrollPane ref="scrollPaneRef" class="tags-view-wrapper" @scroll="handleScroll" @update-arrows="updateArrowState">
      <!-- 标签列表循环渲染 -->
      <router-link
        v-for="tag in visitedViews"
        :key="tag.path"
        :data-path="tag.path"
        :class="{ active: isActive(tag), 'has-icon': tagsIcon }"
        :to="{ path: tag.path, query: tag.query as any }"
        class="tags-view-item"
        :style="tagActiveStyle(tag)"
        @click.middle="!isAffix(tag) ? closeSelectedTag(tag) : ''"
        @contextmenu.prevent="openMenu(tag, $event)"
      >
        <!-- icon -->
        <SvgIcon
          v-if="tagsIcon && tag.meta && tag.meta.icon && tag.meta.icon !== '#'"
          :icon-class="tag.meta.icon as string"
          style="margin-right: 3px"
        />
        <!-- title -->
        {{ tag.title }}
        <!-- close -->
        <span v-if="!isAffix(tag)" @click.prevent.stop="closeSelectedTag(tag)" class="tags-close-btn">
          <Close class="el-icon-close" />
        </span>
      </router-link>
    </ScrollPane>

    <!-- 右箭头 -->
    <span class="tags-nav-btn tags-nav-btn--right" :class="{ disabled: !canScrollRight }" @click="scrollRight">
      <el-icon><ArrowRight /></el-icon>
    </span>

    <!-- 下拉操作菜单：关闭、刷新、全屏等 -->
    <el-dropdown class="tags-action-dropdown" trigger="click" placement="bottom-end" @command="handleDropdownCommand">
      <span class="tags-action-btn">
        <el-icon><ArrowDown /></el-icon>
      </span>
      <template #dropdown>
        <el-dropdown-menu class="tags-dropdown-menu">
          <el-dropdown-item v-if="!isAffix(selectedDropdownTag)" command="close"
            ><Close style="width: 1em; height: 1em" />关闭当前</el-dropdown-item
          >
          <el-dropdown-item command="closeOthers"><CircleClose style="width: 1em; height: 1em" />关闭其他</el-dropdown-item>
          <el-dropdown-item command="closeLeft" :disabled="isFirstView()"
            ><Back style="width: 1em; height: 1em" />关闭左侧</el-dropdown-item
          >
          <el-dropdown-item command="closeRight" :disabled="isLastView()"
            ><Right style="width: 1em; height: 1em" />关闭右侧</el-dropdown-item
          >
          <el-dropdown-item command="closeAll"><CircleClose style="width: 1em; height: 1em" />全部关闭</el-dropdown-item>
          <el-dropdown-item command="fullscreen" divided>
            <template v-if="!isFullscreen"><FullScreen style="width: 1em; height: 1em" />全屏显示</template>
            <template v-else><Close style="width: 1em; height: 1em" />退出全屏</template>
          </el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>

    <!-- 刷新按钮 -->
    <span class="tags-action-btn tags-refresh-btn" title="刷新页面" @click="refreshSelectedTag(selectedDropdownTag)">
      <el-icon><RefreshRight /></el-icon> 刷新
    </span>

    <!-- 右键上下文菜单 -->
    <ul v-show="visible" :style="{ left: left + 'px', top: top + 'px' }" class="contextmenu">
      <li @click="refreshSelectedTag(selectedTag)"><RefreshRight style="width: 1em; height: 1em" />刷新页面</li>
      <li v-if="!isAffix(selectedTag)" @click="closeSelectedTag(selectedTag)"><Close style="width: 1em; height: 1em" />关闭当前</li>
      <li @click="closeOthersTags"><CircleClose style="width: 1em; height: 1em" />关闭其他</li>
      <li v-if="!isFirstView()" @click="closeLeftTags"><Back style="width: 1em; height: 1em" />关闭左侧</li>
      <li v-if="!isLastView()" @click="closeRightTags"><Right style="width: 1em; height: 1em" />关闭右侧</li>
      <li @click="closeAllTags(selectedTag)"><CircleClose style="width: 1em; height: 1em" />全部关闭</li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import ScrollPane from './ScrollPane.vue'
import { resolveMenuPath } from '@/utils/menu'
import { useTagsViewStore, useRoutesStore, useSettingsStore } from '@/store'
import type { TagView } from '@/store/modules/tagsView'
import type { RouteData } from '@/store/modules/routes'
import tab from '@/utils/tab'
import defaultSettings from '@/default-settings'
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { SvgIcon } from '@/components'

const tagsViewStore = useTagsViewStore()
const routesStore = useRoutesStore()
const settingsStore = useSettingsStore()

// 右键上下文菜单
const visible = ref(false)
const top = ref(0)
const left = ref(0)
const selectedTag = ref<Record<string, any>>({})
// 持久化Tab
const affixTags = ref<any[]>([])
// Tab数据
const scrollPaneRef = ref<InstanceType<typeof ScrollPane> | null>(null)
// 左右箭头状态：是否可点击
const canScrollLeft = ref(false)
const canScrollRight = ref(false)
// 页内全屏状态
const isFullscreen = ref(false)
// 全屏隐藏/恢复元素列表：记录隐藏的 navbar/sidebar 信息，退出时恢复
const hiddenElements = ref<{ el: HTMLElement | null; originalDisplay: string }[]>([])

const route = useRoute()
const router = useRouter()

const visitedViews = computed(() => tagsViewStore.visitedViews)
const routes = computed(() => routesStore.fullRoutes)
const theme = computed(() => settingsStore.theme)
const tagsIcon = computed(() => settingsStore.tagsIcon)
const tagsViewPersist = computed(() => settingsStore.tagsViewPersist)
const tagsViewStyle = computed(() => settingsStore.tagsViewStyle)

// 下拉菜单针对当前激活的 tag
const selectedDropdownTag = computed<TagView>(() => visitedViews.value.find((v) => isActive(v)) || ({} as TagView))

/*
 * 路由变化时添加新标签并滚动到当前标签
 */
watch(route, () => {
  addTags()
  moveToCurrentTag()
})

/*
 * 右键菜单显隐时切换 body 点击监听
 */
watch(visible, (value) => {
  if (value) {
    document.body.addEventListener('click', closeMenu)
  } else {
    document.body.removeEventListener('click', closeMenu)
  }
})

watch(visitedViews, () => {
  nextTick(() => updateArrowState())
})

onMounted(() => {
  initTags()
  addTags()
  window.addEventListener('resize', updateArrowState)
  window.addEventListener('keydown', handleKeyDown)
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', updateArrowState)
  window.removeEventListener('keydown', handleKeyDown)
})

/*
 * Esc 退出全屏
 */
function handleKeyDown(event: KeyboardEvent) {
  if (event.key === 'Escape' && isFullscreen.value) {
    toggleFullscreen()
  }
}

/*
 * 当前路由是否为标签页
 */
function isActive(r: Record<string, any>) {
  return r.path === route.path
}

/*
 * 激活标签高亮样式（card 模式下）
 */
function tagActiveStyle(tag: Record<string, any>) {
  if (!isActive(tag) || tagsViewStyle.value !== 'card') return {}
  return {
    'background-color': theme.value,
    'border-color': theme.value
  }
}

/*
 * 是否为固定标签（不可关闭）
 */
function isAffix(tag: Record<string, any>) {
  return tag && tag.meta && tag.meta.affix
}

/*
 * 是否为最左标签（首页索引为 1 的标签）
 */
function isFirstView() {
  try {
    const tag = selectedTag.value && selectedTag.value.fullPath ? selectedTag.value : selectedDropdownTag.value
    return tag.fullPath === defaultSettings.homePath || tag.fullPath === visitedViews.value[1].fullPath
  } catch (err) {
    return false
  }
}

/*
 * 是否为最右标签
 */
function isLastView() {
  try {
    const tag = selectedTag.value && selectedTag.value.fullPath ? selectedTag.value : selectedDropdownTag.value
    return tag.fullPath === visitedViews.value[visitedViews.value.length - 1].fullPath
  } catch (err) {
    return false
  }
}

/*
 * 递归收集带 affix 标记的固定标签（首页/特殊页面）
 */
function filterAffixTags(routes: RouteData[], basePath = '') {
  let tags: TagView[] = []
  routes.forEach((route) => {
    if (route.meta && route.meta.affix) {
      const tagPath = resolveMenuPath(route.path, basePath) as string
      tags.push({
        fullPath: tagPath,
        path: tagPath,
        name: route.name,
        meta: { ...route.meta }
      })
    }
    if (route.children) {
      const tempTags = filterAffixTags(route.children, route.path)
      if (tempTags.length >= 1) {
        tags = [...tags, ...tempTags]
      }
    }
  })
  return tags
}

/*
 * 初始化：持久化恢复 + 固定标签注册
 */
function initTags() {
  if (tagsViewPersist.value) {
    tagsViewStore.loadPersistedViews()
  }
  const res = filterAffixTags(routes.value)
  affixTags.value = res
  for (const tag of res) {
    if (tag.name) {
      tagsViewStore.addAffixView(tag)
    }
  }
}

/*
 * 当前路由加入标签页
 */
function addTags() {
  const { name } = route
  if (name) {
    tagsViewStore.addView(route as any)
  }
}

/*
 * 滚动到当前标签，同步路由更新
 */
function moveToCurrentTag() {
  nextTick(() => {
    for (const r of visitedViews.value) {
      if (r.path === route.path) {
        scrollPaneRef.value?.moveToTarget(r)
        if (r.fullPath !== route.fullPath) {
          tagsViewStore.updateVisitedView(route as any)
        }
      }
    }
  })
}

/*
 * 左 / 右箭头滚动标签栏
 */
function scrollLeft() {
  if (!canScrollLeft.value) return
  scrollPaneRef.value?.scrollToStart()
}

function scrollRight() {
  if (!canScrollRight.value) return
  scrollPaneRef.value?.scrollToEnd()
}

/*
 * 更新左右箭头可用状态
 */
function updateArrowState() {
  // 下次 DOM 更新循环结束之后执行延迟回调‌
  nextTick(() => {
    if (scrollPaneRef.value) {
      const state = scrollPaneRef.value.getScrollState()
      canScrollLeft.value = state.canLeft
      canScrollRight.value = state.canRight
    }
  })
}

/*
 * 全屏模式：隐藏 navbar/sidebar 使内容区占满视口
 */
function toggleFullscreen() {
  const mainContainer = document.querySelector<HTMLElement>('.main-container')
  const navbar = document.querySelector<HTMLElement>('.navbar')
  const sidebar = document.querySelector<HTMLElement>('.sidebar-container')
  if (!mainContainer) return

  if (!isFullscreen.value) {
    mainContainer.classList.add('fullscreen-mode')
    document.body.style.overflow = 'hidden'
    const elementsToHide = [
      { el: navbar, originalDisplay: navbar?.style.display || '' },
      { el: sidebar, originalDisplay: sidebar?.style.display || '' }
    ]
    elementsToHide.forEach((item) => {
      if (item.el && item.el.style.display !== 'none') {
        item.originalDisplay = item.el.style.display
        item.el.style.display = 'none'
        hiddenElements.value.push(item)
      }
    })
    isFullscreen.value = true
  } else {
    mainContainer.classList.remove('fullscreen-mode')
    document.body.style.overflow = ''
    hiddenElements.value.forEach((item) => {
      if (item.el) {
        item.el.style.display = item.originalDisplay
      }
    })
    hiddenElements.value = []
    document.querySelector<HTMLElement>('.tags-action-btn')?.blur()
    isFullscreen.value = false
  }
}

/*
 * 下拉菜单命令分发
 */
function handleDropdownCommand(command: string | number | object) {
  const tag = selectedDropdownTag.value
  selectedTag.value = tag
  switch (command) {
    case 'refresh':
      refreshSelectedTag(tag)
      break
    case 'fullscreen':
      toggleFullscreen()
      break
    case 'close':
      closeSelectedTag(tag)
      break
    case 'closeOthers':
      closeOthersTags()
      break
    case 'closeLeft':
      closeLeftTags()
      break
    case 'closeRight':
      closeRightTags()
      break
    case 'closeAll':
      closeAllTags(tag)
      break
  }
}

/*
 * 刷新指定标签页
 */
function refreshSelectedTag(view: Record<string, any>) {
  tab.refreshPage(view)
}

/*
 * 关闭标签：若关闭的是当前标签则跳转到最后标签
 */
function closeSelectedTag(view: Record<string, any>) {
  tab.closePage(view).then(({ visitedViews }: any) => {
    if (isActive(view)) {
      toLastView(visitedViews, view)
    }
  })
}

/*
 * 关闭右侧标签，若当前标签被关则回退
 */
function closeRightTags() {
  tab.closeRightPage(selectedTag.value).then((visitedViews) => {
    if (!visitedViews.find((i) => i.fullPath === route.fullPath)) {
      toLastView(visitedViews)
    }
  })
}

/*
 * 关闭左侧标签，若当前标签被关则回退
 */
function closeLeftTags() {
  tab.closeLeftPage(selectedTag.value).then((visitedViews) => {
    if (!visitedViews.find((i) => i.fullPath === route.fullPath)) {
      toLastView(visitedViews)
    }
  })
}

/*
 * 关闭其他标签：先跳转到目标标签再关闭其他
 */
function closeOthersTags() {
  router.push(selectedTag.value).catch(() => {})
  tab.closeOtherPage(selectedTag.value).then(() => {
    moveToCurrentTag()
  })
}

/*
 * 关闭全部标签（固定标签保留），若当前页被关则回退
 */
function closeAllTags(view: Record<string, any>) {
  tab.closeAllPage().then(({ visitedViews }) => {
    if (affixTags.value.some((tag) => tag.path === route.path)) {
      return
    }
    toLastView(visitedViews, view)
  })
}

/*
 * 跳转到最后标签。无标签时：Dashboard 走 redirect 刷新，其他跳首页
 */
function toLastView(visitedViews: TagView[], view?: Record<string, any>) {
  const latestView = visitedViews.slice(-1)[0]
  if (latestView) {
    router.push(latestView.fullPath || '/')
  } else {
    if (view && view.name === 'Dashboard') {
      router.replace({ path: '/redirect' + view.fullPath })
    } else {
      router.push('/')
    }
  }
}

/*
 * 右键菜单：记录位置和选中标签
 */
function openMenu(tag: Record<string, any>, e: MouseEvent) {
  left.value = e.clientX
  top.value = e.clientY
  visible.value = true
  selectedTag.value = tag
}

/*
 * 关闭右键菜单
 */
function closeMenu() {
  visible.value = false
}

/*
 * 滚动时关闭右键菜单，更新箭头状态
 */
function handleScroll() {
  closeMenu()
  updateArrowState()
}
</script>

<style lang="scss" scoped>
$tags-bar-height: 34px;

.tags-view-container {
  height: $tags-bar-height;
  width: 100%;
  background: var(--tags-bg, #fff);
  border-bottom: 1px solid var(--tags-item-border, #d8dce5);
  display: flex;
  align-items: center;
  overflow: hidden;

  $btn-width: 28px;
  $btn-color: #71717a;
  $btn-hover-bg: #f0f2f5;
  $btn-hover-color: #303133;
  $btn-disabled-color: #c0c4cc;
  $divider: 1px solid var(--tags-item-border, #d8dce5);

  .tags-nav-btn {
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    width: $btn-width;
    height: $tags-bar-height;
    cursor: pointer;
    color: $btn-color;
    font-size: 13px;
    user-select: none;
    transition:
      background 0.15s,
      color 0.15s;

    &:hover:not(.disabled) {
      background: $btn-hover-bg;
      color: $btn-hover-color;
    }

    &.disabled {
      color: $btn-disabled-color;
      cursor: not-allowed;
    }

    &--left {
      border-right: $divider;
    }
    &--right {
      border-left: $divider;
    }
  }

  .tags-view-wrapper {
    flex: 1;
    min-width: 0;
    height: 100%;

    .tags-view-item {
      display: inline-flex;
      align-items: center;
      position: relative;
      cursor: pointer;
      height: 26px;
      line-height: 26px;
      border: 1px solid var(--tags-item-border, #d8dce5);
      color: var(--tags-item-text, #495060);
      background: var(--tags-item-bg, #fff);
      padding: 0 8px;
      font-size: 12px;
      margin-left: 5px;
      border-radius: 3px;
      text-decoration: none;
      vertical-align: middle;
      padding-top: 2px !important;

      &:first-of-type {
        margin-left: 6px;
      }
      &:last-of-type {
        margin-right: 15px;
      }
    }
  }

  &:not(.tags-view-container--chrome) .tags-view-wrapper .tags-view-item.active {
    background-color: #42b983;
    color: #fff;
    border-color: #42b983;

    &::before {
      content: '';
      background: #fff;
      display: inline-block;
      width: 8px;
      height: 8px;
      border-radius: 50%;
      position: relative;
      margin-right: 5px;
    }
  }

  &:not(.tags-view-container--chrome) .tags-view-wrapper .tags-view-item.active.has-icon::before {
    content: none !important;
  }

  .tags-action-dropdown {
    flex-shrink: 0;
    display: flex;
    align-items: center;
  }

  .tags-action-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: $btn-width;
    height: $tags-bar-height;
    cursor: pointer;
    color: $btn-color;
    font-size: 13px;
    border-left: $divider;
    user-select: none;
    transition:
      background 0.15s,
      color 0.15s;

    &:hover {
      background: $btn-hover-bg;
      color: $btn-hover-color;
    }
  }

  .tags-refresh-btn {
    width: 60px;
  }

  .contextmenu {
    margin: 0;
    background: var(--el-bg-color-overlay, #fff);
    z-index: 3000;
    position: fixed;
    list-style-type: none;
    padding: 5px 0;
    border-radius: 4px;
    font-size: 12px;
    font-weight: 400;
    color: var(--tags-item-text, #333);
    box-shadow: 2px 2px 3px 0 rgba(0, 0, 0, 0.3);
    border: 1px solid var(--el-border-color-light, #e4e7ed);

    li {
      margin: 0;
      padding: 7px 16px;
      cursor: pointer;

      &:hover {
        background: var(--tags-item-hover, #eee);
      }
    }
  }

  &.tags-view-container--chrome {
    --chrome-strip-bg: #ffffff;
    --chrome-strip-border: var(--el-border-color-lighter, #e4e7ed);
    --chrome-tab-active-bg: var(--el-color-primary-light-9);
    --chrome-tab-text: var(--el-text-color-regular, #606266);
    --chrome-tab-text-active: var(--el-color-primary);
    --chrome-wing-r: 10px;

    overflow: visible;
    background: var(--chrome-strip-bg);
    border-bottom: 1px solid var(--chrome-strip-border);
    align-items: flex-end;

    .tags-nav-btn {
      align-self: stretch;
      height: auto;
      min-height: $tags-bar-height;
      border-color: var(--chrome-strip-border);
    }

    .tags-action-btn {
      border-color: var(--chrome-strip-border);
    }

    .tags-view-wrapper {
      .tags-view-item {
        display: inline-flex !important;
        align-items: center;
        justify-content: center;
        position: relative;
        z-index: 1;
        height: 30px;
        min-height: 30px;
        margin: 0 0 -1px;
        padding: 0 12px;
        font-size: 13px;
        font-weight: 400;
        line-height: 1.2;
        border: none !important;
        border-radius: 0;
        background: transparent !important;
        color: var(--chrome-tab-text);
        padding-top: 0 !important;
        box-shadow: none !important;
        transition:
          background 0.12s ease,
          color 0.12s ease,
          border-radius 0.12s ease;

        &::before,
        &::after {
          content: '' !important;
          display: block !important;
          position: absolute;
          bottom: 0;
          width: var(--chrome-wing-r);
          height: var(--chrome-wing-r);
          margin: 0 !important;
          pointer-events: none;
          background: transparent !important;
          border-radius: 0 !important;
          transition: box-shadow 0.12s ease;
        }

        &::before {
          left: calc(-1 * var(--chrome-wing-r));
          border-bottom-right-radius: var(--chrome-wing-r) !important;
          box-shadow: none;
        }

        &::after {
          right: calc(-1 * var(--chrome-wing-r));
          border-bottom-left-radius: var(--chrome-wing-r) !important;
          box-shadow: none;
        }

        &:first-of-type {
          margin-left: 6px;
        }

        &:last-of-type {
          margin-right: 10px;
        }

        &:not(.active) + .tags-view-item:not(.active) {
          border-left: 1px solid var(--el-border-color-lighter, #e4e7ed);
          padding-left: 11px;
        }

        &:hover:not(.active) {
          background: var(--el-fill-color-light, #f5f7fa) !important;
          border-radius: 6px 6px 0 0;
          color: var(--el-text-color-primary, #303133);
        }

        &.active {
          height: 31px;
          min-height: 31px;
          padding: 0 14px;
          color: var(--chrome-tab-text-active) !important;
          font-weight: 500;
          background: var(--chrome-tab-active-bg) !important;
          border: none !important;
          border-radius: var(--chrome-wing-r) var(--chrome-wing-r) 0 0;
          box-shadow: 0 1px 4px rgba(0, 0, 0, 0.06);

          &::before {
            box-shadow: calc(var(--chrome-wing-r) * 0.5) calc(var(--chrome-wing-r) * 0.5) 0 calc(var(--chrome-wing-r) * 0.5)
              var(--chrome-tab-active-bg);
          }

          &::after {
            box-shadow: calc(var(--chrome-wing-r) * -0.5) calc(var(--chrome-wing-r) * 0.5) 0 calc(var(--chrome-wing-r) * 0.5)
              var(--chrome-tab-active-bg);
          }
        }
      }
    }
  }
}
</style>

<style lang="scss">
.tags-view-wrapper {
  .tags-view-item {
    .tags-close-btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 16px;
      height: 16px;
      margin-left: 4px;
      border-radius: 50%;
      transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
      cursor: pointer;

      .el-icon-close {
        width: 1em;
        height: 1em;
        vertical-align: 0;
        line-height: 1;
        display: inline-flex;
        align-items: center;
        justify-content: center;
      }

      &:hover {
        background-color: var(--tags-close-hover, #b4bccc);

        .el-icon-close {
          color: #fff;
        }
      }
    }
  }
}

/* 页签全屏模式样式 */
.main-container.fullscreen-mode {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  margin-left: 0 !important;
  transition: none !important;
}

.main-container.fullscreen-mode .fixed-header {
  display: block !important;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  width: 100% !important;
  z-index: 1000;
  transition: none !important;
}

.main-container.fullscreen-mode .fixed-header .navbar {
  display: none !important;
}

.main-container.fullscreen-mode .app-main {
  position: fixed;
  top: 34px;
  left: 0;
  right: 0;
  bottom: 0;
  margin: 0 !important;
  padding: 0 !important;
  height: calc(100vh - 34px) !important;
  min-height: calc(100vh - 34px) !important;
  overflow: auto;
}
</style>

// xxl-boot-ui-react/src/layout/components/TagsView/index.tsx
/**
 * 组件：TagsView（多标签页）
 * 功能：顶部多标签页管理，支持标签切换、关闭、刷新、全屏显示，以及右键/下拉菜单操作。
 *       支持 card 和 chrome 两种标签样式。
 */
import { useEffect, useRef, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Dropdown } from 'antd'
import type { MenuProps } from 'antd'
import { LeftOutlined, RightOutlined, DownOutlined, ReloadOutlined } from '@ant-design/icons'
import { useAliveController } from 'react-activation'
import ScrollPane, { type ScrollPaneHandle } from './ScrollPane'
import SvgIcon from '@/components/SvgIcon'
import { getNormalPath } from '@/utils/common'
import { useTagsViewStore, useRoutesStore, useSettingsStore } from '@/stores'
import type { TagView } from '@/stores/tagsView'
import type { RouteData } from '@/stores/routes'
import tab from '@/utils/tab'
import defaultSettings from '@/default-settings'
import './tagsView.scss'

/**
 * 多标签页
 */
export default function TagsView() {
  const location = useLocation()
  const navigate = useNavigate()
  const tagsViewStore = useTagsViewStore()
  const routesStore = useRoutesStore()
  const settingsStore = useSettingsStore()
  const { refresh } = useAliveController()

  // 右键上下文菜单
  const [visible, setVisible] = useState(false)
  const [top, setTop] = useState(0)
  const [left, setLeft] = useState(0)
  const [selectedTag, setSelectedTag] = useState<Record<string, any>>({})
  // 持久化固定标签
  const affixTagsRef = useRef<any[]>([])
  const scrollPaneRef = useRef<ScrollPaneHandle>(null)
  // 左右箭头状态
  const [canScrollLeft, setCanScrollLeft] = useState(false)
  const [canScrollRight, setCanScrollRight] = useState(false)
  // 页内全屏状态
  const [isFullscreen, setIsFullscreen] = useState(false)
  const hiddenElementsRef = useRef<{ el: HTMLElement | null; originalDisplay: string }[]>([])

  const visitedViews = tagsViewStore.visitedViews
  const theme = settingsStore.theme
  const tagsIcon = settingsStore.tagsIcon
  const tagsViewPersist = settingsStore.tagsViewPersist
  const tagsViewStyle = settingsStore.tagsViewStyle

  // 当前路由
  const route = {
    path: location.pathname,
    fullPath: location.pathname + location.search,
    name: location.pathname,
    query: Object.fromEntries(new URLSearchParams(location.search).entries())
  }

  // 下拉菜单针对当前激活的 tag
  const selectedDropdownTag = visitedViews.find((v) => isActive(v)) || ({} as TagView)

  /*
   * 路由变化时添加新标签并滚动到当前标签
   */
  useEffect(() => {
    addTags()
    moveToCurrentTag()
     
  }, [location.pathname, location.search])

  /*
   * 右键菜单显隐时切换 body 点击监听
   */
  useEffect(() => {
    const closeMenu = () => setVisible(false)
    if (visible) {
      document.body.addEventListener('click', closeMenu)
    } else {
      document.body.removeEventListener('click', closeMenu)
    }
    return () => {
      document.body.removeEventListener('click', closeMenu)
    }
  }, [visible])

  /*
   * visitedViews 变化后更新箭头状态
   */
  useEffect(() => {
    setTimeout(() => updateArrowState(), 0)
  }, [visitedViews])

  /*
   * 挂载：初始化固定标签 + 持久化恢复 + 监听窗口
   */
  useEffect(() => {
    initTags()
    window.addEventListener('resize', updateArrowState)
    window.addEventListener('keydown', handleKeyDown)
    return () => {
      window.removeEventListener('resize', updateArrowState)
      window.removeEventListener('keydown', handleKeyDown)
    }
     
  }, [])

  /*
   * Esc 退出全屏
   */
  const handleKeyDown = (event: KeyboardEvent) => {
    if (event.key === 'Escape' && isFullscreen) {
      toggleFullscreen()
    }
  }

  /*
   * 当前路由是否为标签页
   */
  function isActive(r: Record<string, any>) {
    return r.path === route.path
  }

  /*
   * 激活标签高亮样式（card 模式下）
   */
  function tagActiveStyle(tag: Record<string, any>): React.CSSProperties {
    if (!isActive(tag) || tagsViewStyle !== 'card') return {}
    return {
      backgroundColor: theme,
      borderColor: theme
    }
  }

  /*
   * 是否为固定标签（不可关闭）
   */
  function isAffix(tag: Record<string, any>) {
    return tag && tag.meta && tag.meta.affix
  }

  /*
   * 是否为最左标签
   */
  function isFirstView() {
    try {
      const tag = selectedTag && selectedTag.fullPath ? selectedTag : selectedDropdownTag
      return tag.fullPath === defaultSettings.homePath || tag.fullPath === visitedViews[1]?.fullPath
    } catch (err) {
      return false
    }
  }

  /*
   * 是否为最右标签
   */
  function isLastView() {
    try {
      const tag = selectedTag && selectedTag.fullPath ? selectedTag : selectedDropdownTag
      return tag.fullPath === visitedViews[visitedViews.length - 1]?.fullPath
    } catch (err) {
      return false
    }
  }

  /*
   * 递归收集带 affix 标记的固定标签（首页/特殊页面）
   */
  function filterAffixTags(routes: RouteData[], basePath = ''): TagView[] {
    let tags: TagView[] = []
    routes.forEach((route) => {
      if (route.meta && route.meta.affix) {
        const tagPath = route.path!.startsWith('/') ? getNormalPath(route.path!) : getNormalPath(basePath + '/' + route.path!)
        tags.push({
          fullPath: tagPath,
          path: tagPath,
          name: route.name,
          meta: { ...route.meta }
        })
      }
      if (route.children) {
        const tempTags = filterAffixTags(route.children, route.path)
        if (tempTags.length >= 1) {
          tags = [...tags, ...tempTags]
        }
      }
    })
    return tags
  }

  /*
   * 初始化：持久化恢复 + 固定标签注册
   */
  function initTags() {
    if (tagsViewPersist) {
      tagsViewStore.loadPersistedViews()
    }
    const res = filterAffixTags(routesStore.fullRoutes)
    affixTagsRef.current = res
    for (const tag of res) {
      if (tag.name) {
        tagsViewStore.addAffixView(tag)
      }
    }
  }

  /*
   * 当前路由加入标签页
   */
  function addTags() {
    const title = findTitle(route.path)
    if (route.path) {
      tagsViewStore.addView({ path: route.path, fullPath: route.fullPath, name: route.path, query: route.query, meta: { title } })
    }
  }

  /*
   * 滚动到当前标签，同步路由更新
   */
  function moveToCurrentTag() {
    setTimeout(() => {
      for (const r of visitedViews) {
        if (r.path === route.path) {
          scrollPaneRef.current?.moveToTarget(r)
          if (r.fullPath !== route.fullPath) {
            tagsViewStore.updateVisitedView({ ...route, meta: { title: r.title } })
          }
        }
      }
    }, 0)
  }

  /*
   * 左 / 右箭头滚动标签栏
   */
  const scrollLeft = () => {
    if (!canScrollLeft) return
    scrollPaneRef.current?.scrollToStart()
  }

  const scrollRight = () => {
    if (!canScrollRight) return
    scrollPaneRef.current?.scrollToEnd()
  }

  /*
   * 更新左右箭头可用状态
   */
  function updateArrowState() {
    setTimeout(() => {
      if (scrollPaneRef.current) {
        const state = scrollPaneRef.current.getScrollState()
        setCanScrollLeft(state.canLeft)
        setCanScrollRight(state.canRight)
      }
    }, 0)
  }

  /*
   * 全屏模式：隐藏 navbar/sidebar 使内容区占满视口
   */
  function toggleFullscreen() {
    const mainContainer = document.querySelector<HTMLElement>('.main-container')
    const navbar = document.querySelector<HTMLElement>('.navbar')
    const sidebar = document.querySelector<HTMLElement>('.sidebar-container')
    if (!mainContainer) return

    if (!isFullscreen) {
      mainContainer.classList.add('fullscreen-mode')
      document.body.style.overflow = 'hidden'
      const elementsToHide = [
        { el: navbar, originalDisplay: navbar?.style.display || '' },
        { el: sidebar, originalDisplay: sidebar?.style.display || '' }
      ]
      const hidden: { el: HTMLElement | null; originalDisplay: string }[] = []
      elementsToHide.forEach((item) => {
        if (item.el && item.el.style.display !== 'none') {
          item.originalDisplay = item.el.style.display
          item.el.style.display = 'none'
          hidden.push(item)
        }
      })
      hiddenElementsRef.current = hidden
      setIsFullscreen(true)
    } else {
      mainContainer.classList.remove('fullscreen-mode')
      document.body.style.overflow = ''
      hiddenElementsRef.current.forEach((item) => {
        if (item.el) {
          item.el.style.display = item.originalDisplay
        }
      })
      hiddenElementsRef.current = []
      setIsFullscreen(false)
    }
  }

  /*
   * 下拉菜单命令分发
   */
  const handleDropdownCommand = (command: string) => {
    const tag = selectedDropdownTag
    setSelectedTag(tag)
    switch (command) {
      case 'refresh':
        refreshSelectedTag(tag)
        break
      case 'fullscreen':
        toggleFullscreen()
        break
      case 'close':
        closeSelectedTag(tag)
        break
      case 'closeOthers':
        closeOthersTags()
        break
      case 'closeLeft':
        closeLeftTags()
        break
      case 'closeRight':
        closeRightTags()
        break
      case 'closeAll':
        closeAllTags(tag)
        break
    }
  }

  /*
   * 刷新指定标签页（react-activation refresh 重挂载）
   */
  const refreshSelectedTag = (view: Record<string, any>) => {
    if (view.path && view.path.startsWith('/redirect/')) return
    // 刷新：销毁并重建对应 KeepAlive 缓存节点
    refresh(view.path)
  }

  /*
   * 关闭标签：若关闭的是当前标签则跳转到最后标签
   */
  const closeSelectedTag = (view: Record<string, any>) => {
    tab.closePage(view).then(() => {
      if (isActive(view)) {
        toLastView(tagsViewStore.visitedViews, view)
      }
    })
  }

  /*
   * 关闭右侧标签，若当前标签被关则回退
   */
  const closeRightTags = () => {
    tab.closeRightPage(selectedTag).then(() => {
      if (!tagsViewStore.visitedViews.find((i) => i.fullPath === route.fullPath)) {
        toLastView(tagsViewStore.visitedViews)
      }
    })
  }

  /*
   * 关闭左侧标签，若当前标签被关则回退
   */
  const closeLeftTags = () => {
    tab.closeLeftPage(selectedTag).then(() => {
      if (!tagsViewStore.visitedViews.find((i) => i.fullPath === route.fullPath)) {
        toLastView(tagsViewStore.visitedViews)
      }
    })
  }

  /*
   * 关闭其他标签：先跳转到目标标签再关闭其他
   */
  const closeOthersTags = () => {
    navigate(selectedTag.path || '/')
    tab.closeOtherPage(selectedTag).then(() => {
      moveToCurrentTag()
    })
  }

  /*
   * 关闭全部标签（固定标签保留），若当前页被关则回退
   */
  const closeAllTags = (view: Record<string, any>) => {
    tab.closeAllPage().then(() => {
      if (affixTagsRef.current.some((tag) => tag.path === route.path)) {
        return
      }
      toLastView(tagsViewStore.visitedViews, view)
    })
  }

  /*
   * 跳转到最后标签。无标签时：Dashboard 走 redirect 刷新，其他跳首页
   */
  function toLastView(visited: TagView[], view?: Record<string, any>) {
    const latestView = visited.slice(-1)[0]
    if (latestView) {
      navigate(latestView.fullPath || '/')
    } else {
      if (view && view.name === 'Dashboard') {
        navigate('/redirect' + view.fullPath, { replace: true })
      } else {
        navigate('/')
      }
    }
  }

  /*
   * 右键菜单：记录位置和选中标签
   */
  const openMenu = (tag: Record<string, any>, e: React.MouseEvent) => {
    setLeft(e.clientX)
    setTop(e.clientY)
    setVisible(true)
    setSelectedTag(tag)
  }

  /*
   * 滚动时关闭右键菜单，更新箭头状态
   */
  const handleScroll = () => {
    setVisible(false)
    updateArrowState()
  }

  // 下拉菜单项
  const dropdownItems: MenuProps['items'] = [
    ...(!isAffix(selectedDropdownTag) ? [{ key: 'close', label: <span><SvgIcon iconClass="close" /> 关闭当前</span> }] : []),
    { key: 'closeOthers', label: <span>关闭其他</span> },
    { key: 'closeLeft', label: <span>关闭左侧</span>, disabled: isFirstView() },
    { key: 'closeRight', label: <span>关闭右侧</span>, disabled: isLastView() },
    { key: 'closeAll', label: <span>全部关闭</span> },
    { key: 'fullscreen', label: <span>{isFullscreen ? '退出全屏' : '全屏显示'}</span> }
  ]

  return (
    <div id="tags-view-container" className={`tags-view-container ${tagsViewStyle === 'chrome' ? 'tags-view-container--chrome' : ''}`}>
      {/* 左箭头 */}
      <span className={`tags-nav-btn tags-nav-btn--left ${canScrollLeft ? '' : 'disabled'}`} onClick={scrollLeft}>
        <LeftOutlined />
      </span>

      {/* scroll pane */}
      <ScrollPane ref={scrollPaneRef} className="tags-view-wrapper" onScroll={handleScroll} onUpdateArrows={updateArrowState}>
        {visitedViews.map((tag) => (
          <Link
            key={tag.path}
            to={{ pathname: tag.path, search: tag.query ? toSearchString(tag.query) : '' }}
            data-path={tag.path}
            className={`tags-view-item ${isActive(tag) ? 'active' : ''} ${tagsIcon ? 'has-icon' : ''}`}
            style={tagActiveStyle(tag)}
            onAuxClick={(e) => {
              if (e.button === 1 && !isAffix(tag)) {
                closeSelectedTag(tag)
              }
            }}
            onContextMenu={(e) => {
              e.preventDefault()
              openMenu(tag, e)
            }}
          >
            {/* icon */}
            {!!(tagsIcon && tag.meta && tag.meta.icon && tag.meta.icon !== '#') && (
              <SvgIcon iconClass={String(tag.meta.icon)} style={{ marginRight: 3 }} />
            )}
            {/* title */}
            {tag.title}
            {/* close */}
            {!isAffix(tag) && (
              <span
                className="tags-close-btn"
                onClick={(e) => {
                  e.preventDefault()
                  e.stopPropagation()
                  closeSelectedTag(tag)
                }}
              >
                <svg viewBox="0 0 1024 1024" width="1em" height="1em" fill="currentColor" aria-hidden="true">
                  <path d="M563.8 512l262.5-312.9c4.4-5.2.7-13.1-6.1-13.1h-79.8c-4.7 0-9.2 2.1-12.3 5.7L511.6 449.8 295.1 191.7c-3-3.6-7.5-5.7-12.3-5.7H203c-6.8 0-10.5 7.9-6.1 13.1L459.4 512 196.9 824.9A7.95 7.95 0 0 0 203 838h79.8c4.7 0 9.2-2.1 12.3-5.7l216.5-258.1 216.5 258.1c3 3.6 7.5 5.7 12.3 5.7h79.8c6.8 0 10.5-7.9 6.1-13.1L563.8 512z" />
                </svg>
              </span>
            )}
          </Link>
        ))}
      </ScrollPane>

      {/* 右箭头 */}
      <span className={`tags-nav-btn tags-nav-btn--right ${canScrollRight ? '' : 'disabled'}`} onClick={scrollRight}>
        <RightOutlined />
      </span>

      {/* 下拉操作菜单 */}
      <Dropdown menu={{ items: dropdownItems, onClick: ({ key }) => handleDropdownCommand(key) }} trigger={['click']} placement="bottomRight">
        <span className="tags-action-btn">
          <DownOutlined />
        </span>
      </Dropdown>

      {/* 刷新按钮 */}
      <span className="tags-action-btn tags-refresh-btn" title="刷新页面" onClick={() => refreshSelectedTag(selectedDropdownTag)}>
        <ReloadOutlined /> 刷新
      </span>

      {/* 右键上下文菜单 */}
      {visible && (
        <ul style={{ left: `${left}px`, top: `${top}px` }} className="contextmenu">
          <li onClick={() => refreshSelectedTag(selectedTag)}>
            <ReloadOutlined /> 刷新页面
          </li>
          {!isAffix(selectedTag) && (
            <li onClick={() => closeSelectedTag(selectedTag)}>
              <svg viewBox="0 0 1024 1024" width="1em" height="1em" fill="currentColor" aria-hidden="true">
                <path d="M563.8 512l262.5-312.9c4.4-5.2.7-13.1-6.1-13.1h-79.8c-4.7 0-9.2 2.1-12.3 5.7L511.6 449.8 295.1 191.7c-3-3.6-7.5-5.7-12.3-5.7H203c-6.8 0-10.5 7.9-6.1 13.1L459.4 512 196.9 824.9A7.95 7.95 0 0 0 203 838h79.8c4.7 0 9.2-2.1 12.3-5.7l216.5-258.1 216.5 258.1c3 3.6 7.5 5.7 12.3 5.7h79.8c6.8 0 10.5-7.9 6.1-13.1L563.8 512z" />
              </svg>{' '}
              关闭当前
            </li>
          )}
          <li onClick={closeOthersTags}>
            <span className="contextmenu-icon" />关闭其他
          </li>
          {!isFirstView() && <li onClick={closeLeftTags}>关闭左侧</li>}
          {!isLastView() && <li onClick={closeRightTags}>关闭右侧</li>}
          <li onClick={() => closeAllTags(selectedTag)}>全部关闭</li>
        </ul>
      )}
    </div>
  )
}

/**
 * 查询参数对象转 search 字符串
 */
function toSearchString(query: Record<string, unknown>): string {
  const searchParams = new URLSearchParams()
  Object.keys(query).forEach((key) => {
    const value = query[key]
    if (value != null && value !== '') {
      searchParams.set(key, String(value))
    }
  })
  const str = searchParams.toString()
  return str ? `?${str}` : ''
}

/**
 * 查找路由标题
 */
function findTitle(path: string): string {
  const routes = useRoutesStore.getState().fullRoutes
  const stack = [...routes]
  while (stack.length > 0) {
    const route = stack.pop()
    if (!route) continue
    if (route.children && route.children.length) {
      stack.push(...(route.children as RouteData[]))
    }
    if (route.path === path) {
      return route.meta?.title || ''
    }
  }
  return ''
}
