// xxl-boot-ui-vue/src/views/tool/pagegen/index.vue
<!--
  页面：表单设计器（首页）
  功能：拖拽式表单设计，支持组件添加、属性配置、代码生成
-->
<template>
  <div class="container">
    <!-- 左侧面板 -->
    <div class="left-board">
      <!-- 标题 -->
      <div class="logo-wrapper">
        <div class="logo">表单生成器 / Form Generator</div>
      </div>

      <!-- 组件选择区 -->
      <el-scrollbar class="left-scrollbar">
        <div class="components-list">
          <div class="components-title">
            <SvgIcon icon-class="component" />
            输入型组件
          </div>
          <draggable
            class="components-draggable"
            :list="inputComponents"
            :group="{ name: 'componentsGroup', pull: 'clone', put: false }"
            :clone="cloneComponent"
            draggable=".components-item"
            :sort="false"
            @end="onEnd"
            item-key="label"
          >
            <template #item="{ element, index }">
              <div :key="index" class="components-item" @click="addComponent(element)">
                <div class="components-body">
                  <SvgIcon :icon-class="element.tagIcon" />
                  {{ element.label }}
                </div>
              </div>
            </template>
          </draggable>

          <div class="components-title">
            <SvgIcon icon-class="component" />
            选择型组件
          </div>
          <draggable
            class="components-draggable"
            :list="selectComponents"
            :group="{ name: 'componentsGroup', pull: 'clone', put: false }"
            :clone="cloneComponent"
            draggable=".components-item"
            :sort="false"
            @end="onEnd"
            item-key="label"
          >
            <template #item="{ element, index }">
              <div :key="index" class="components-item" @click="addComponent(element)">
                <div class="components-body">
                  <SvgIcon :icon-class="element.tagIcon" />
                  {{ element.label }}
                </div>
              </div>
            </template>
          </draggable>

          <div class="components-title">
            <SvgIcon icon-class="component" />
            布局型组件
          </div>
          <draggable
            class="components-draggable"
            :list="layoutComponents"
            :group="{ name: 'componentsGroup', pull: 'clone', put: false }"
            :clone="cloneComponent"
            draggable=".components-item"
            :sort="false"
            @end="onEnd"
            item-key="label"
          >
            <template #item="{ element, index }">
              <div :key="index" class="components-item" @click="addComponent(element)">
                <div class="components-body">
                  <SvgIcon :icon-class="element.tagIcon" />
                  {{ element.label }}
                </div>
              </div>
            </template>
          </draggable>
        </div>
      </el-scrollbar>
    </div>

    <!-- 中间画布 -->
    <div class="center-board">
      <!-- 中间画布操作栏 -->
      <div class="action-bar">
        <el-button icon="Download" type="primary" text @click="download"> 导出vue文件 </el-button>
        <el-button class="copy-btn-main" icon="DocumentCopy" type="primary" text @click="copy"> 复制代码 </el-button>
        <el-button class="delete-btn" icon="Delete" text @click="empty" type="danger"> 清空 </el-button>
      </div>

      <!-- 中间画布 -->
      <el-scrollbar class="center-scrollbar">
        <el-row class="center-board-row" :gutter="formConf.gutter">
          <el-form
            :size="formConf.size"
            :label-position="formConf.labelPosition"
            :disabled="formConf.disabled"
            :label-width="formConf.labelWidth + 'px'"
          >
            <!-- 拖拽区域内容 -->
            <draggable class="drawing-board" :list="canvas.drawingList" :animation="340" group="componentsGroup" item-key="label">
              <template #item="{ element, index }">
                <DraggableItem
                  :key="element.renderKey"
                  :drawing-list="canvas.drawingList"
                  :element="element"
                  :index="index"
                  :active-id="canvas.activeId"
                  :form-conf="formConf"
                  @activeItem="activeFormItem"
                  @copyItem="drawingItemCopy"
                  @deleteItem="drawingItemDelete"
                />
              </template>
            </draggable>

            <!-- 拖拽区域，为空 -->
            <div v-show="!canvas.drawingList.length" class="empty-info">从左侧拖入或点选组件进行表单设计</div>
          </el-form>
        </el-row>
      </el-scrollbar>
    </div>

    <!-- 右侧属性面板 -->
    <RightPanel :active-data="canvas.activeData" :form-conf="formConf" :show-field="!!canvas.drawingList.length" @tag-change="tagChange" />

    <!-- 代码生成类型选择弹窗 -->
    <CodeTypeDialog
      v-model="genDialog.dialogVisible"
      title="选择生成类型"
      :genDialog.showFileName="genDialog.showFileName"
      @confirm="generate"
    />

    <!-- 隐藏的复制节点 -->
    <input id="copyNode" type="hidden" />
  </div>
</template>

<script setup lang="ts">
/**
 * 表单设计器 - 主逻辑
 * 1. 左侧组件库：输入型、选择型、布局型组件列表
 * 2. 中间画布：拖拽放置组件，支持选中、复制、删除
 * 3. 右侧面板：组件属性 / 表单属性配置
 * 4. 代码生成：导出 vue 文件或复制代码
 */
import type { FormConf, FormItemConf } from '@/utils/generator/config'
import draggable from 'vuedraggable'
import ClipboardJS from 'clipboard'
import beautifier from 'js-beautify'
import { inputComponents, selectComponents, layoutComponents, formConf as formConfData } from '@/utils/generator/config'
import { beautifierConf } from '@/utils/generator/config'
import { drawingDefaultValue, initDrawingDefaultValue, cleanDrawingDefaultValue } from '@/utils/generator/drawingDefault'
import { makeUpHtml, vueTemplate, vueScript, cssStyle } from '@/utils/generator/html'
import { makeUpJs } from '@/utils/generator/js'
import { makeUpCss } from '@/utils/generator/css'
import Download from '@/utils/download'
import modal from '@/utils/modal'
import { ElNotification } from 'element-plus'
import DraggableItem from './DraggableItem.vue'
import RightPanel from './RightPanel.vue'
import CodeTypeDialog from './CodeTypeDialog.vue'
import { onMounted, watch } from 'vue'
import { nextTick, onUnmounted, provide, ref } from 'vue'

// --------------------------------- ref data ---------------------------------

// 初始化画布默认配置
initDrawingDefaultValue()

/* 画布状态 */
const canvas = ref<{
  drawingList: FormItemConf[] /* 画布中的组件列表 */
  activeData: FormItemConf /* 当前选中组件 */
  activeId: number | string /* 当前选中组件 ID */
}>({
  drawingList: drawingDefaultValue,
  activeData: drawingDefaultValue[0],
  activeId: drawingDefaultValue[0].formId!
})
let oldActiveId: number | string | undefined /* 上一次选中 ID，用于 placeholder 联动 */
let tempActiveData: FormItemConf | undefined /* 拖拽结束暂存激活组件 */

/* 生成代码弹窗状态 */
const genDialog = ref({
  dialogVisible: false /* 生成类型弹窗 */,
  showFileName: false /* 是否显示文件名输入 */,
  operationType: '' /* 操作类型：copy / download */,
  generateConf: null as any /* 生成配置 */,
  formData: {} as FormConf & { fields: FormItemConf[] } /* 表单组装数据 */
})

/* 全局配置 */
const idGlobal = ref(100) /* 全局组件 ID 自增 */
provide('idGlobal', idGlobal)
const formConf = ref(formConfData) /* 表单全局配置 */

// --------------------------------- fun ---------------------------------

/**
 * 激活选中组件
 */
function activeFormItem(element: FormItemConf) {
  canvas.value.activeData = element
  canvas.value.activeId = element.formId!
}

/**
 * 复制代码：打开弹框，不显示文件
 */
function copy() {
  genDialog.value.dialogVisible = true
  genDialog.value.showFileName = false
  genDialog.value.operationType = 'copy'
}

/**
 * 下载 vue 文件：打开弹框，显示文件属性
 */
function download() {
  genDialog.value.dialogVisible = true
  genDialog.value.showFileName = true
  genDialog.value.operationType = 'download'
}

/**
 * 清空画布所有组件
 */
function empty() {
  modal.confirm('确定要清空所有组件吗？').then(() => {
    idGlobal.value = 100
    canvas.value.drawingList = []
    cleanDrawingDefaultValue()
  })
}

/**
 * 拖拽结束回调：从组件库拖入画布时，激活拖入的组件
 */
function onEnd(obj: any) {
  if (obj.from !== obj.to) {
    canvas.value.activeData = tempActiveData!
    canvas.value.activeId = idGlobal.value
  }
}

/**
 * 点击添加组件到画布
 */
function addComponent(item: FormItemConf) {
  const clone = cloneComponent(item)
  canvas.value.drawingList.push(clone)
  activeFormItem(clone)
}

/**
 * 克隆组件：生成新 ID、设置 vModel / componentName
 */
function cloneComponent(origin: FormItemConf): FormItemConf {
  const clone: FormItemConf = JSON.parse(JSON.stringify(origin))
  clone.formId = ++idGlobal.value
  clone.span = formConf.value.span
  clone.renderKey = +new Date() /* 改变 renderKey 实现强制更新 */
  if (!clone.layout) clone.layout = 'colFormItem'
  if (clone.layout === 'colFormItem') {
    clone.vModel = `field${idGlobal.value}`
    clone.placeholder !== undefined && (clone.placeholder += clone.label)
    tempActiveData = clone
  } else if (clone.layout === 'rowFormItem') {
    delete clone.label
    clone.componentName = `row${idGlobal.value}`
    clone.gutter = formConf.value.gutter
    tempActiveData = clone
  }
  return tempActiveData as FormItemConf
}

/**
 * 复制画布中的组件
 */
function drawingItemCopy(item: FormItemConf, parent: FormItemConf[]) {
  let clone = JSON.parse(JSON.stringify(item)) as FormItemConf
  clone = createIdAndKey(clone)
  parent.push(clone)
  activeFormItem(clone)
}

/**
 * 递归生成新 ID 和 renderKey
 */
function createIdAndKey(item: FormItemConf): FormItemConf {
  item.formId = ++idGlobal.value
  item.renderKey = +new Date()
  if (item.layout === 'colFormItem') {
    item.vModel = `field${idGlobal.value}`
  } else if (item.layout === 'rowFormItem') {
    item.componentName = `row${idGlobal.value}`
  }
  if (Array.isArray(item.children)) {
    item.children = item.children.map((childItem) => createIdAndKey(childItem))
  }
  return item
}

/**
 * 删除画布中的组件
 */
function drawingItemDelete(index: number | undefined, parent: FormItemConf[]) {
  parent.splice(index as number, 1)
  nextTick(() => {
    const len = canvas.value.drawingList.length
    if (len) {
      activeFormItem(canvas.value.drawingList[len - 1])
    }
  })
}

/**
 * 切换组件类型：保留 vModel / formId / span，替换其他属性
 */
function tagChange(newTag: FormItemConf) {
  newTag = cloneComponent(newTag)
  newTag.vModel = canvas.value.activeData.vModel
  newTag.formId = canvas.value.activeId
  newTag.span = canvas.value.activeData.span
  delete canvas.value.activeData.tag
  delete canvas.value.activeData.tagIcon
  delete canvas.value.activeData.document
  Object.keys(newTag).forEach((key) => {
    if (canvas.value.activeData[key] !== undefined && typeof canvas.value.activeData[key] === typeof newTag[key]) {
      newTag[key] = canvas.value.activeData[key]
    }
  })
  canvas.value.activeData = newTag
  updateDrawingList(newTag, canvas.value.drawingList)
}

/**
 * 更新画布中的组件数据
 */
function updateDrawingList(newTag: FormItemConf, list: FormItemConf[]) {
  const index = list.findIndex((item) => item.formId === canvas.value.activeId)
  if (index > -1) {
    list.splice(index, 1, newTag)
  } else {
    list.forEach((item) => {
      if (Array.isArray(item.children)) updateDrawingList(newTag, item.children)
    })
  }
}

/**
 * 生成代码：组件回调- 弹窗确认后执行
 */
function generate(data: any) {
  genDialog.value.generateConf = data
  nextTick(() => {
    switch (genDialog.value.operationType) {
      case 'copy':
        execCopy(data)
        break
      case 'download':
        execDownload(data)
        break
      default:
        break
    }
  })
}

/**
 * 下载 vue 文件
 */
function execDownload(data: any) {
  const codeStr = generateCode()
  const blob = new Blob([codeStr], { type: 'text/plain;charset=utf-8' })
  Download.saveAs(blob, data.fileName)
}

/**
 * 复制代码到剪切板
 */
function execCopy(data: any) {
  document.getElementById('copyNode')!.click()
}

/**
 * 组装表单数据：画布组件 + 全局配置
 */
function AssembleFormData() {
  genDialog.value.formData = { fields: JSON.parse(JSON.stringify(canvas.value.drawingList)), ...formConf.value }
}

/**
 * 生成 vue 代码（html + script + css）
 */
function generateCode() {
  const { type } = genDialog.value.generateConf
  AssembleFormData()
  const script = vueScript(makeUpJs(genDialog.value.formData, type))
  const html = vueTemplate(makeUpHtml(genDialog.value.formData, type))
  const css = cssStyle(makeUpCss(genDialog.value.formData))
  return beautifier.html(html + script + css, beautifierConf.html)
}

// --------------------------------- init ---------------------------------

/* 监听标题变化，同步更新占位提示 */
watch(
  () => canvas.value.activeData.label,
  (val, oldVal) => {
    if (canvas.value.activeData.placeholder === undefined || !canvas.value.activeData.tag || oldActiveId !== canvas.value.activeId) {
      return
    }
    canvas.value.activeData.placeholder = canvas.value.activeData.placeholder.replace(oldVal, '') + val
  }
)

/* 记录当前激活 ID，用于上文 watch */
watch(
  () => canvas.value.activeId,
  (val) => {
    oldActiveId = val
  },
  { immediate: true }
)

/* 初始化剪切板复制 */
let clipboard: ClipboardJS | null = null
onMounted(() => {
  clipboard = new ClipboardJS('#copyNode', {
    text: (trigger) => {
      const codeStr = generateCode()
      ElNotification({ title: '成功', message: '代码已复制到剪切板，可粘贴。', type: 'success' })
      return codeStr
    }
  })
  clipboard.on('error', (e) => {
    modal.msgError('代码复制失败')
  })
})
onUnmounted(() => {
  clipboard?.destroy()
})
</script>

<style lang="scss">
$lighterBlue: #409eff;

.container {
  position: relative;
  width: 100%;
  background-color: var(--el-bg-color-overlay);
  height: calc(100vh - 50px - 40px);
  overflow: hidden;

  .left-board {
    width: 260px;
    position: absolute;
    left: 0;
    top: 0;
    height: calc(100vh - 50px - 40px);

    .logo-wrapper {
      position: relative;
      height: 42px;
      border-bottom: 1px solid var(--el-border-color-extra-light);
      box-sizing: border-box;

      .logo {
        position: absolute;
        left: 12px;
        top: 6px;
        line-height: 30px;
        color: #00afff;
        font-weight: 600;
        font-size: 17px;
        white-space: nowrap;

        .github {
          display: inline-block;
          vertical-align: sub;
          margin-left: 15px;
        }
      }
    }

    .left-scrollbar {
      .el-scrollbar__wrap {
        box-sizing: border-box;
        overflow-x: hidden !important;
        margin-bottom: 0 !important;

        .components-list {
          padding: 8px;
          box-sizing: border-box;
          height: 100%;

          .components-title {
            font-size: 14px;
            // color: #222;
            margin: 6px 2px;

            .svg-icon {
              // color: #666;
              font-size: 18px;
              margin-right: 5px;
            }
          }

          .components-draggable {
            padding-bottom: 20px;

            .components-item {
              display: inline-block;
              width: 48%;
              margin: 1%;
              transition: transform 0ms !important;

              .components-body {
                padding: 8px 10px;
                background: var(--el-border-color-extra-light);
                font-size: 12px;
                cursor: move;
                border: 1px dashed var(--el-border-color-extra-light);
                border-radius: 3px;

                .svg-icon {
                  // color: #777;
                  font-size: 15px;
                  margin-right: 5px;
                }

                &:hover {
                  border: 1px dashed #787be8;
                  color: #787be8;

                  .svg-icon {
                    color: #787be8;
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  .center-board {
    height: calc(100vh - 50px - 40px);
    width: auto;
    margin: 0 350px 0 260px;
    box-sizing: border-box;

    .action-bar {
      position: relative;
      height: 42px;
      padding: 0 15px;
      box-sizing: border-box;
      border: 1px solid var(--el-border-color-extra-light);
      border-top: none;
      border-left: none;
      display: flex;
      align-items: center;
      justify-content: flex-end;

      u .delete-btn {
        color: #f56c6c;
      }
    }

    .center-scrollbar {
      height: calc(100vh - 50px - 40px - 42px);
      overflow: hidden;
      border-left: 1px solid var(--el-border-color-extra-light);
      border-right: 1px solid var(--el-border-color-extra-light);
      box-sizing: border-box;

      .el-scrollbar__view {
        overflow-x: hidden;
      }

      .center-board-row {
        padding: 12px 12px 15px 12px;
        box-sizing: border-box;

        & > .el-form {
          // 69 = 12+15+42
          height: calc(100vh - 50px - 40px - 69px);
          flex: 1;

          .drawing-board {
            height: 100%;
            position: relative;

            .components-body {
              padding: 0;
              margin: 0;
              font-size: 0;
            }

            .sortable-ghost {
              position: relative;
              display: block;
              overflow: hidden;

              &::before {
                content: ' ';
                position: absolute;
                left: 0;
                right: 0;
                top: 0;
                height: 3px;
                background: rgb(89, 89, 223);
                z-index: 2;
              }
            }

            .components-item.sortable-ghost {
              width: 100%;
              height: 60px;
              background: var(--el-border-color-extra-light);
            }

            .active-from-item {
              & > .el-form-item {
                background: var(--el-border-color-extra-light);
                border-radius: 6px;
              }

              & > .drawing-item-copy,
              & > .drawing-item-delete {
                display: initial;
              }

              & > .component-name {
                color: $lighterBlue;
              }

              .el-input__wrapper {
                box-shadow: 0 0 0 1px var(--el-input-hover-border-color) inset;
              }
            }

            .el-form-item {
              margin-bottom: 15px;
            }
          }

          .drawing-item {
            position: relative;
            cursor: move;

            &.unfocus-bordered:not(.activeFromItem) > div:first-child {
              border: 1px dashed #ccc;
            }

            .el-form-item {
              padding: 12px 10px;
            }
          }

          .drawing-row-item {
            position: relative;
            cursor: move;
            box-sizing: border-box;
            border: 1px dashed #ccc;
            border-radius: 3px;
            padding: 0 2px;
            margin-bottom: 15px;

            .drawing-row-item {
              margin-bottom: 2px;
            }

            .el-col {
              margin-top: 22px;
            }

            .el-form-item {
              margin-bottom: 0;
            }

            .drag-wrapper {
              min-height: 80px;
              flex: 1;
              display: flex;
              flex-wrap: wrap;
            }

            &.active-from-item {
              border: 1px dashed $lighterBlue;
            }

            .component-name {
              position: absolute;
              top: 0;
              left: 0;
              font-size: 12px;
              color: #bbb;
              display: inline-block;
              padding: 0 6px;
            }
          }

          .drawing-item,
          .drawing-row-item {
            &:hover {
              & > .el-form-item {
                background: var(--el-border-color-extra-light);
                border-radius: 6px;
              }

              & > .drawing-item-copy,
              & > .drawing-item-delete {
                display: initial;
              }
            }

            & > .drawing-item-copy,
            & > .drawing-item-delete {
              display: none;
              position: absolute;
              top: -10px;
              width: 22px;
              height: 22px;
              line-height: 22px;
              text-align: center;
              border-radius: 50%;
              font-size: 12px;
              border: 1px solid;
              cursor: pointer;
              z-index: 1;
            }

            & > .drawing-item-copy {
              right: 56px;
              border-color: $lighterBlue;
              color: $lighterBlue;
              background: #fff;

              &:hover {
                background: $lighterBlue;
                color: #fff;
              }
            }

            & > .drawing-item-delete {
              right: 24px;
              border-color: #f56c6c;
              color: #f56c6c;
              background: #fff;

              &:hover {
                background: #f56c6c;
                color: #fff;
              }
            }
          }

          .empty-info {
            position: absolute;
            top: 46%;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 18px;
            color: #ccb1ea;
            letter-spacing: 4px;
          }
        }
      }
    }
  }
}
</style>

// xxl-boot-ui-react/src/views/tool/pagegen/index.tsx
/**
 * 页面：PageGen（表单/页面生成器）
 * 功能：拖拽式表单设计，支持组件添加、属性配置、React+antd 代码生成
 */
import { useEffect, useMemo, useRef, useState } from 'react'
import { Button, Drawer, Form, Input, InputNumber, Modal, Radio, Select, Tabs } from 'antd'
import { CopyOutlined, DownloadOutlined, DeleteOutlined, ClearOutlined, EyeOutlined } from '@ant-design/icons'
import ClipboardJS from 'clipboard'
import beautifier from 'js-beautify'
import SvgIcon from '@/components/SvgIcon'
import IconSelect, { type IconSelectHandle } from '@/components/IconSelect'
import {
  inputComponents,
  selectComponents,
  layoutComponents,
  formConf as formConfData,
  beautifierConf,
  type FormConf,
  type FormItemConf
} from '@/utils/generator/config'
import { drawingDefaultValue, initDrawingDefaultValue, cleanDrawingDefaultValue } from '@/utils/generator/drawingDefault'
import { makeUpHtml, vueTemplate, vueScript, cssStyle } from '@/utils/generator/html'
import { makeUpJs } from '@/utils/generator/js'
import { makeUpCss } from '@/utils/generator/css'
import RenderForm from '@/utils/generator/render'
import Download from '@/utils/download'
import modal from '@/utils/modal'
import './pagegen.scss'

/** 画布状态 */
interface CanvasState {
  drawingList: FormItemConf[]
  activeData: FormItemConf
  activeId: number | string
}

export default function PageGen() {
  // 初始化画布默认配置
  useEffect(() => {
    initDrawingDefaultValue()
  }, [])

  // 画布状态
  const [canvas, setCanvas] = useState<CanvasState>({
    drawingList: drawingDefaultValue,
    activeData: drawingDefaultValue[0],
    activeId: drawingDefaultValue[0].formId!
  })

  // 生成代码弹窗状态
  const [genDialog, setGenDialog] = useState({
    dialogVisible: false,
    showFileName: false,
    operationType: '' as 'copy' | 'download',
    generateConf: null as any,
    formData: {} as FormConf & { fields: FormItemConf[] }
  })

  // 全局组件 ID 自增
  const idGlobalRef = useRef(100)
  // 表单全局配置
  const [formConf, setFormConf] = useState<FormConf>(formConfData)
  // 预览弹窗
  const [previewVisible, setPreviewVisible] = useState(false)
  // 生成类型
  const [genType, setGenType] = useState('file')
  // 文件名
  const [fileName, setFileName] = useState('form')

  /**
   * 激活选中组件
   */
  function activeFormItem(element: FormItemConf) {
    setCanvas((prev) => ({ ...prev, activeData: element, activeId: element.formId! }))
  }

  /**
   * 复制代码：打开弹框
   */
  function copy() {
    setGenDialog((prev) => ({ ...prev, dialogVisible: true, showFileName: false, operationType: 'copy' }))
  }

  /**
   * 下载文件：打开弹框
   */
  function download() {
    setGenDialog((prev) => ({ ...prev, dialogVisible: true, showFileName: true, operationType: 'download' }))
  }

  /**
   * 清空画布
   */
  function empty() {
    modal.confirm('确定要清空所有组件吗？').then(() => {
      idGlobalRef.current = 100
      cleanDrawingDefaultValue()
      setCanvas((prev) => ({ ...prev, drawingList: [] }))
    })
  }

  /**
   * 克隆组件：生成新 ID、设置 vModel
   */
  function cloneComponent(origin: FormItemConf): FormItemConf {
    const clone: FormItemConf = JSON.parse(JSON.stringify(origin))
    clone.formId = ++idGlobalRef.current
    clone.span = formConf.span
    clone.renderKey = +new Date()
    if (!clone.layout) clone.layout = 'colFormItem'
    if (clone.layout === 'colFormItem') {
      clone.vModel = `field${idGlobalRef.current}`
    } else if (clone.layout === 'rowFormItem') {
      delete clone.label
      clone.componentName = `row${idGlobalRef.current}`
      clone.gutter = formConf.gutter
    }
    return clone
  }

  /**
   * 点击添加组件到画布
   */
  function addComponent(item: FormItemConf) {
    const clone = cloneComponent(item)
    const drawingList = [...canvas.drawingList, clone]
    setCanvas((prev) => ({ ...prev, drawingList }))
    activeFormItem(clone)
  }

  /**
   * 画布拖拽排序：拖拽结束
   */
  const handleCanvasDragOver = (e: React.DragEvent) => {
    e.preventDefault()
  }

  /**
   * 组件库拖拽开始：记录拖拽的组件
   */
  const handlePaletteDragStart = (e: React.DragEvent, item: FormItemConf) => {
    e.dataTransfer.setData('text/plain', '')
    e.dataTransfer.effectAllowed = 'copy'
    dragItemRef.current = item
  }

  /**
   * 画布放置：克隆组件入库
   */
  const handleCanvasDrop = (e: React.DragEvent) => {
    e.preventDefault()
    if (dragItemRef.current) {
      const clone = cloneComponent(dragItemRef.current)
      const drawingList = [...canvas.drawingList, clone]
      setCanvas((prev) => ({ ...prev, drawingList }))
      activeFormItem(clone)
      dragItemRef.current = null
    }
  }

  const dragItemRef = useRef<FormItemConf | null>(null)

  /**
   * 删除画布中的组件
   */
  function drawingItemDelete(index: number) {
    const drawingList = canvas.drawingList.filter((_, i) => i !== index)
    setCanvas((prev) => ({ ...prev, drawingList }))
    if (drawingList.length) {
      activeFormItem(drawingList[drawingList.length - 1])
    }
  }

  /**
   * 组装表单数据
   */
  function assembleFormData() {
    return { fields: JSON.parse(JSON.stringify(canvas.drawingList)), ...formConf }
  }

  /**
   * 生成代码
   */
  function generateCode(): string {
    const formData = assembleFormData()
    const script = vueScript(makeUpJs(formData, genType))
    const html = vueTemplate(makeUpHtml(formData, genType))
    const css = cssStyle(makeUpCss(formData))
    return beautifier.html(html + script + css, beautifierConf.html)
  }

  /**
   * 生成代码：弹窗确认后执行
   */
  function generate(data: any) {
    setGenDialog((prev) => ({ ...prev, generateConf: data }))
    if (genDialog.operationType === 'download') {
      const codeStr = generateCode()
      const blob = new Blob([codeStr], { type: 'text/plain;charset=utf-8' })
      Download.saveAs(blob, data.fileName || 'form.jsx')
    }
    // copy 类型由 clipboard 按钮触发
  }

  // 初始化剪切板复制
  useEffect(() => {
    const clipboard = new ClipboardJS('#copyNode', {
      text: () => {
        const codeStr = generateCode()
        modal.msgSuccess('代码已复制到剪切板，可粘贴。')
        return codeStr
      }
    })
    clipboard.on('error', () => {
      modal.msgError('代码复制失败')
    })
    return () => {
      clipboard.destroy()
    }
     
  }, [])

  // 组件分组
  const componentGroups = [
    { title: '输入型组件', list: inputComponents },
    { title: '选择型组件', list: selectComponents },
    { title: '布局型组件', list: layoutComponents }
  ]

  // 预览渲染数据
  const previewValue = useMemo(() => {
    const obj: Record<string, unknown> = {}
    canvas.drawingList.forEach((el) => {
      if (el.vModel) obj[el.vModel] = el.defaultValue
      el.children?.forEach((c) => {
        if (c.vModel) obj[c.vModel] = c.defaultValue
      })
    })
    return obj
  }, [canvas.drawingList])

  return (
    <div className="container">
      {/* 左侧面板 */}
      <div className="left-board">
        <div className="logo-wrapper">
          <div className="logo">表单生成器 / Form Generator</div>
        </div>
        <div className="left-scrollbar">
          <div className="components-list">
            {componentGroups.map((group) => (
              <div key={group.title}>
                <div className="components-title">
                  <SvgIcon iconClass="component" />
                  {group.title}
                </div>
                <div className="components-draggable">
                  {group.list.map((item, index) => (
                    <div
                      key={index}
                      className="components-item"
                      draggable
                      onDragStart={(e) => handlePaletteDragStart(e, item)}
                      onClick={() => addComponent(item)}
                    >
                      <div className="components-body">
                        <SvgIcon iconClass={item.tagIcon} />
                        {item.label}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 中间画布 */}
      <div className="center-board">
        <div className="action-bar">
          <Button icon={<CopyOutlined />} onClick={copy}>
            复制代码
          </Button>
          <Button icon={<DownloadOutlined />} onClick={download}>
            下载代码
          </Button>
          <Button icon={<EyeOutlined />} onClick={() => setPreviewVisible(true)}>
            预览
          </Button>
          <Button danger icon={<ClearOutlined />} onClick={empty}>
            清空
          </Button>
        </div>
        <div
          className="center-scrollbar"
          onDragOver={handleCanvasDragOver}
          onDrop={handleCanvasDrop}
        >
          <RenderForm
            conf={formConf}
            draw={canvas.drawingList}
            value={previewValue}
            activeId={canvas.activeId}
            onSelect={activeFormItem}
          />
        </div>
      </div>

      {/* 右侧属性面板 */}
      <RightPanel
        formConf={formConf}
        onFormConfChange={(v) => setFormConf((prev) => ({ ...prev, ...v }))}
        activeData={canvas.activeData}
        drawingList={canvas.drawingList}
        onDrawingListChange={(list) => setCanvas((prev) => ({ ...prev, drawingList: list }))}
        onDelete={drawingItemDelete}
      />

      {/* 生成类型弹窗 */}
      <Modal
        title="生成代码"
        open={genDialog.dialogVisible}
        onCancel={() => setGenDialog((prev) => ({ ...prev, dialogVisible: false }))}
        onOk={() => generate({ fileName: fileName || 'form' })}
        okText="确 定"
        cancelText="取 消"
      >
        <Form layout="vertical">
          <Form.Item label="生成类型">
            <Radio.Group value={genType} onChange={(e) => setGenType(e.target.value)}>
              <Radio value="file">文件</Radio>
              <Radio value="dialog">弹窗</Radio>
            </Radio.Group>
          </Form.Item>
          {genDialog.showFileName && (
            <Form.Item label="文件名">
              <Input value={fileName} onChange={(e) => setFileName(e.target.value)} placeholder="请输入文件名" />
            </Form.Item>
          )}
          {genDialog.operationType === 'copy' && (
            <Button type="primary" id="copyNode" style={{ width: '100%' }}>
              点击复制代码到剪切板
            </Button>
          )}
        </Form>
      </Modal>

      {/* 预览弹窗 */}
      <Modal title="表单预览" open={previewVisible} footer={null} width={720} onCancel={() => setPreviewVisible(false)}>
        <RenderForm conf={formConf} draw={canvas.drawingList} value={previewValue} />
      </Modal>
    </div>
  )
}

/**
 * 右侧属性面板
 */
interface RightPanelProps {
  formConf: FormConf
  onFormConfChange: (v: Partial<FormConf>) => void
  activeData: FormItemConf
  drawingList: FormItemConf[]
  onDrawingListChange: (list: FormItemConf[]) => void
  onDelete: (index: number) => void
}

function RightPanel({ formConf, onFormConfChange, activeData, drawingList, onDrawingListChange, onDelete }: RightPanelProps) {
  const iconSelectRef = useRef<IconSelectHandle>(null)
  // 编辑模式：组件属性 / 表单属性
  const [mode, setMode] = useState<'field' | 'form'>('field')

  /**
   * 更新当前选中组件属性
   */
  function updateField(partial: Partial<FormItemConf>) {
    const updateIn = (list: FormItemConf[]): FormItemConf[] =>
      list.map((item) => {
        if (item.formId === activeData.formId) {
          return { ...item, ...partial }
        }
        if (item.children && item.children.length) {
          return { ...item, children: updateIn(item.children) }
        }
        return item
      })
    onDrawingListChange(updateIn(drawingList))
  }

  /**
   * 更新选项列表
   */
  function updateOptions(options: any[]) {
    updateField({ options })
  }

  const activeIndex = drawingList.findIndex((item) => item.formId === activeData.formId)

  return (
    <div className="right-board">
      <div className="field-config">
        <Tabs
          activeKey={mode}
          onChange={(key) => setMode(key as 'field' | 'form')}
          items={[
            { key: 'field', label: '组件属性' },
            { key: 'form', label: '表单属性' }
          ]}
        />
        {mode === 'field' && activeData && activeData.tag ? (
          <div className="content">
            <Form layout="vertical" size="small">
              <Form.Item label="字段名">
                <Input value={activeData.vModel} onChange={(e) => updateField({ vModel: e.target.value })} />
              </Form.Item>
              <Form.Item label="标题">
                <Input value={activeData.label} onChange={(e) => updateField({ label: e.target.value })} />
              </Form.Item>
              {activeData.placeholder !== undefined && (
                <Form.Item label="占位提示">
                  <Input value={activeData.placeholder} onChange={(e) => updateField({ placeholder: e.target.value })} />
                </Form.Item>
              )}
              <Form.Item label="栅格">
                <InputNumber
                  min={1}
                  max={24}
                  value={activeData.span}
                  onChange={(v) => updateField({ span: v || 24 })}
                  style={{ width: '100%' }}
                />
              </Form.Item>
              {activeData.min !== undefined && (
                <Form.Item label="最小值">
                  <InputNumber value={activeData.min} onChange={(v) => updateField({ min: v })} style={{ width: '100%' }} />
                </Form.Item>
              )}
              {activeData.max !== undefined && (
                <Form.Item label="最大值">
                  <InputNumber value={activeData.max} onChange={(v) => updateField({ max: v })} style={{ width: '100%' }} />
                </Form.Item>
              )}
              <Form.Item label="默认值">
                <Input value={activeData.defaultValue} onChange={(e) => updateField({ defaultValue: e.target.value })} />
              </Form.Item>
              <Form.Item label="是否必填">
                <Radio.Group value={activeData.required} onChange={(e) => updateField({ required: e.target.value })}>
                  <Radio value={true}>是</Radio>
                  <Radio value={false}>否</Radio>
                </Radio.Group>
              </Form.Item>
              <Form.Item label="是否禁用">
                <Radio.Group value={activeData.disabled} onChange={(e) => updateField({ disabled: e.target.value })}>
                  <Radio value={true}>是</Radio>
                  <Radio value={false}>否</Radio>
                </Radio.Group>
              </Form.Item>
              {activeData.clearable !== undefined && (
                <Form.Item label="可清空">
                  <Radio.Group value={activeData.clearable} onChange={(e) => updateField({ clearable: e.target.value })}>
                    <Radio value={true}>是</Radio>
                    <Radio value={false}>否</Radio>
                  </Radio.Group>
                </Form.Item>
              )}
              {activeData.icon !== undefined && (
                <Form.Item label="图标">
                  <IconSelect ref={iconSelectRef} activeIcon={activeData.icon} onSelected={(name) => updateField({ icon: name })} />
                </Form.Item>
              )}
              {Array.isArray(activeData.options) && (
                <Form.Item label="选项配置">
                  <div className="options-editor">
                    {activeData.options.map((opt: any, i: number) => (
                      <div key={i} style={{ display: 'flex', gap: 6, marginBottom: 6 }}>
                        <Input
                          placeholder="显示值"
                          value={opt.label}
                          onChange={(e) => {
                            const options = [...(activeData.options as any[])]
                            options[i] = { ...options[i], label: e.target.value }
                            updateOptions(options)
                          }}
                        />
                        <Input
                          placeholder="绑定值"
                          value={opt.value}
                          onChange={(e) => {
                            const options = [...(activeData.options as any[])]
                            options[i] = { ...options[i], value: e.target.value }
                            updateOptions(options)
                          }}
                        />
                        <Button
                          danger
                          icon={<DeleteOutlined />}
                          onClick={() => {
                            const options = [...(activeData.options as any[])]
                            options.splice(i, 1)
                            updateOptions(options)
                          }}
                        />
                      </div>
                    ))}
                    <Button
                      block
                      onClick={() => {
                        const options = [...(activeData.options as any[]), { label: '选项', value: new Date().getTime() }]
                        updateOptions(options)
                      }}
                    >
                      添加选项
                    </Button>
                  </div>
                </Form.Item>
              )}
            </Form>
            {activeIndex > -1 && (
              <Button danger block icon={<DeleteOutlined />} onClick={() => onDelete(activeIndex)} style={{ marginTop: 12 }}>
                删除该组件
              </Button>
            )}
          </div>
        ) : (
          <div className="content" style={{ color: '#999' }}>
            请在画布中选中组件
          </div>
        )}

        {mode === 'form' && (
          <div className="content">
            <Form layout="vertical" size="small">
              <Form.Item label="表单栅格间隔">
                <InputNumber
                  value={formConf.gutter}
                  onChange={(v) => onFormConfChange({ gutter: v || 15 })}
                  style={{ width: '100%' }}
                />
              </Form.Item>
              <Form.Item label="标签宽度">
                <InputNumber
                  value={formConf.labelWidth}
                  onChange={(v) => onFormConfChange({ labelWidth: v || 100 })}
                  style={{ width: '100%' }}
                />
              </Form.Item>
              <Form.Item label="标签位置">
                <Radio.Group
                  value={formConf.labelPosition}
                  onChange={(e) => onFormConfChange({ labelPosition: e.target.value })}
                >
                  <Radio value="right">右对齐</Radio>
                  <Radio value="left">左对齐</Radio>
                </Radio.Group>
              </Form.Item>
              <Form.Item label="显示表单按钮">
                <Radio.Group value={formConf.formBtns} onChange={(e) => onFormConfChange({ formBtns: e.target.value })}>
                  <Radio value={true}>是</Radio>
                  <Radio value={false}>否</Radio>
                </Radio.Group>
              </Form.Item>
            </Form>
          </div>
        )}
      </div>
    </div>
  )
}
