// xxl-boot-ui2/src/components/HeaderSearch/index.vue
<template>
  <div class="header-search">
    <svg-icon class-name="search-icon" icon-class="search" @click.stop="click" />
    <el-dialog
      v-model="show"
      width="600"
      @close="close"
      @opened="onDialogOpened"
      :show-close="false"
      append-to-body
    >
      <el-input
        v-model="search"
        ref="headerSearchSelectRef"
        size="large"
        @input="querySearch"
        :prefix-icon="Search"
        placeholder="菜单搜索，支持标题、URL模糊查询"
        clearable
        @keyup.enter="selectActiveResult"
        @keydown.up.prevent="navigateResult('up')"
        @keydown.down.prevent="navigateResult('down')"
      >
      </el-input>

      <div class="result-count" v-if="search && options.length > 0">
        找到 <strong>{{ options.length }}</strong> 个结果
      </div>

      <div class="result-wrap">
        <el-scrollbar>

          <template v-if="options.length > 0">
            <div
              class="search-item"
              tabindex="1"
              v-for="(item, index) in options"
              :key="item.path"
              :class="{ 'is-active': index === activeIndex }"
              :style="activeStyle(index)"
              @mouseenter="activeIndex = index"
              @mouseleave="activeIndex = -1"
            >
              <div class="left">
                <svg-icon class="menu-icon" :icon-class="item.icon" />
              </div>
              <div class="search-info" @click="change(item)">
                <div class="menu-title" v-html="highlightText(item.title.join(' / '))"></div>
                <div class="menu-path" v-html="highlightText(item.path)"></div>
              </div>
              <svg-icon icon-class="enter" v-show="index === activeIndex" />
            </div>
          </template>

          <div class="empty-state" v-else-if="search && options.length === 0">
            <el-icon class="empty-icon"><Search /></el-icon>
            <p class="empty-text">未找到 "<strong>{{ search }}</strong>" 相关菜单</p>
            <p class="empty-tip">试试其他关键词或路径</p>
          </div>

        </el-scrollbar>
      </div>

      <div class="search-footer">
        <span class="shortcut-item">
          <kbd>↑</kbd><kbd>↓</kbd> 切换
        </span>
        <span class="shortcut-item">
          <kbd>↵</kbd> 选择
        </span>
        <span class="shortcut-item">
          <kbd>Esc</kbd> 关闭
        </span>
      </div>
    </el-dialog>
  </div>
</template>

<script setup>
import { Search } from '@element-plus/icons-vue'
import Fuse from 'fuse.js'
import { getNormalPath } from '@/utils/common'
import { isHttp } from '@/utils/validate'
import { useSettingsStore, useRoutesStore } from '@/store'

const search = ref('')
const options = ref([])
const searchPool = ref([])
const activeIndex = ref(-1)
const show = ref(false)
const fuse = ref(undefined)
const headerSearchSelectRef = ref(null)
const router = useRouter()
const theme = computed(() => useSettingsStore().theme)
const routes = computed(() => useRoutesStore().fullRoutes)

function click() {
  show.value = !show.value
  if (show.value) {
    options.value = searchPool.value
  }
}

function onDialogOpened() {
  nextTick(() => {
    headerSearchSelectRef.value && headerSearchSelectRef.value.focus()
  })
}

function close() {
  headerSearchSelectRef.value && headerSearchSelectRef.value.blur()
  search.value = ''
  options.value = searchPool.value
  show.value = false
  activeIndex.value = -1
}

function change(val) {
  const p = val.path
  const query = val.query
  if (isHttp(p)) {
    // http(s):// 路径新窗口打开
    const pindex = p.indexOf("http")
    window.open(p.substr(pindex, p.length), "_blank")
  } else {
    if (query) {
      router.push({ path: p, query: JSON.parse(query) })
    } else {
      router.push(p)
    }
  }
  search.value = ''
  options.value = searchPool.value
  nextTick(() => {
    show.value = false
  })
}

function initFuse(list) {
  fuse.value = new Fuse(list, {
    shouldSort: true,
    threshold: 0.2,
    distance: 100,
    minMatchCharLength: 1,
    keys: [{
      name: 'title',
      weight: 0.7
    }, {
      name: 'path',
      weight: 0.3
    }]
  })
}

function generateRoutes(routes, basePath = '', prefixTitle = []) {
  let res = []
  for (const r of routes) {
    if (r.hidden) { continue }
    const p = r.path.length > 0 && r.path[0] === '/' ? r.path : '/' + r.path
    const data = {
      path: !isHttp(r.path) ? getNormalPath(p) : r.path,
      title: [...prefixTitle],
      icon: ''
    }
    if (r.meta && r.meta.title) {
      data.title = [...data.title, r.meta.title]
      data.icon = r.meta.icon
      if (!r.children || r.children.length === 0) {
        res.push(data)
      }
    }
    if (r.query) {
      data.query = r.query
    }
    if (r.children) {
      const tempRoutes = generateRoutes(r.children, data.path, data.title)
      if (tempRoutes.length >= 1) {
        res = [...res, ...tempRoutes]
      }
    }
  }
  return res
}

function querySearch(query) {
  activeIndex.value = -1
  if (query !== '') {
    const q = query.toLowerCase()
    const pathMatches = searchPool.value.filter(item =>
      item.path.toLowerCase().includes(q)
    )
    const fuseMatches = fuse.value.search(query).map(item => item.item)
    const merged = [...pathMatches]
    fuseMatches.forEach(item => {
      if (!merged.find(m => m.path === item.path)) {
        merged.push(item)
      }
    })
    options.value = merged
  } else {
    options.value = searchPool.value
  }
}

function activeStyle(index) {
  if (index !== activeIndex.value) return {}
  return {
    "background-color": theme.value,
    "color": "#fff"
  }
}

function navigateResult(direction) {
  if (direction === "up") {
    activeIndex.value = activeIndex.value <= 0 ? options.value.length - 1 : activeIndex.value - 1
  } else if (direction === "down") {
    activeIndex.value = activeIndex.value >= options.value.length - 1 ? 0 : activeIndex.value + 1
  }
}

function selectActiveResult() {
  if (options.value.length > 0 && activeIndex.value >= 0) {
    change(options.value[activeIndex.value])
  }
}

function highlightText(text) {
  if (!text) return ''
  if (!search.value) return text
  const keyword = escapeRegExp(search.value)
  const reg = new RegExp(`(${keyword})`, 'gi')
  return text.replace(reg, '<span class="highlight">$1</span>')
}

function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

onMounted(() => {
  searchPool.value = generateRoutes(routes.value)
})

watch(searchPool, (list) => {
  initFuse(list)
})
</script>

<style lang='scss' scoped>
:deep(.el-dialog__header) {
  padding: 6px !important;
}

:deep(.highlight) {
  color: red;
  font-weight: 600;
}

:deep(.is-active .highlight) {
  color: rgba(255, 255, 255, 0.9);
  font-weight: 600;
}

.header-search {
  .search-icon {
    cursor: pointer;
    font-size: 18px;
    vertical-align: middle;
  }
}

.result-count {
  padding: 6px 16px 0;
  font-size: 12px;
  color: #aaa;

  strong {
    color: red;
    font-weight: 600;
  }
}

.result-wrap {
  height: 280px;
  margin: 4px 0;

  .search-item {
    display: flex;
    height: 48px;
    align-items: center;
    padding-right: 10px;
    border-radius: 4px;
    transition: background 0.15s;

    .left {
      width: 60px;
      text-align: center;
      flex-shrink: 0;

      .menu-icon {
        width: 18px;
        height: 18px;
      }
    }

    .search-info {
      padding-left: 5px;
      margin-top: 10px;
      width: 100%;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      flex: 1;
      overflow: hidden;

      .menu-title,
      .menu-path {
        height: 20px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      .menu-path {
        color: #ccc;
        font-size: 10px;
      }
    }
  }

  .search-item:hover {
    cursor: pointer;
  }

  .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;

    .empty-icon {
      font-size: 42px;
      color: #e0e0e0;
      margin-bottom: 14px;
    }

    .empty-text {
      font-size: 14px;
      color: #999;
      margin: 0 0 6px;

      strong {
        color: #666;
      }
    }

    .empty-tip {
      font-size: 12px;
      color: #bbb;
      margin: 0;
    }
  }
}

.search-footer {
  display: flex;
  align-items: center;
  gap: 28px;
  padding: 10px 20px;
  border-top: 1px solid #f0f0f0;
  color: #999;
  font-size: 12px;

  .shortcut-item {
    display: flex;
    align-items: center;
    gap: 5px;
  }

  kbd {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 20px;
    height: 20px;
    padding: 0 5px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: #f7f7f7;
    color: #555;
    font-size: 11px;
    font-family: inherit;
    line-height: 1;
    box-shadow: 0 1px 0 #ccc;
  }
}
</style>

// xxl-boot-ui-react/src/layout/components/Navbar/HeaderSearch.tsx
/**
 * 组件：HeaderSearch（菜单搜索）
 * 功能：顶部导航栏搜索图标，点击弹出搜索弹窗，支持按菜单标题/路径模糊搜索并跳转
 */
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Input, Modal } from 'antd'
import type { InputRef } from 'antd'
import { SearchOutlined } from '@ant-design/icons'
import Fuse from 'fuse.js'
import SvgIcon from '@/components/SvgIcon'
import { getNormalPath } from '@/utils/common'
import { isHttp } from '@/utils/validate'
import { useRoutesStore } from '@/stores'
import type { RouteData } from '@/stores/routes'
import './navbar.scss'

/** 搜索项：可搜索菜单节点 */
interface SearchItem {
  path: string
  title: string[]
  icon: string
  query?: string
}

/**
 * 菜单搜索
 */
export default function HeaderSearch() {
  const navigate = useNavigate()
  const routesStore = useRoutesStore()
  const [search, setSearch] = useState('')
  const [options, setOptions] = useState<SearchItem[]>([])
  const [searchPool, setSearchPool] = useState<SearchItem[]>([])
  const [activeIndex, setActiveIndex] = useState(-1)
  const [show, setShow] = useState(false)
  const fuseRef = useRef<Fuse<SearchItem> | undefined>(undefined)
  const inputRef = useRef<InputRef>(null)

  // 生成搜索池 + 初始化 Fuse
  useEffect(() => {
    const pool = generateRoutes(routesStore.fullRoutes)
    setSearchPool(pool)
    fuseRef.current = new Fuse(pool, {
      shouldSort: true,
      threshold: 0.2,
      distance: 100,
      minMatchCharLength: 1,
      keys: [
        { name: 'title', weight: 0.7 },
        { name: 'path', weight: 0.3 }
      ]
    })
     
  }, [routesStore.fullRoutes])

  /*
   * 切换搜索弹窗显隐
   */
  const click = () => {
    const nextShow = !show
    setShow(nextShow)
    if (nextShow) {
      setOptions(searchPool)
      setTimeout(() => inputRef.current?.focus(), 50)
    }
  }

  /*
   * 关闭弹窗：重置搜索状态
   */
  const close = () => {
    setSearch('')
    setOptions(searchPool)
    setShow(false)
    setActiveIndex(-1)
  }

  /*
   * 选中搜索结果：外部链接新窗口打开，内部路由跳转
   */
  const change = (val: SearchItem) => {
    const p = val.path
    if (isHttp(p)) {
      // 外部链接分支：新窗口打开
      window.open(p, '_blank')
    } else {
      // 内部路由分支：跳转
      navigate(p)
    }
    setSearch('')
    setOptions(searchPool)
    setShow(false)
  }

  /*
   * 输入关键词实时搜索：路径匹配 + Fuse 模糊匹配，合并去重
   */
  const querySearch = (query: string) => {
    setActiveIndex(-1)
    if (query !== '') {
      const q = query.toLowerCase()
      // 路径前缀匹配
      const pathMatches = searchPool.filter((item) => item.path.toLowerCase().includes(q))
      // Fuse 模糊匹配
      const fuseMatches = fuseRef.current ? fuseRef.current.search(query).map((item) => item.item) : []
      // 合并去重
      const merged = [...pathMatches]
      fuseMatches.forEach((item) => {
        if (!merged.find((m) => m.path === item.path)) {
          merged.push(item)
        }
      })
      setOptions(merged)
    } else {
      setOptions(searchPool)
    }
  }

  /*
   * 键盘上下键切换选中项
   */
  const navigateResult = (direction: 'up' | 'down') => {
    if (direction === 'up') {
      setActiveIndex((prev) => (prev <= 0 ? options.length - 1 : prev - 1))
    } else if (direction === 'down') {
      setActiveIndex((prev) => (prev >= options.length - 1 ? 0 : prev + 1))
    }
  }

  /*
   * 回车确认选中项
   */
  const selectActiveResult = () => {
    if (options.length > 0 && activeIndex >= 0) {
      change(options[activeIndex])
    }
  }

  return (
    <div className="header-search">
      {/* 图标：搜索触发 */}
      <SvgIcon iconClass="search" className="search-icon" onClick={click} />
      {/* 搜索弹窗 */}
      <Modal open={show} width={600} closable={false} footer={null} onCancel={close} wrapClassName="header-search-modal">
        <Input
          ref={inputRef}
          size="large"
          prefix={<SearchOutlined />}
          placeholder="菜单搜索，支持标题、URL模糊查询"
          allowClear
          value={search}
          onChange={(e) => {
            setSearch(e.target.value)
            querySearch(e.target.value)
          }}
          onPressEnter={selectActiveResult}
          onKeyDown={(e) => {
            if (e.key === 'ArrowUp') {
              e.preventDefault()
              navigateResult('up')
            } else if (e.key === 'ArrowDown') {
              e.preventDefault()
              navigateResult('down')
            }
          }}
        />

        {/* 搜索结果：计数 */}
        {search && options.length > 0 && (
          <div className="result-count">
            找到 <strong>{options.length}</strong> 个结果
          </div>
        )}

        {/* 搜索结果：结果列表 / 空状态 */}
        <div className="result-wrap">
          {options.length > 0 ? (
            options.map((item, index) => (
              <div
                key={item.path}
                className={`search-item ${index === activeIndex ? 'is-active' : ''}`}
                onMouseEnter={() => setActiveIndex(index)}
                onMouseLeave={() => setActiveIndex(-1)}
                onClick={() => change(item)}
              >
                <div className="left">
                  <SvgIcon iconClass={item.icon} className="menu-icon" />
                </div>
                <div className="search-info">
                  <div className="menu-title" dangerouslySetInnerHTML={{ __html: highlightText(item.title.join(' / '), search) }} />
                  <div className="menu-path" dangerouslySetInnerHTML={{ __html: highlightText(item.path, search) }} />
                </div>
                {index === activeIndex && <SvgIcon iconClass="enter" />}
              </div>
            ))
          ) : (
            search &&
            options.length === 0 && (
              <div className="empty-state">
                <SearchOutlined className="empty-icon" />
                <p className="empty-text">
                  未找到 "<strong>{search}</strong>" 相关菜单
                </p>
                <p className="empty-tip">试试其他关键词或路径</p>
              </div>
            )
          )}
        </div>

        {/* 快捷键说明 */}
        <div className="search-footer">
          <span className="shortcut-item">
            <kbd>↑</kbd>
            <kbd>↓</kbd> 切换
          </span>
          <span className="shortcut-item">
            <kbd>↵</kbd> 选择
          </span>
          <span className="shortcut-item">
            <kbd>Esc</kbd> 关闭
          </span>
        </div>
      </Modal>
    </div>
  )
}

/**
 * 递归遍历路由树，生成可搜索列表
 */
function generateRoutes(routes: RouteData[], basePath = '', prefixTitle: string[] = []): SearchItem[] {
  let res: SearchItem[] = []
  for (const r of routes) {
    // 跳过隐藏路由
    if (r.hidden) {
      continue
    }
    const p = r.path ? (r.path.length > 0 && r.path[0] === '/' ? r.path : '/' + r.path) : ''
    const data: SearchItem = {
      path: !isHttp(r.path as string) ? getNormalPath(p) : (r.path as string),
      title: [...prefixTitle],
      icon: ''
    }
    if (r.meta && r.meta.title) {
      data.title = [...data.title, r.meta.title]
      data.icon = (r.meta.icon as string) || ''
      // 叶节点：加入搜索结果
      if (!r.children || r.children.length === 0) {
        res.push(data)
      }
    }
    if (r.query) {
      data.query = r.query as string
    }
    if (r.children) {
      const tempRoutes = generateRoutes(r.children, data.path, data.title)
      if (tempRoutes.length >= 1) {
        res = [...res, ...tempRoutes]
      }
    }
  }
  return res
}

/**
 * 高亮搜索结果中的匹配关键词
 */
function highlightText(text: string, search: string): string {
  if (!text) return ''
  if (!search) return text
  const keyword = escapeRegExp(search)
  const reg = new RegExp(`(${keyword})`, 'gi')
  return text.replace(reg, '<span class="highlight">$1</span>')
}

/**
 * 转义正则特殊字符
 */
function escapeRegExp(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
