// xxl-boot-ui/src/components/DictTag/index.vue
<!--
  组件：DictTag（字典标签）
  功能：根据字典选项数组，将字典值渲染为 el-tag 或纯文本。
        支持 "单值、数组、逗号分隔" 字符串三种输入格式。

  用法：<DictTag :options="sys_normal_disable" :value="scope.row.status" />
-->
<template>
  <div>
    <!-- 遍历字典选项，匹配当前值则渲染标签 -->
    <template v-for="(item, index) in options">
      <template v-if="isValueMatch(item.value)">
        <!-- 默认样式(tagType=default 且无自定义class)时使用纯文本，免去多余 el-tag 结构 -->
        <span
          v-if="
            (item.elTagType === 'default' || item.elTagType === '') &&
            (item.elTagClass === '' || item.elTagClass === null)
          "
          :key="item.value"
          :index="index"
          :class="item.elTagClass"
          >{{ item.label + ' ' }}</span
        >
        <!-- 有自定义样式时用 el-tag 渲染 -->
        <el-tag
          v-else
          :disable-transitions="true"
          :key="item.value + ''"
          :index="index"
          :type="item.elTagType"
          :class="item.elTagClass"
          >{{ item.label + ' ' }}</el-tag
        >
      </template>
    </template>
    <!-- 存在未匹配项且 showValue 开启时，显示原始值 -->
    <template v-if="unmatch && showValue">
      {{ handleArray(unmatchArray) }}
    </template>
  </div>
</template>

<script setup lang="ts">
// 字典选项类型定义
interface DictOption {
  // 字典值
  value: string | number
  // 字典显示文案
  label: string
  // el-tag 类型
  elTagType: any
  // 自定义 class
  elTagClass: any
}

const props = withDefaults(
  defineProps<{
    // 字典选项列表：[{ value, label, elTagType, elTagClass }]
    options: DictOption[]
    // 当前值：支持 Number / String / Array 三种类型
    value?: number | string | Array<string | number> | null
    // 字符串分隔符：value 为逗号分隔字符串时使用
    separator?: string
    // 未匹配时是否显示原始 value
    showValue?: boolean
  }>(),
  {
    // 字典选项列表，默认空数组
    options: () => [],
    // 字符串分隔符
    separator: ',',
    // 未匹配时显示原始 value
    showValue: true
  }
)

// 将 props.value 统一转为字符串数组，方便后续匹配
const values = computed(() => {
  if (props.value === null || typeof props.value === 'undefined' || props.value === '') return []
  if (typeof props.value === 'number' || typeof props.value === 'boolean') return [props.value]
  return Array.isArray(props.value) ? props.value.map((item) => '' + item) : String(props.value).split(props.separator)
})

// 检测是否存在未匹配的字典项，存在时记录到 unmatchArray
const unmatchArray = computed<Array<string | number>>(() => {
  if (
    props.value === null ||
    typeof props.value === 'undefined' ||
    props.value === '' ||
    !Array.isArray(props.options) ||
    props.options.length === 0
  )
    return []
  // 遍历 value 中的每一项，收集在 options 中不存在的项（未匹配项）
  return values.value.filter((item) => !props.options.some((v) => v.value === item))
})

// 是否存在未匹配的字典项（由 unmatchArray 派生）
const unmatch = computed(() => unmatchArray.value.length > 0)

// 数组转空格分隔字符串，用于显示未匹配项
function handleArray(array: Array<string | number>) {
  if (array.length === 0) return ''
  return array.reduce((pre, cur) => {
    return pre + ' ' + cur
  })
}

// 判断某个字典值是否与当前 value 匹配
function isValueMatch(itemValue: string | number) {
  return values.value.some((val) => val === itemValue)
}
</script>

<style scoped>
.el-tag + .el-tag {
  margin-left: 10px;
}
</style>

// xxl-boot-ui-react/src/components/DictTag.tsx
/**
 * 组件：DictTag（字典标签）
 * 功能：根据字典选项数组，将字典值渲染为 Tag 或纯文本。
 *       支持 "单值、数组、逗号分隔" 字符串三种输入格式。
 *
 * 用法：<DictTag options={sys_normal_disable} value={row.status} />
 */
import { Tag } from 'antd'
import type { ReactNode } from 'react'

/** 字典选项类型 */
interface DictOption {
  /** 字典值 */
  value: string | number
  /** 字典显示文案 */
  label: string
  /** 标签类型 */
  elTagType?: any
  /** 自定义 class */
  elTagClass?: any
}

interface DictTagProps {
  /** 字典选项列表 */
  options?: DictOption[]
  /** 当前值：支持 Number / String / Array 三种类型 */
  value?: number | string | Array<string | number> | null
  /** 字符串分隔符：value 为逗号分隔字符串时使用 */
  separator?: string
  /** 未匹配时是否显示原始 value */
  showValue?: boolean
}

/**
 * 字典标签
 */
export default function DictTag({ options = [], value, separator = ',', showValue = true }: DictTagProps) {
  // 将 value 统一转为字符串数组，方便后续匹配
  const values = normalizeValues(value, separator)

  // 未匹配项
  const unmatchArray = computeUnmatch(values, value, options)
  const unmatch = unmatchArray.length > 0

  // 判断某个字典值是否与当前 value 匹配
  const isValueMatch = (itemValue: string | number) => values.some((val) => val === itemValue)

  // 数组转空格分隔字符串，用于显示未匹配项
  const handleArray = (array: Array<string | number>): string => {
    if (array.length === 0) return ''
    return array.reduce((pre: string, cur) => pre + ' ' + cur, '')
  }

  return (
    <div className="dict-tag">
      {/* 遍历字典选项，匹配当前值则渲染标签 */}
      {options.map((item, index) =>
        isValueMatch(item.value) ? (
          (item.elTagType === 'default' || item.elTagType === '' || item.elTagType === undefined) &&
          (item.elTagClass === '' || item.elTagClass === null || item.elTagClass === undefined) ? (
            <span key={String(item.value)} className={String(item.elTagClass || '')}>
              {item.label + ' '}
            </span>
          ) : (
            <Tag key={String(item.value)} color={item.elTagType} className={String(item.elTagClass || '')} style={{ marginRight: 10 }}>
              {item.label + ' '}
            </Tag>
          )
        ) : null
      )}
      {/* 存在未匹配项且 showValue 开启时，显示原始值 */}
      {unmatch && showValue ? handleArray(unmatchArray) : null}
    </div>
  )
}

/**
 * 将 value 统一转为字符串数组
 */
function normalizeValues(value: number | string | Array<string | number> | null | undefined, separator: string): Array<string | number> {
  if (value === null || typeof value === 'undefined' || value === '') return []
  if (typeof value === 'number' || typeof value === 'boolean') return [value]
  return Array.isArray(value) ? value.map((item) => '' + item) : String(value).split(separator)
}

/**
 * 收集未匹配的字典项
 */
function computeUnmatch(
  values: Array<string | number>,
  value: number | string | Array<string | number> | null | undefined,
  options: DictOption[]
): Array<string | number> {
  if (
    value === null ||
    typeof value === 'undefined' ||
    value === '' ||
    !Array.isArray(options) ||
    options.length === 0
  )
    return []
  return values.filter((item) => !options.some((v) => v.value === item))
}
