// xxl-boot-ui/xxl-boot-ui-vue/src/components/ExcelImportDialog/index.vue
<!--
  组件：ExcelImportDialog（Excel 导入弹窗）
  功能：Excel 文件导入对话框，支持文件拖拽上传、模板下载、覆盖更新选项。
  用法：<ExcelImportDialog ref="importRef" title="用户导入" action="/system/user/importData"
          @success="getList" />
-->
<template>
  <el-dialog :title="title" v-model="visible" :width="width" append-to-body @close="handleClose">
    <el-upload
      ref="uploadRef"
      :limit="1"
      accept=".xlsx, .xls"
      :headers="headers"
      :action="uploadUrl"
      :disabled="isUploading"
      :on-progress="handleProgress"
      :on-change="handleFileChange"
      :on-remove="handleFileRemove"
      :on-success="handleSuccess"
      :auto-upload="false"
      drag
    >
      <el-icon class="el-icon--upload">
        <UploadFilled />
      </el-icon>
      <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
      <template #tip>
        <div class="el-upload__tip text-center">
          <div class="el-upload__tip">
            <el-checkbox v-model="updateSupport"> {{ updateSupportLabel }}</el-checkbox>
          </div>
          <span>仅允许导入xls、xlsx格式文件。</span>
          <el-link
            v-if="templateUrl"
            type="primary"
            underline="never"
            style="font-size: 12px; vertical-align: baseline"
            @click="handleDownloadTemplate"
            >下载模板
          </el-link>
        </div>
      </template>
    </el-upload>
    <template #footer>
      <div class="dialog-footer">
        <el-button type="primary" @click="handleSubmit">确 定</el-button>
        <el-button @click="visible = false">取 消</el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { getAuthHeaders } from '@/utils/auth'
import { download } from '@/utils/request'
import modal from '@/utils/modal'
import { ElMessageBox } from 'element-plus'
import type { UploadFile, UploadFiles } from 'element-plus'
import { computed, nextTick, ref } from 'vue'

/**
 * defineProps：父传子
 */
const props = defineProps({
  // 对话框标题
  title: {
    type: String,
    default: '数据导入'
  },
  // 对话框宽度
  width: {
    type: String,
    default: '400px'
  },
  // 上传接口地址（必传）
  action: {
    type: String,
    required: true
  },
  // 模板下载接口地址，不传则不显示下载模板链接
  templateAction: {
    type: String,
    default: ''
  },
  // 模板文件名前缀
  templateFileName: {
    type: String,
    default: 'template'
  },
  // 覆盖更新勾选框的说明文字
  updateSupportLabel: {
    type: String,
    default: '是否更新已经存在的数据'
  }
})

/**
 * 暴露 open 方法供父组件调用
 *
 * defineExpose：父传子
 */
defineExpose({ open })

/**
 * defineEmits：子传父
 */
const emit = defineEmits(['success'])

const uploadRef = ref<any>(null) // el-upload 组件引用
const visible = ref(false) // 弹窗显示/隐藏
const selectedFile = ref<any>(null) // 当前选中的文件
const isUploading = ref(false) // 是否正在上传中
const updateSupport = ref(false) // 是否覆盖更新已有数据
const headers = getAuthHeaders() // 上传请求头（el-upload 不走 axios 拦截器，需手动注入）

// 上传地址（拼接 updateSupport 参数）
const uploadUrl = computed(() => {
  return import.meta.env.VITE_APP_BASE_API + props.action + '?updateSupport=' + (updateSupport.value ? 1 : 0)
})

// 是否有模板下载地址
const templateUrl = computed(() => !!props.templateAction)

// 打开对话框（供父组件通过 ref 调用）
function open() {
  updateSupport.value = false
  isUploading.value = false
  visible.value = true
  nextTick(() => {
    selectedFile.value = null
    uploadRef.value?.clearFiles()
  })
}

// 关闭时清理上传状态
function handleClose() {
  isUploading.value = false
  selectedFile.value = null
  uploadRef.value?.clearFiles()
}

// 下载导入模板文件
function handleDownloadTemplate() {
  download(props.templateAction, {}, `${props.templateFileName}_${new Date().getTime()}.xlsx`)
}

// 上传进度中：禁用提交按钮
function handleProgress() {
  isUploading.value = true
}

// 文件选择处理：记录选中文件
const handleFileChange = (file: UploadFile, fileList: UploadFiles) => {
  selectedFile.value = file
}

// 文件删除处理：清空选中文件
const handleFileRemove = (file: UploadFile, fileList: UploadFiles) => {
  selectedFile.value = null
}

// 上传成功：关闭弹窗，弹出导入结果消息
function handleSuccess(response: any) {
  visible.value = false
  isUploading.value = false
  selectedFile.value = null
  uploadRef.value?.clearFiles()
  ElMessageBox.alert(
    "<div style='overflow:auto;overflow-x:hidden;max-height:70vh;padding:10px 20px 0;'>" + response.msg + '</div>',
    '导入结果',
    { dangerouslyUseHTMLString: true }
  )
  emit('success')
}

// 提交上传：校验文件格式后执行上传
function handleSubmit() {
  const file = selectedFile.value
  if (!file || file.length === 0 || (!file.name.toLowerCase().endsWith('.xls') && !file.name.toLowerCase().endsWith('.xlsx'))) {
    modal.msgError('请选择后缀为 “xls”或“xlsx”的文件。')
    return
  }
  uploadRef.value.submit()
}
</script>

// xxl-boot-ui-react/src/components/ExcelImportDialog.tsx
/**
 * 组件：ExcelImportDialog（Excel 导入弹窗）
 * 功能：Excel 文件导入对话框，支持文件拖拽上传、模板下载、覆盖更新选项。
 * 用法：<ExcelImportDialog ref={importRef} title="用户导入" action="/system/user/importData" onSuccess={getList} />
 */
import { forwardRef, useImperativeHandle, useRef, useState } from 'react'
import { Button, Checkbox, Modal, Upload } from 'antd'
import { InboxOutlined, LinkOutlined } from '@ant-design/icons'
import { message } from 'antd'
import axios from 'axios'
import { getAuthHeaders } from '@/utils/auth'
import { download } from '@/utils/request'
import modal from '@/utils/modal'

export interface ExcelImportDialogHandle {
  /** 打开对话框 */
  open: () => void
}

interface ExcelImportDialogProps {
  /** 对话框标题 */
  title?: string
  /** 对话框宽度 */
  width?: number | string
  /** 上传接口地址（必传，相对路径） */
  action: string
  /** 模板下载接口地址，不传则不显示下载模板链接 */
  templateAction?: string
  /** 模板文件名前缀 */
  templateFileName?: string
  /** 覆盖更新勾选框的说明文字 */
  updateSupportLabel?: string
  /** 导入成功事件 */
  onSuccess?: () => void
}

/**
 * Excel 导入弹窗
 */
const ExcelImportDialog = forwardRef<ExcelImportDialogHandle, ExcelImportDialogProps>(function ExcelImportDialog(
  {
    title = '数据导入',
    width = 400,
    action,
    templateAction = '',
    templateFileName = 'template',
    updateSupportLabel = '是否更新已经存在的数据',
    onSuccess
  },
  ref
) {
  const [visible, setVisible] = useState(false)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [isUploading, setIsUploading] = useState(false)
  const [updateSupport, setUpdateSupport] = useState(false)
  const headers = getAuthHeaders()

  // 上传地址（拼接 updateSupport 参数）
  const uploadUrl = import.meta.env.VITE_APP_BASE_API + action + '?updateSupport=' + (updateSupport ? 1 : 0)

  /**
   * 打开对话框
   */
  const open = () => {
    setUpdateSupport(false)
    setIsUploading(false)
    setSelectedFile(null)
    setVisible(true)
  }

  useImperativeHandle(ref, () => ({ open }))

  /**
   * 关闭时清理上传状态
   */
  const handleClose = () => {
    setIsUploading(false)
    setSelectedFile(null)
  }

  /**
   * 下载导入模板文件
   */
  const handleDownloadTemplate = () => {
    download(templateAction, {}, `${templateFileName}_${new Date().getTime()}.xlsx`)
  }

  /**
   * 上传成功：关闭弹窗，弹出导入结果消息
   */
  const handleSuccess = (response: any) => {
    setVisible(false)
    setIsUploading(false)
    setSelectedFile(null)
    Modal.info({
      title: '导入结果',
      content: (
        <div style={{ overflow: 'auto', overflowX: 'hidden', maxHeight: '70vh', padding: '10px 20px 0' }} dangerouslySetInnerHTML={{ __html: response.msg }} />
      )
    })
    onSuccess && onSuccess()
  }

  /**
   * 提交上传：校验文件格式后执行上传
   */
  const handleSubmit = () => {
    const file = selectedFile
    if (!file || (!file.name.toLowerCase().endsWith('.xls') && !file.name.toLowerCase().endsWith('.xlsx'))) {
      modal.msgError('请选择后缀为 "xls"或"xlsx"的文件。')
      return
    }
    setIsUploading(true)
    const formData = new FormData()
    formData.append('file', file)
    axios
      .post(uploadUrl, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
          Authorization: headers.Authorization
        }
      })
      .then((res) => {
        handleSuccess(res.data)
      })
      .catch(() => {
        setIsUploading(false)
        modal.msgError('上传失败')
      })
  }

  return (
    <Modal title={title} open={visible} width={width} onCancel={() => setVisible(false)} onOk={handleSubmit} okText="确定" cancelText="取消" confirmLoading={isUploading} afterClose={handleClose}>
      <Upload.Dragger
        accept=".xlsx, .xls"
        maxCount={1}
        disabled={isUploading}
        beforeUpload={(file) => {
          setSelectedFile(file)
          return false
        }}
        onRemove={() => setSelectedFile(null)}
      >
        <p className="ant-upload-drag-icon">
          <InboxOutlined />
        </p>
        <p className="ant-upload-text">将文件拖到此处，或点击上传</p>
        <p className="ant-upload-hint">
          <div>
            <Checkbox checked={updateSupport} onChange={(e) => setUpdateSupport(e.target.checked)}>
              {updateSupportLabel}
            </Checkbox>
          </div>
          <span>仅允许导入xls、xlsx格式文件。</span>
          {templateAction && (
            <LinkOutlined onClick={handleDownloadTemplate} style={{ cursor: 'pointer', color: '#1677ff' }} />
          )}
        </p>
      </Upload.Dragger>
    </Modal>
  )
})

ExcelImportDialog.displayName = 'ExcelImportDialog'
export default ExcelImportDialog
