// xxl-boot-ui/src/components/iFrame/index.vue
<!--
  组件：IFrame（iframe 内嵌页面容器）
  功能：在系统页面内嵌加载外部 url，显示 loading 直至页面加载完成。
  用法：<IFrame src="https://example.com" />
-->
<template>
  <div v-loading="loading" :style="'height:' + height">
    <iframe 
      :src="url" 
      frameborder="no" 
      style="width: 100%; height: 100%" 
      scrolling="auto" />
  </div>
</template>

<script setup>
const props = defineProps({
  // 要嵌入的页面 URL（必传）
  src: {
    type: String,
    required: true
  }
})

// 动态高度：视口高度减去导航栏/标签栏占位
const height = ref(document.documentElement.clientHeight - 94.5 + "px;")
// 加载状态：初始 true，300ms 后自动关闭（给 iframe 加载缓冲时间）
const loading = ref(true)
const url = computed(() => props.src)

onMounted(() => {
  setTimeout(() => {
    loading.value = false
  }, 300)
  // 窗口大小变化时重新计算 iframe 高度
  window.onresize = function temp() {
    height.value = document.documentElement.clientHeight - 94.5 + "px;"
  }
})
</script>

// xxl-boot-ui-react/src/components/IFrame.tsx
/**
 * 组件：IFrame（iframe 内嵌页面容器）
 * 功能：在系统页面内嵌加载外部 url，显示 loading 直至页面加载完成。
 *
 * 用法：<IFrame src="https://example.com" />
 */
import { useEffect, useRef, useState } from 'react'
import { Spin } from 'antd'

interface IFrameProps {
  /** 要嵌入的页面 URL（必传） */
  src: string
}

/**
 * iframe 内嵌页面容器
 */
export default function IFrame({ src }: IFrameProps) {
  const [height, setHeight] = useState(`${document.documentElement.clientHeight - 94.5}px`)
  const [loading, setLoading] = useState(true)
  const iframeRef = useRef<HTMLIFrameElement>(null)

  useEffect(() => {
    // 加载状态：300ms 后自动关闭（给 iframe 加载缓冲时间）
    const timer = setTimeout(() => {
      setLoading(false)
    }, 300)

    // 窗口大小变化时重新计算 iframe 高度
    const handleResize = () => {
      setHeight(`${document.documentElement.clientHeight - 94.5}px`)
    }
    window.addEventListener('resize', handleResize)

    // iframe onload 提前关闭 loading
    const onLoad = () => setLoading(false)
    iframeRef.current?.addEventListener('load', onLoad)

    return () => {
      clearTimeout(timer)
      window.removeEventListener('resize', handleResize)
      iframeRef.current?.removeEventListener('load', onLoad)
    }
  }, [])

  return (
    <div style={{ height, position: 'relative' }}>
      <Spin spinning={loading} tip="加载中..." style={{ position: 'absolute', top: '50%', left: '50%' }}>
        <iframe ref={iframeRef} src={src} frameBorder="no" style={{ width: '100%', height: '100%' }} scrolling="auto" title="iframe" />
      </Spin>
    </div>
  )
}
