// xxl-boot-ui/src/views/system/dict/detail.vue
<!--
  组件：DictDataDrawer（字典项抽屉）
  功能：展示指定字典下的全部字典项
-->
<template>
  <el-drawer
    :model-value="visible"
    direction="rtl"
    size="700px"
    append-to-body
    @update:model-value="$emit('update:visible', $event)"
  >
    <!-- 自定义标题 -->
    <template #header>
      <div class="drawer-head">
        <el-icon style="color: #5b9bd5; margin-right: 8px"><List /></el-icon>
        <span class="drawer-head-name">{{ row.name }}</span>
        <span class="drawer-head-type">{{ row.type }}</span>
      </div>
    </template>

    <div class="drawer-wrap">
      <!-- 加载中 -->
      <div v-if="loading" class="drawer-loading">
        <el-icon class="is-loading"><Loading /></el-icon>
        <span>加载中...</span>
      </div>

      <!-- 空数据 -->
      <div v-else-if="!dataList.length" class="drawer-empty">
        <el-icon style="font-size: 36px"><Document /></el-icon>
        <div>暂无字典数据</div>
      </div>

      <template v-else>
        <!-- 统计卡片 -->
        <el-row :gutter="12" class="stat-row">
          <el-col :span="disabledCount > 0 ? 8 : 12">
            <div class="stat-card">
              <div class="stat-num">{{ dataList.length }}</div>
              <div class="stat-label">共计条目</div>
            </div>
          </el-col>
          <el-col :span="disabledCount > 0 ? 8 : 12">
            <div class="stat-card">
              <div class="stat-num success">{{ normalCount }}</div>
              <div class="stat-label">正常</div>
            </div>
          </el-col>
          <el-col v-if="disabledCount > 0" :span="8">
            <div class="stat-card">
              <div class="stat-num danger">{{ disabledCount }}</div>
              <div class="stat-label">停用</div>
            </div>
          </el-col>
        </el-row>

        <!-- 字典项列表 -->
        <div v-for="item in dataList" :key="item.id" class="dict-item">
          <div class="dict-cell">
            <div class="dict-cell-key">字典项名称</div>
            <div class="dict-cell-val">{{ item.name }}</div>
          </div>
          <div class="dict-cell">
            <div class="dict-cell-key">字典项Code</div>
            <div class="dict-cell-val">{{ item.code }}</div>
          </div>
          <div class="dict-cell">
            <div class="dict-cell-key">状态</div>
            <div class="dict-cell-val">
              <el-tag :type="item.status === 0 ? 'success' : 'danger'" size="small">
                {{ item.status === 0 ? '正常' : '停用' }}
              </el-tag>
            </div>
          </div>
        </div>
      </template>
    </div>
  </el-drawer>
</template>

<script setup lang="ts">
import { listData } from '@/api/system/dict/data'
import type { Dict, DictItem } from '@/types/api'

/** 抽屉入参 */
interface DrawerProps {
  visible: boolean
  row: Dict
}

const props = withDefaults(defineProps<DrawerProps>(), {
  visible: false,
  row: () => ({})
})

const emit = defineEmits(['update:visible'])

const loading = ref(false) /* 加载状态 */
const dataList = ref<DictItem[]>([]) /* 字典项列表 */

const normalCount = computed(() => dataList.value.filter((r) => r.status === 0).length)
const disabledCount = computed(() => dataList.value.filter((r) => r.status !== 0).length)

/* 弹窗打开时加载数据，关闭时清空 */
watch(
  () => props.visible,
  (val) => {
    if (val) {
      loadData()
    } else {
      dataList.value = []
    }
  }
)

/** 加载字典项列表 */
function loadData() {
  if (!props.row?.id) return
  loading.value = true
  dataList.value = []
  listData({ dictId: props.row.id, offset: 0, pagesize: 100 })
    .then((response) => {
      dataList.value = response.data.data || []
    })
    .catch(() => {})
    .finally(() => {
      loading.value = false
    })
}
</script>

<style scoped>
.drawer-head {
  display: flex;
  align-items: center;
}
.drawer-head-name {
  font-size: 16px;
  font-weight: 600;
  color: #2c3e50;
  margin-right: 8px;
}
.drawer-head-type {
  font-size: 14px;
  color: #95a5a6;
  font-family: monospace;
}
.drawer-wrap {
  padding: 0 20px 20px;
}
.drawer-loading {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 120px;
  color: #aaa;
  font-size: 13px;
  gap: 8px;
}
.drawer-empty {
  text-align: center;
  color: #bbb;
  padding: 60px 0;
  font-size: 13px;
}
.drawer-empty .el-icon {
  display: block;
  margin: 0 auto 8px;
}
.stat-row {
  margin-bottom: 16px;
}
.stat-card {
  background: #f7f9fb;
  border: 1px solid #e8ecf0;
  border-radius: 6px;
  padding: 10px 14px;
  text-align: center;
}
.stat-num {
  font-size: 22px;
  font-weight: 700;
  color: #2c3e50;
}
.stat-num.success {
  color: #27ae60;
}
.stat-num.danger {
  color: #e74c3c;
}
.stat-label {
  font-size: 11px;
  color: #95a5a6;
  margin-top: 4px;
}
.dict-item {
  display: grid;
  grid-template-columns: 1.1fr 1.1fr 0.8fr;
  border: 1px solid #e8ecf0;
  border-radius: 6px;
  overflow: hidden;
  margin-bottom: 8px;
}
.dict-cell {
  display: grid;
  grid-template-columns: auto 1fr;
  border-right: 1px solid #f0f4f8;
}
.dict-cell:last-child {
  border-right: 0;
}
.dict-cell-key {
  padding: 9px 14px;
  font-size: 12px;
  color: #888;
  background: #f7f9fb;
  border-right: 1px solid #f0f4f8;
  white-space: nowrap;
}
.dict-cell-val {
  padding: 9px 14px;
  font-size: 13px;
  color: #2c3e50;
  word-break: break-all;
  display: flex;
  align-items: center;
}
</style>

// xxl-boot-ui-react/src/views/system/dict/detail.tsx
/**
 * 组件：DictDataDrawer（字典项抽屉）
 * 功能：展示指定字典下的全部字典项
 * @author xuxueli 2026-08-09
 */
import { forwardRef, useImperativeHandle, useState } from 'react'
import { Drawer, Row, Col, Spin, Tag } from 'antd'
import { UnorderedListOutlined, LoadingOutlined, FileTextOutlined } from '@ant-design/icons'
import { listData } from '@/api/system/dict/data'
import type { Dict, DictItem } from '@/types/api'
import './detail.scss'

export interface DictDataDrawerHandle {
  /** 打开抽屉：加载指定字典下的字典项列表 */
  open: (row: Dict) => void
}

/**
 * 字典项抽屉
 */
const DictDataDrawer = forwardRef<DictDataDrawerHandle>(function DictDataDrawer(_, ref) {
  const [visible, setVisible] = useState(false)
  const [loading, setLoading] = useState(false)
  const [row, setRow] = useState<Dict>({})
  const [dataList, setDataList] = useState<DictItem[]>([])

  // 正常条数 / 停用条数
  const normalCount = dataList.filter((r) => r.status === 0).length
  const disabledCount = dataList.filter((r) => r.status !== 0).length

  /** 加载字典项列表 */
  function loadData(row: Dict) {
    if (!row?.id) return
    setLoading(true)
    setDataList([])
    listData({ dictId: row.id, offset: 0, pagesize: 100 })
      .then((response) => {
        setDataList(response.data.data || [])
      })
      .catch(() => {})
      .finally(() => {
        setLoading(false)
      })
  }

  /** 打开抽屉 */
  function open(row: Dict) {
    setRow(row)
    setVisible(true)
    loadData(row)
  }

  /** 关闭抽屉：清空字典项列表 */
  function handleClose() {
    setVisible(false)
    setDataList([])
  }

  useImperativeHandle(ref, () => ({ open }))

  return (
    <Drawer
      open={visible}
      placement="right"
      width={700}
      onClose={handleClose}
      title={
        <div className="drawer-head">
          <UnorderedListOutlined style={{ color: '#5b9bd5', marginRight: 8 }} />
          <span className="drawer-head-name">{row.name}</span>
          <span className="drawer-head-type">{row.type}</span>
        </div>
      }
    >
      <div className="drawer-wrap">
        {/* 加载中 */}
        {loading ? (
          <div className="drawer-loading">
            <LoadingOutlined spin />
            <span>加载中...</span>
          </div>
        ) : !dataList.length ? (
          /* 空数据 */
          <div className="drawer-empty">
            <FileTextOutlined style={{ fontSize: 36 }} />
            <div>暂无字典数据</div>
          </div>
        ) : (
          <>
            {/* 统计卡片 */}
            <Row gutter={12} className="stat-row">
              <Col span={disabledCount > 0 ? 8 : 12}>
                <div className="stat-card">
                  <div className="stat-num">{dataList.length}</div>
                  <div className="stat-label">共计条目</div>
                </div>
              </Col>
              <Col span={disabledCount > 0 ? 8 : 12}>
                <div className="stat-card">
                  <div className="stat-num success">{normalCount}</div>
                  <div className="stat-label">正常</div>
                </div>
              </Col>
              {disabledCount > 0 && (
                <Col span={8}>
                  <div className="stat-card">
                    <div className="stat-num danger">{disabledCount}</div>
                    <div className="stat-label">停用</div>
                  </div>
                </Col>
              )}
            </Row>

            {/* 字典项列表 */}
            {dataList.map((item) => (
              <div key={item.id} className="dict-item">
                <div className="dict-cell">
                  <div className="dict-cell-key">字典项名称</div>
                  <div className="dict-cell-val">{item.name}</div>
                </div>
                <div className="dict-cell">
                  <div className="dict-cell-key">字典项Code</div>
                  <div className="dict-cell-val">{item.code}</div>
                </div>
                <div className="dict-cell">
                  <div className="dict-cell-key">状态</div>
                  <div className="dict-cell-val">
                    <Tag color={item.status === 0 ? 'green' : 'red'}>{item.status === 0 ? '正常' : '停用'}</Tag>
                  </div>
                </div>
              </div>
            ))}
          </>
        )}
      </div>
    </Drawer>
  )
})

DictDataDrawer.displayName = 'DictDataDrawer'
export default DictDataDrawer
