// xxl-boot-ui-react/src/views/system/message/ReadUsers.tsx
/**
 * 组件：ReadUsers（已读用户弹窗）
 * 功能：分页展示某条消息的已读用户列表
 */
import { forwardRef, useImperativeHandle, useState } from 'react'
import { Modal, Table } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { listMessageReadUsers } from '@/api/system/message'
import { parseTime } from '@/utils/common'
import Pagination from '@/components/Pagination'
import type { Message, User } from '@/types/api'

export interface ReadUsersHandle {
  /** 打开弹窗：回显消息信息并加载已读用户列表 */
  open: (row: Message) => void
}

/** 查询参数 */
interface QueryState {
  pageNum: number
  pageSize: number
  messageId?: number
}

/**
 * 已读用户弹窗
 */
const ReadUsers = forwardRef<ReadUsersHandle>(function ReadUsers(_, ref) {
  const [visible, setVisible] = useState(false)
  const [title, setTitle] = useState('')
  const [list, setList] = useState<User[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [queryParams, setQueryParams] = useState<QueryState>({ pageNum: 1, pageSize: 10, messageId: undefined })

  /** 查询已读用户列表 */
  const getList = () => {
    setLoading(true)
    const { pageNum, pageSize, ...rest } = queryParams
    const params = {
      ...rest,
      offset: (pageNum - 1) * pageSize,
      pagesize: pageSize
    }
    listMessageReadUsers(params)
      .then((res) => {
        setList(res.data.data)
        setTotal(res.data.total)
      })
      .finally(() => {
        setLoading(false)
      })
  }

  /** 打开弹窗 */
  const open = (row: Message) => {
    setQueryParams({ pageNum: 1, pageSize: 10, messageId: row.id })
    setTitle(String(row.title || ''))
    setVisible(true)
    getList()
  }

  /** 关闭弹窗：清空列表与计数 */
  const handleClose = () => {
    setList([])
    setTotal(0)
  }

  useImperativeHandle(ref, () => ({ open }))

  const columns: ColumnsType<User> = [
    { title: '序号', key: 'index', width: 70, align: 'center', render: (_v, _r, index) => index + 1 },
    { title: '登录名称', dataIndex: 'userName', align: 'center', ellipsis: true },
    { title: '用户名称', dataIndex: 'realName', align: 'center', ellipsis: true },
    {
      title: '阅读时间',
      dataIndex: 'addTime',
      align: 'center',
      width: 180,
      render: (value: string) => <span>{parseTime(value)}</span>
    }
  ]

  return (
    <Modal
      title={`「${title}」已读用户`}
      open={visible}
      width={680}
      footer={null}
      onCancel={() => setVisible(false)}
      afterClose={handleClose}
      style={{ top: '6vh' }}
    >
      <Table
        rowKey={(record) => String(record.userId)}
        size="small"
        loading={loading}
        columns={columns}
        dataSource={list}
        pagination={false}
        scroll={{ y: 340 }}
      />
      <div style={{ display: total > 0 ? 'block' : 'none' }}>
        <Pagination
          total={total}
          page={queryParams.pageNum}
          limit={queryParams.pageSize}
          onPageChange={(v) => setQueryParams((prev) => ({ ...prev, pageNum: v }))}
          onLimitChange={(v) => setQueryParams((prev) => ({ ...prev, pageSize: v }))}
          onPagination={getList}
        />
      </div>
    </Modal>
  )
})

ReadUsers.displayName = 'ReadUsers'
export default ReadUsers

// xxl-boot-ui/src/views/system/message/ReadUsers.vue
<!--
  组件：ReadUsers（已读用户弹窗）
  功能：分页展示某条消息的已读用户列表
-->
<template>
  <!-- 弹框组件 -->
  <el-dialog v-model="dialog.visible" :title="`「${dialog.title}」已读用户`" width="680px" top="6vh" append-to-body @close="handleClose">
    <!-- 已读用户 table -->
    <el-table v-loading="table.loading" :data="table.list" size="small" stripe height="340px">
      <el-table-column type="index" label="序号" width="70" align="center" />
      <el-table-column label="登录名称" prop="userName" align="center" :show-overflow-tooltip="true" />
      <el-table-column label="用户名称" prop="realName" align="center" :show-overflow-tooltip="true" />
      <el-table-column label="阅读时间" prop="addTime" align="center" width="180">
        <template #default="scope">
          <span>{{ parseTime(scope.row.addTime) }}</span>
        </template>
      </el-table-column>
    </el-table>
    <!-- 分页 -->
    <Pagination
      v-show="table.total > 0"
      :total="table.total"
      v-model:page="queryParams.pageNum"
      v-model:limit="queryParams.pageSize"
      @pagination="getList"
      style="padding: 6px 0px"
    />
  </el-dialog>
</template>

<script setup name="ReadUsers" lang="ts">
import { listMessageReadUsers } from '@/api/system/message'
import { parseTime } from '@/utils/common'
import { usePageParams } from '@/composables/usePageParams'
import type { Message, User } from '@/types/api'

/** 弹窗状态 */
interface DialogState {
  visible: boolean
  title: string | undefined
}

/** 表格状态 */
interface TableState {
  list: User[]
  total: number
  loading: boolean
}

/** 查询参数 */
interface QueryState {
  pageNum: number
  pageSize: number
  messageId?: number
}

// 弹窗：UI数据
const dialog = ref<DialogState>({
  visible: false /* 弹窗显隐 */,
  title: '' /* 消息标题 */
})

// 表格：UI数据
const table = ref<TableState>({
  list: [] /* 已读用户列表 */,
  total: 0 /* 已读人数 */,
  loading: false /* 加载状态 */
})

// 查询参数
const queryParams = ref<QueryState>({
  pageNum: 1 /* 当前页码 */,
  pageSize: 10 /* 每页条数 */,
  messageId: undefined /* 消息ID */
})

/** 打开弹窗：回显消息信息并加载已读用户列表 */
function open(row: Message) {
  queryParams.value.messageId = row.id
  dialog.value.title = row.title
  queryParams.value.pageNum = 1
  dialog.value.visible = true
  getList()
}

/** 查询已读用户列表 */
function getList() {
  table.value.loading = true
  // 前端分页参数 → 后端分页参数（offset/pagesize）
  const { pageNum, pageSize, ...rest } = queryParams.value
  const params = {
    ...rest,
    offset: (pageNum - 1) * pageSize,
    pagesize: pageSize
  }
  listMessageReadUsers(params)
    .then((res) => {
      table.value.list = res.data.data
      table.value.total = res.data.total
    })
    .finally(() => {
      table.value.loading = false
    })
}

/** 关闭弹窗：清空列表与计数 */
function handleClose() {
  table.value.list = []
  table.value.total = 0
}

/**
 * “父传子”通信工具：
 */
defineExpose({
  // 打开弹框
  open
})
</script>
