// xxl-boot-ui-react/src/views/system/log/index.tsx
/**
 * 页面：Log（日志管理）
 * 功能：查询、删除日志，查看日志详情
 * @author xuxueli 2026-08-09
 */
import { useEffect, useRef, useState } from 'react'
import { Button, Form, Input, Select, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { DeleteOutlined, DownloadOutlined, EyeOutlined, SearchOutlined, ReloadOutlined } from '@ant-design/icons'
import LogDetail, { type LogDetailHandle } from './detail'
import Pagination from '@/components/Pagination'
import RightToolbar from '@/components/RightToolbar'
import Auth from '@/components/Auth'
import { pageList, delOperlog } from '@/api/system/log'
import { loadEnumItem } from '@/api/system/dict/data'
import { parseTime } from '@/utils/common'
import { buildPageParams } from '@/hooks/buildPageParams'
import modal from '@/utils/modal'
import { download } from '@/utils/request'
import type { Log } from '@/types/api'
import type { EnumOption } from '@/types'

// --------------------------------- ref data ---------------------------------

/** 搜索栏：查询参数 */
interface LogQueryState {
  pageNum: number
  pageSize: number
  type: number
  module: number
  title?: string
  [key: string]: unknown
}

/** 表格：UI数据 */
interface TableState {
  list: Log[]
  total: number
  loading: boolean
  showSearch: boolean
  ids: number[]
  multiple: boolean
}

/** 枚举数据状态（下拉选项 + 编码 → 名称映射） */
interface DictState {
  options: EnumOption[]
  map: Record<number | string, string | undefined>
}

export default function Log() {
  const logDetailRef = useRef<LogDetailHandle>(null)

  // 页面初始化：加载日志类型、系统模块枚举 + 日志列表
  useEffect(() => {
    getList()
    loadEnumItem('LogTypeEnum').then((res) => {
      setTypeDict({ options: res.data, map: buildMap(res.data) })
    })
    loadEnumItem('LogModuleEnum').then((res) => {
      setModuleDict({ options: res.data, map: buildMap(res.data) })
    })
     
  }, [])

  // 搜索栏：查询参数
  const [queryParams, setQueryParams] = useState<LogQueryState>({
    pageNum: 1,
    pageSize: 10,
    type: -1,
    module: 0,
    title: undefined
  })

  // 表格：UI数据
  const [table, setTable] = useState<TableState>({
    list: [],
    total: 0,
    loading: true,
    showSearch: true,
    ids: [],
    multiple: true
  })

  // 枚举数据（下拉选项 + 编码 → 名称映射）
  const [typeDict, setTypeDict] = useState<DictState>({ options: [], map: {} })
  const [moduleDict, setModuleDict] = useState<DictState>({ options: [], map: {} })

  // 表单实例
  const [searchForm] = Form.useForm()

  // --------------------------------- fun ---------------------------------

  /** 枚举选项 → 编码名称映射 */
  function buildMap(options: EnumOption[]): Record<number | string, string | undefined> {
    const map: Record<number | string, string | undefined> = {}
    options.forEach((item) => {
      map[item.code] = item.title
    })
    return map
  }

  /** 查询日志列表 */
  function getList() {
    setTable((prev) => ({ ...prev, loading: true }))
    const params = buildPageParams(queryParams)()
    pageList(params).then((response) => {
      setTable((prev) => ({
        ...prev,
        list: response.data.data,
        total: response.data.total,
        loading: false
      }))
    })
  }

  /** 日志类型编码 → 文案 */
  function typeText(type: number) {
    const item = typeDict.options.find((i) => i.code === type)
    return item ? item.title : type
  }

  /** 搜索按钮操作 */
  function handleQuery() {
    setQueryParams((prev) => ({ ...prev, pageNum: 1 }))
    getList()
  }

  /** 重置按钮操作 */
  function resetQuery() {
    searchForm.resetFields()
    setQueryParams((prev) => ({ ...prev, type: -1, module: 0, title: undefined, pageNum: 1 }))
    handleQuery()
  }

  /** 多选框选中数据 */
  function handleSelectionChange(selectedRowKeys: React.Key[]) {
    const ids = selectedRowKeys.map((k) => Number(k))
    setTable((prev) => ({
      ...prev,
      ids,
      multiple: !selectedRowKeys.length
    }))
  }

  /** 查看日志详情 */
  function handleDetail(row: Log) {
    logDetailRef.current?.open(row)
  }

  /** 导出按钮操作 */
  function handleExport() {
    download('system/log/export', { ...buildPageParams(queryParams)() }, `log_${new Date().getTime()}.xlsx`)
  }

  /** 删除按钮操作（顶部按钮点击传入的是事件对象而非行数据，此时取勾选 ids） */
  function handleDelete(row: any) {
    const logIds = row?.id ?? table.ids
    if (logIds == null || (Array.isArray(logIds) && logIds.length === 0)) {
      return
    }
    modal
      .confirm('是否确认删除日志编号为"' + logIds + '"的数据项?')
      .then(function () {
        return delOperlog(logIds)
      })
      .then(() => {
        getList()
        modal.msgSuccess('删除成功')
      })
      .catch(() => {})
  }

  // --------------------------------- 表格列 ---------------------------------

  const columns: ColumnsType<Log> = [
    { title: '日志编号', dataIndex: 'id', key: 'id', width: 80, align: 'center' },
    {
      title: '日志类型',
      key: 'type',
      width: 100,
      align: 'center',
      render: (_v, row) => (
        <Tag color={row.type === 0 ? 'blue' : 'orange'}>{typeText(Number(row.type))}</Tag>
      )
    },
    {
      title: '系统模块',
      key: 'module',
      align: 'center',
      ellipsis: true,
      render: (_v, row) => <span>{moduleDict.map[row.module as number] || row.module}</span>
    },
    { title: '日志标题', dataIndex: 'title', align: 'center', ellipsis: true },
    { title: '操作人', dataIndex: 'operator', align: 'center', width: 110, ellipsis: true },
    {
      title: '操作地址',
      key: 'ipAddress',
      align: 'center',
      width: 160,
      ellipsis: true,
      render: (_v, row) => <span>{String((row.ipAddress || row.ip) ?? '')}</span>
    },
    {
      title: '新增时间',
      dataIndex: 'addTime',
      align: 'center',
      width: 180,
      render: (value: string) => <span>{parseTime(value)}</span>
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      width: 90,
      render: (_v, row) => (
        <a onClick={() => handleDetail(row)}>
          <EyeOutlined /> 详细
        </a>
      )
    }
  ]

  return (
    <div className="app-container">
      {/* 搜索栏 */}
      <Form
        form={searchForm}
        layout="inline"
        style={{ display: table.showSearch ? 'flex' : 'none', marginBottom: 16, flexWrap: 'wrap', gap: '8px 0' }}
      >
        <Form.Item label="日志类型" name="type">
          <Select
            style={{ width: 200 }}
            placeholder="日志类型"
            allowClear
            value={queryParams.type}
            onChange={(v) => setQueryParams((prev) => ({ ...prev, type: v }))}
          >
            <Select.Option value={-1}>全部</Select.Option>
            {typeDict.options.map((item: EnumOption) => (
              <Select.Option key={item.code} value={item.code}>
                {item.title}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="系统模块" name="module">
          <Select
            style={{ width: 200 }}
            placeholder="系统模块"
            allowClear
            value={queryParams.module}
            onChange={(v) => setQueryParams((prev) => ({ ...prev, module: v }))}
          >
            <Select.Option value={0}>全部</Select.Option>
            {moduleDict.options.map((item: EnumOption) => (
              <Select.Option key={item.code} value={item.code}>
                {item.title}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="日志标题" name="title">
          <Input
            style={{ width: 200 }}
            placeholder="请输入日志标题"
            allowClear
            value={queryParams.title}
            onChange={(e) => setQueryParams((prev) => ({ ...prev, title: e.target.value }))}
            onPressEnter={handleQuery}
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
            搜索
          </Button>
          <Button style={{ marginLeft: 8 }} icon={<ReloadOutlined />} onClick={resetQuery}>
            重置
          </Button>
        </Form.Item>
      </Form>

      {/* 操作按钮 */}
      <div className="mb8" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <Auth roles={['admin']}>
          <Button danger icon={<DeleteOutlined />} disabled={table.multiple} onClick={handleDelete}>
            删除
          </Button>
          <Button icon={<DownloadOutlined />} onClick={handleExport}>
            导出
          </Button>
        </Auth>
        <div style={{ marginLeft: 'auto' }}>
          <RightToolbar showSearch={table.showSearch} onUpdateShowSearch={(v) => setTable((prev) => ({ ...prev, showSearch: v }))} onQueryTable={getList} />
        </div>
      </div>

      {/* 日志列表 */}
      <Table
        rowKey={(record) => String(record.id)}
        loading={table.loading}
        dataSource={table.list}
        columns={columns}
        rowSelection={{ onChange: handleSelectionChange }}
        pagination={false}
      />

      {/* 分页 */}
      <div style={{ display: table.total > 0 ? 'block' : 'none' }}>
        <Pagination
          total={table.total}
          page={queryParams.pageNum}
          limit={queryParams.pageSize}
          onPageChange={(v) => setQueryParams((prev) => ({ ...prev, pageNum: v }))}
          onLimitChange={(v) => setQueryParams((prev) => ({ ...prev, pageSize: v }))}
          onPagination={getList}
        />
      </div>

      {/* 日志详情弹窗 */}
      <LogDetail ref={logDetailRef} moduleMap={moduleDict.map} />
    </div>
  )
}

// xxl-boot-ui-vue/src/views/system/log/index.vue
<!--
  页面：Log（日志管理）
  功能：查询、删除日志，查看日志详情
-->
<template>
  <div class="app-container">
    <!-- 搜索栏 -->
    <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="table.showSearch">
      <el-form-item label="日志类型" prop="type">
        <el-select v-model="queryParams.type" placeholder="日志类型" clearable style="width: 200px">
          <el-option label="全部" :value="-1" />
          <el-option v-for="item in typeDict.options" :key="item.code" :label="item.title" :value="item.code" />
        </el-select>
      </el-form-item>
      <el-form-item label="系统模块" prop="module">
        <el-select v-model="queryParams.module" placeholder="系统模块" clearable style="width: 200px">
          <el-option label="全部" :value="0" />
          <el-option v-for="item in moduleDict.options" :key="item.code" :label="item.title" :value="item.code" />
        </el-select>
      </el-form-item>
      <el-form-item label="日志标题" prop="title">
        <el-input v-model="queryParams.title" placeholder="请输入日志标题" clearable style="width: 200px" @keyup.enter="handleQuery" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <!-- 操作按钮 -->
    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button type="danger" plain icon="Delete" :disabled="table.multiple" @click="handleDelete" v-hasRole="['admin']">删除</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="warning" plain icon="Download" @click="handleExport" v-hasRole="['admin']">导出</el-button>
      </el-col>
      <RightToolbar v-model:showSearch="table.showSearch" @queryTable="getList"></RightToolbar>
    </el-row>

    <!-- 日志列表 -->
    <el-table v-loading="table.loading" :data="table.list" @selection-change="handleSelectionChange">
      <el-table-column type="selection" width="50" align="center" />
      <el-table-column label="日志编号" align="center" prop="id" width="80" />
      <el-table-column label="日志类型" align="center" width="100">
        <template #default="scope">
          <el-tag :type="scope.row.type === 0 ? 'primary' : 'warning'" size="small">
            {{ typeText(scope.row.type) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="系统模块" align="center" :show-overflow-tooltip="true">
        <template #default="scope">
          {{ moduleDict.map[scope.row.module] || scope.row.module }}
        </template>
      </el-table-column>
      <el-table-column label="日志标题" align="center" prop="title" :show-overflow-tooltip="true" />
      <el-table-column label="操作人" align="center" prop="operator" width="110" :show-overflow-tooltip="true" />
      <el-table-column label="操作地址" align="center" :show-overflow-tooltip="true" width="160">
        <template #default="scope">
          {{ scope.row.ipAddress || scope.row.ip }}
        </template>
      </el-table-column>
      <el-table-column label="新增时间" align="center" prop="addTime" width="180">
        <template #default="scope">
          <span>{{ parseTime(scope.row.addTime) }}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" align="center" class-name="small-padding fixed-width">
        <template #default="scope">
          <el-button link type="primary" icon="View" @click="handleDetail(scope.row)">详细</el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <Pagination
      v-show="table.total > 0"
      :total="table.total"
      v-model:page="queryParams.pageNum"
      v-model:limit="queryParams.pageSize"
      @pagination="getList"
    />

    <!-- 详情弹窗 -->
    <LogDetail v-model:visible="detail.visible" :row="detail.row" :module-map="moduleDict.map" />
  </div>
</template>

<script setup lang="ts">
defineOptions({ name: 'Log' })
import LogDetail from './detail.vue'
import { pageList, delOperlog } from '@/api/system/log'
import { loadEnumItem } from '@/api/system/dict/data'
import { parseTime } from '@/utils/common'
import { useFormReset } from '@/composables/useFormReset'
import { usePageParams } from '@/composables/usePageParams'
import modal from '@/utils/modal'
import { download } from '@/utils/request'
import type { Log, LogQuery } from '@/types/api'
import type { EnumOption, TableState } from '@/types'

const resetForm = useFormReset()

/** 详情弹窗状态 */
interface DetailState {
  visible: boolean
  row: Log
}

/** 枚举数据状态（下拉选项 + 编码 → 名称映射） */
interface DictState {
  options: EnumOption[]
  map: Record<number | string, string | undefined>
}

// --------------------------------- ref data ---------------------------------

// 筛选：表单数据
const queryParams = ref<LogQuery>({
  pageNum: 1 /* 当前页码 */,
  pageSize: 10 /* 每页条数 */,
  type: -1 /* 日志类型（-1 全部） */,
  module: 0 /* 系统模块编码（0 全部） */,
  title: undefined /* 日志标题 */
})

// 表格：UI数据
const table = ref<TableState<Log>>({
  list: [] /* 表格：列表数据 */,
  total: 0 /* 表格：总条数 */,
  loading: true /* 表格：加载状态 */,
  showSearch: true /* 表格：是否显示搜索栏 */,
  ids: [] /* 表格：选中行 ID 数组 */,
  multiple: true /* 表格：是否多选 */
})

// 详情弹框：UI数据
const detail = ref<DetailState>({
  visible: false /* 详情弹窗：可见状态 */,
  row: {} /* 详情弹窗：当前查看的日志行 */
})

// 枚举数据（下拉选项 + 编码→名称映射）
const typeDict = ref<DictState>({
  options: [] /* 日志类型下拉选项 */,
  map: {} /* 日志类型编码 → 名称映射 */
})
const moduleDict = ref<DictState>({
  options: [] /* 系统模块下拉选项 */,
  map: {} /* 系统模块编码 → 名称映射 */
})

// --------------------------------- fun ---------------------------------

/** 查询日志列表 */
function getList() {
  table.value.loading = true
  // 前端分页参数 → 后端请求参数（offset/pagesize）
  const params = usePageParams(queryParams)()
  pageList(params).then((response) => {
    table.value.list = response.data.data
    table.value.total = response.data.total
    table.value.loading = false
  })
}

/** 日志类型编码 → 文案 */
function typeText(type: number) {
  const item = typeDict.value.options.find((i) => i.code === type)
  return item ? item.title : type
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  resetForm('queryRef')
  queryParams.value.pageNum = 1
  getList()
}

/** 多选框选中数据 */
function handleSelectionChange(selection: Log[]) {
  table.value.ids = selection.map((item) => item.id as number)
  table.value.multiple = !selection.length
}

/** 查看日志详情 */
function handleDetail(row: Log) {
  detail.value = { visible: true, row }
}

/** 删除日志（顶部按钮 @click 传事件对象，取勾选 ids） */

/** 导出按钮操作 */
function handleExport() {
  download(
    'system/log/export',
    {
      ...usePageParams(queryParams)()
    },
    `log_${new Date().getTime()}.xlsx`
  )
}

/** 删除按钮操作（顶部按钮 @click 传事件对象，需取勾选 ids） */
function handleDelete(row: any) {
  const logIds = row?.id ?? table.value.ids
  if (logIds == null || (Array.isArray(logIds) && logIds.length === 0)) {
    return
  }
  modal
    .confirm('是否确认删除日志编号为"' + logIds + '"的数据项?')
    .then(function () {
      return delOperlog(logIds)
    })
    .then(() => {
      getList()
      modal.msgSuccess('删除成功')
    })
    .catch(() => {})
}

// --------------------------------- init page ---------------------------------

// 加载日志类型、系统模块枚举（下拉选项）
loadEnumItem('LogTypeEnum').then((res) => {
  typeDict.value.options = res.data
  typeDict.value.map = {}
  typeDict.value.options.forEach((item) => {
    typeDict.value.map[item.code] = item.title
  })
})
loadEnumItem('LogModuleEnum').then((res) => {
  moduleDict.value.options = res.data
  moduleDict.value.map = {}
  moduleDict.value.options.forEach((item) => {
    moduleDict.value.map[item.code] = item.title
  })
})

// 页面初始化加载日志列表
getList()
</script>
