// xxl-boot-ui/src/views/tool/codegen/index.vue
<!--
  页面：代码生成管理
  功能：查询、创建、修改、删除、预览、生成代码
-->
<template>
  <div class="app-container">
    <!-- 搜索栏 -->
    <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="table.showSearch">
      <el-form-item label="表名称" prop="tableName">
        <el-input
          v-model="queryParams.tableName"
          placeholder="请输入表名称"
          clearable
          style="width: 200px"
          @keyup.enter="handleQuery"
        />
      </el-form-item>
      <el-form-item label="表描述" prop="tableComment">
        <el-input
          v-model="queryParams.tableComment"
          placeholder="请输入表描述"
          clearable
          style="width: 200px"
          @keyup.enter="handleQuery"
        />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <!-- 操作按钮 -->
    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button type="primary" plain icon="Plus" @click="openCreateDialog" v-hasRole="['admin']">创建</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="success" plain icon="Edit" :disabled="table.single" @click="handleEditTable" v-hasRole="['admin']">修改</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="danger" plain icon="Delete" :disabled="table.multiple" @click="handleDelete" v-hasRole="['admin']">删除</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="primary" plain icon="Download" :disabled="table.multiple" @click="handleGenTable" v-hasRole="['admin']">生成</el-button>
      </el-col>
      <RightToolbar v-model:showSearch="table.showSearch" @queryTable="getList"></RightToolbar>
    </el-row>

    <!-- 表格区域 -->
    <el-table ref="genRef" v-loading="table.loading" :data="table.list" @selection-change="handleSelectionChange">
      <el-table-column type="selection" align="center" width="55"></el-table-column>
      <el-table-column label="序号" type="index" width="50" align="center">
        <template #default="scope">
          <span>{{ (queryParams.pageNum - 1) * queryParams.pageSize + scope.$index + 1 }}</span>
        </template>
      </el-table-column>
      <el-table-column label="表名称" align="center" prop="tableName" :show-overflow-tooltip="true"/>
      <el-table-column label="表描述" align="center" prop="tableComment" :show-overflow-tooltip="true"/>
      <el-table-column label="创建时间" align="center" prop="addTime" width="160"/>
      <el-table-column label="更新时间" align="center" prop="updateTime" width="160"/>
      <el-table-column label="操作" align="center" width="330" class-name="small-padding fixed-width">
        <template #default="scope">
          <el-tooltip content="编辑" placement="top">
            <el-button link type="primary" icon="Edit" @click="handleEditTable(scope.row)" v-hasRole="['admin']">编辑</el-button>
          </el-tooltip>
          <el-tooltip content="删除" placement="top">
            <el-button link type="primary" icon="Delete" @click="handleDelete(scope.row)" v-hasRole="['admin']">删除</el-button>
          </el-tooltip>
          <el-tooltip content="预览" placement="top">
            <el-button link type="primary" icon="View" @click="handlePreview(scope.row)" v-hasRole="['admin']">预览</el-button>
          </el-tooltip>
          <el-tooltip content="生成代码" placement="top">
            <el-button link type="primary" icon="Download" @click="handleGenTable(scope.row)" v-hasRole="['admin']">生成代码</el-button>
          </el-tooltip>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <Pagination
      v-show="table.total>0"
      :total="table.total"
      v-model:page="queryParams.pageNum"
      v-model:limit="queryParams.pageSize"
      @pagination="getList"
    />

    <!-- 预览界面 -->
    <el-dialog :title="preview.title" v-model="preview.open" width="80%" top="5vh" append-to-body class="scrollbar">
      <el-tabs v-model="preview.activeName">
        <el-tab-pane
          v-for="(value, key) in preview.data"
          :label="key.substring(key.lastIndexOf('/')+1,key.indexOf('.ftl'))"
          :name="key.substring(key.lastIndexOf('/')+1,key.indexOf('.ftl'))"
          :key="value"
        >
          <el-link underline="never" icon="DocumentCopy" v-copyText="value" v-copyText:callback="copyTextSuccess"
                   style="float:right">&nbsp;复制
          </el-link>
          <pre>{{ value }}</pre>
        </el-tab-pane>
      </el-tabs>
    </el-dialog>

    <!-- 创建表弹窗 -->
    <el-dialog v-model="createDialog.visible" title="创建表" width="800px" top="5vh" append-to-body>
      <span>创建表语句(支持多个建表语句)：</span>
      <el-input type="textarea" :rows="10" placeholder="请输入文本" v-model="createDialog.content"></el-input>
      <template #footer>
        <el-button type="primary" @click="handleCreateTable">确 定</el-button>
        <el-button @click="createDialog.visible = false">取 消</el-button>
      </template>
    </el-dialog>

    <!-- 编辑代码生成信息 -->
    <EditTable ref="editRef" @ok="handleQuery"/>
  </div>
</template>

<script setup lang="ts" name="Gen">
import { listTable, previewTable, delTable, createTable } from '@/api/tool/codegen'
import type { CodegenTable } from '@/api/tool/codegen'
import { useFormReset } from '@/composables/useFormReset'
import modal from '@/utils/modal'
import downloadPlugin from '@/utils/download'
import EditTable from './editTable.vue'

const resetForm = useFormReset()

/* --------------------------------- ref data --------------------------------- */

// 路由参数
const route = useRoute()             /* 当前路由 */
const uniqueId = ref("")             /* 页面路由唯一标识 */

// 组件实例引用
const editRef = ref<InstanceType<typeof EditTable> | null>(null)            /* 编辑弹窗 ref */

// 搜索栏：查询参数
const queryParams = ref({
  pageNum: 1,        /* 当前页码 */
  pageSize: 10,      /* 每页条数 */
  tableName: undefined,  /* 表名称 */
  tableComment: undefined /* 表描述 */
})

// 表格：UI数据
const table = ref({
  list: [] as CodegenTable[],  /* 表列表数据 */
  total: 0,          /* 总条数 */
  loading: true,     /* 加载状态 */
  showSearch: true,  /* 是否显示搜索栏 */
  ids: [] as number[],  /* 选中行 ID 数组 */
  single: true,      /* 是否单选 */
  multiple: true     /* 是否多选 */
})

// 预览弹窗
const preview = ref({
  open: false,       /* 弹窗显隐 */
  title: "代码预览",  /* 弹窗标题 */
  data: {} as Record<string, string>,          /* 预览代码数据 */
  activeName: "entity.java" /* 激活标签 */
})

// 创建表弹窗
const createDialog = ref({
  visible: false,  /* 弹窗显隐 */
  content: ""      /* 建表 SQL 语句 */
})


/* --------------------------------- fun --------------------------------- */

/** 页面激活时：若路由携带时间戳且与上次不同，则刷新列表 */
onActivated(() => {
  const time = route.query.t
  if (time != null && time !== uniqueId.value) {
    uniqueId.value = time as string
    queryParams.value.pageNum = Number(route.query.pageNum)
    resetForm("queryForm")
    getList()
  }
})

/** 查询表集合 */
function getList() {
  table.value.loading = true
  listTable(queryParams.value).then(response => {
    table.value.list = response.data.data
    table.value.total = response.data.total
    table.value.loading = false
  })
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  resetForm("queryRef")
  queryParams.value.pageNum = 1
  getList()
}

/** 多选框选中数据 */
function handleSelectionChange(selection: CodegenTable[]) {
  table.value.ids = selection.map(item => item.id as number)
  table.value.single = selection.length != 1
  table.value.multiple = !selection.length
}

/** 生成代码操作 */
function handleGenTable(row: any) {
  const idList = row && row.id != null ? [row.id] : table.value.ids
  if (!idList || idList.length === 0) {
    modal.msgError("请选择要生成的数据")
    return
  }
  const zipName = "xxl-boot-codegen.zip"
  const query = idList.map(id => "ids=" + id).join("&")
  downloadPlugin.zip("/tool/codegen/batchGenCode?" + query, zipName)
}

/** 打开创建表弹窗 */
function openCreateDialog() {

  let demo_sql = `CREATE TABLE \`test01\` (
      \`id\`            INT             NOT NULL AUTO_INCREMENT      COMMENT '主键ID',
      \`name\`          VARCHAR(50)     NOT NULL                     COMMENT '名称',
      \`age\`           INT             NOT NULL                     COMMENT '年龄',
      \`add_time\`      DATETIME        NOT NULL                     COMMENT '新增时间',
      \`update_time\`   DATETIME        NOT NULL                     COMMENT '更新时间',
      PRIMARY KEY (\`id\`)
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
  `

  createDialog.value.content = demo_sql
  createDialog.value.visible = true
}

/** 创建表 */
function handleCreateTable() {
  if (createDialog.value.content === "") {
    modal.msgError("请输入建表语句")
    return
  }
  createTable({ tableSql: createDialog.value.content }).then(() => {
    modal.msgSuccess("创建成功")
    createDialog.value.visible = false
    handleQuery()
  })
}

/** 预览按钮 */
function handlePreview(row: any) {
  previewTable(row.id).then(response => {
    preview.value.data = response.data
    preview.value.open = true
    const keys = Object.keys(response.data)
    preview.value.activeName = keys.length > 0 ? keys[0].substring(keys[0].lastIndexOf('/') + 1, keys[0].indexOf('.ftl')) : "entity.java"
  })
}

/** 复制代码成功 */
function copyTextSuccess() {
  modal.msgSuccess("复制成功")
}

/** 修改按钮操作（顶部按钮 @click 传事件对象，需取勾选 id） */
function handleEditTable(row: any) {
  // 顶部按钮点击传入的是事件对象而非行数据，此时取勾选 id
  const id = row?.id ?? table.value.ids[0]
  if (id == null) {
    return
  }
  editRef.value!.open(id)
}

/** 删除按钮操作（顶部按钮 @click 传事件对象，需取勾选 ids） */
function handleDelete(row: any) {
  const tableIds = row?.id ?? table.value.ids
  if (tableIds == null || (Array.isArray(tableIds) && tableIds.length === 0)) {
    return
  }
  modal.confirm('是否确认删除表编号为"' + tableIds + '"的数据项？').then(function() {
    return delTable(tableIds)
  }).then(() => {
    getList()
    modal.msgSuccess("删除成功")
  }).catch(() => {})
}

/* --------------------------------- page init --------------------------------- */
getList()

</script>

// xxl-boot-ui-react/src/views/tool/codegen/index.tsx
/**
 * 页面：代码生成管理
 * 功能：查询、创建、修改、删除、预览、生成代码
 * @author xuxueli 2026-08-09
 */
import { useEffect, useRef, useState } from 'react'
import { Button, Form, Input, Modal, Table, Tabs, Tooltip } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EyeOutlined,
  CopyOutlined,
  SearchOutlined,
  ReloadOutlined
} from '@ant-design/icons'
import Pagination from '@/components/Pagination'
import RightToolbar from '@/components/RightToolbar'
import Auth from '@/components/Auth'
import EditTable, { type EditTableHandle } from './editTable'
import { listTable, previewTable, delTable, createTable } from '@/api/tool/codegen'
import type { CodegenTable } from '@/api/tool/codegen'
import { buildPageParams } from '@/hooks/buildPageParams'
import modal from '@/utils/modal'
import downloadPlugin from '@/utils/download'
import './index.scss'

// --------------------------------- ref data ---------------------------------

/** 搜索栏：查询参数 */
interface CodegenQueryState {
  pageNum: number
  pageSize: number
  tableName?: string
  tableComment?: string
  [key: string]: unknown
}

/** 表格：UI数据 */
interface TableState {
  list: CodegenTable[]
  total: number
  loading: boolean
  showSearch: boolean
  ids: number[]
  single: boolean
  multiple: boolean
}

/** 预览弹窗：数据状态 */
interface PreviewState {
  open: boolean
  title: string
  data: Record<string, string>
  activeName: string
}

/** 创建表弹窗：数据状态 */
interface CreateDialogState {
  visible: boolean
  content: string
}

export default function Codegen() {
  // 编辑弹窗 ref
  const editRef = useRef<EditTableHandle>(null)

  // 页面初始化：加载生成表列表
  useEffect(() => {
    getList()
     
  }, [])

  // 搜索栏：查询参数
  const [queryParams, setQueryParams] = useState<CodegenQueryState>({
    pageNum: 1,
    pageSize: 10,
    tableName: undefined,
    tableComment: undefined
  })

  // 表格：UI数据
  const [table, setTable] = useState<TableState>({
    list: [],
    total: 0,
    loading: true,
    showSearch: true,
    ids: [],
    single: true,
    multiple: true
  })

  // 预览弹窗：数据状态
  const [preview, setPreview] = useState<PreviewState>({
    open: false,
    title: '代码预览',
    data: {},
    activeName: 'entity.java'
  })

  // 创建表弹窗：数据状态
  const [createDialog, setCreateDialog] = useState<CreateDialogState>({
    visible: false,
    content: ''
  })

  // 表单实例
  const [searchForm] = Form.useForm()

  // --------------------------------- fun ---------------------------------

  /** 查询表集合 */
  function getList() {
    setTable((prev) => ({ ...prev, loading: true }))
    const params = buildPageParams(queryParams)()
    listTable(params).then((response) => {
      setTable((prev) => ({
        ...prev,
        list: response.data.data,
        total: response.data.total,
        loading: false
      }))
    })
  }

  /** 搜索按钮操作 */
  function handleQuery() {
    setQueryParams((prev) => ({ ...prev, pageNum: 1 }))
    getList()
  }

  /** 重置按钮操作 */
  function resetQuery() {
    searchForm.resetFields()
    setQueryParams((prev) => ({ ...prev, tableName: undefined, tableComment: undefined, pageNum: 1 }))
    handleQuery()
  }

  /** 多选框选中数据 */
  function handleSelectionChange(selectedRowKeys: React.Key[]) {
    const ids = selectedRowKeys.map((k) => Number(k))
    setTable((prev) => ({
      ...prev,
      ids,
      single: selectedRowKeys.length !== 1,
      multiple: !selectedRowKeys.length
    }))
  }

  /** 生成代码操作 */
  function handleGenTable(row: any) {
    const idList = row && row.id != null ? [row.id] : table.ids
    if (!idList || idList.length === 0) {
      modal.msgError('请选择要生成的数据')
      return
    }
    const zipName = 'xxl-boot-codegen.zip'
    const query = idList.map((id) => 'ids=' + id).join('&')
    downloadPlugin.zip('/tool/codegen/batchGenCode?' + query, zipName)
  }

  /** 打开创建表弹窗 */
  function openCreateDialog() {
    const demoSql = `CREATE TABLE \`product01\` (
      \`id\`            INT             NOT NULL AUTO_INCREMENT      COMMENT '主键ID',
      \`name\`          VARCHAR(50)     NOT NULL                     COMMENT '产品名称',
      \`num\`           INT             NOT NULL                     COMMENT '产品数量',
      \`add_time\`      DATETIME        NOT NULL                     COMMENT '新增时间',
      \`update_time\`   DATETIME        NOT NULL                     COMMENT '更新时间',
      PRIMARY KEY (\`id\`)
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT='产品信息表';
  `
    setCreateDialog({ visible: true, content: demoSql })
  }

  /** 创建表 */
  function handleCreateTable() {
    if (createDialog.content === '') {
      modal.msgError('请输入建表语句')
      return
    }
    createTable({ tableSql: createDialog.content }).then(() => {
      modal.msgSuccess('创建成功')
      setCreateDialog((prev) => ({ ...prev, visible: false }))
      handleQuery()
    })
  }

  /** 预览按钮 */
  function handlePreview(row: any) {
    previewTable(row.id).then((response) => {
      const data = response.data || {}
      const keys = Object.keys(data)
      setPreview({
        open: true,
        title: '代码预览',
        data,
        activeName:
          keys.length > 0 ? keys[0].substring(keys[0].lastIndexOf('/') + 1, keys[0].indexOf('.ftl')) : 'entity.java'
      })
    })
  }

  /** 复制代码 */
  function handleCopy(value: string) {
    navigator.clipboard.writeText(value).then(() => modal.msgSuccess('复制成功'))
  }

  /** 修改按钮操作（顶部按钮点击传入事件对象，此时取勾选 id） */
  function handleEditTable(row: any) {
    const id = row?.id ?? table.ids[0]
    if (id == null) {
      return
    }
    editRef.current?.open(id)
  }

  /** 删除按钮操作（顶部按钮点击传入事件对象，此时取勾选 ids） */
  function handleDelete(row: any) {
    const tableIds = row?.id ?? table.ids
    if (tableIds == null || (Array.isArray(tableIds) && tableIds.length === 0)) {
      return
    }
    modal
      .confirm('是否确认删除表编号为"' + tableIds + '"的数据项？')
      .then(function () {
        return delTable(tableIds)
      })
      .then(() => {
        getList()
        modal.msgSuccess('删除成功')
      })
      .catch(() => {})
  }

  // --------------------------------- 表格列 ---------------------------------

  const columns: ColumnsType<CodegenTable> = [
    {
      title: '序号',
      key: 'index',
      width: 50,
      align: 'center',
      render: (_v, _row, index) => (
        <span>{(queryParams.pageNum - 1) * queryParams.pageSize + (index ?? 0) + 1}</span>
      )
    },
    { title: '表名称', dataIndex: 'tableName', align: 'center', ellipsis: true },
    { title: '表描述', dataIndex: 'tableComment', align: 'center', ellipsis: true },
    { title: '创建时间', dataIndex: 'addTime', align: 'center', width: 160 },
    { title: '更新时间', dataIndex: 'updateTime', align: 'center', width: 160 },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      width: 330,
      render: (_v, row) => (
        <Auth roles={['admin']}>
          <Tooltip title="编辑" placement="top">
            <a style={{ marginRight: 8 }} onClick={() => handleEditTable(row)}>
              <EditOutlined /> 编辑
            </a>
          </Tooltip>
          <Tooltip title="删除" placement="top">
            <a style={{ marginRight: 8 }} onClick={() => handleDelete(row)}>
              <DeleteOutlined /> 删除
            </a>
          </Tooltip>
          <Tooltip title="预览" placement="top">
            <a style={{ marginRight: 8 }} onClick={() => handlePreview(row)}>
              <EyeOutlined /> 预览
            </a>
          </Tooltip>
          <Tooltip title="生成代码" placement="top">
            <a onClick={() => handleGenTable(row)}>
              <DownloadOutlined /> 生成代码
            </a>
          </Tooltip>
        </Auth>
      )
    }
  ]

  // 预览弹窗 TAB 数据（key → 代码内容）
  const previewItems = Object.keys(preview.data).map((key) => {
    const label = key.substring(key.lastIndexOf('/') + 1, key.indexOf('.ftl'))
    return {
      key: label,
      label,
      children: (
        <div>
          <a style={{ float: 'right' }} onClick={() => handleCopy(preview.data[key])}>
            <CopyOutlined /> 复制
          </a>
          <pre className="codegen-pre">{preview.data[key]}</pre>
        </div>
      )
    }
  })

  return (
    <div className="app-container">
      {/* 搜索栏 */}
      <Form
        form={searchForm}
        layout="inline"
        style={{ display: table.showSearch ? 'flex' : 'none', marginBottom: 16, flexWrap: 'wrap', gap: '8px 0' }}
      >
        <Form.Item label="表名称" name="tableName">
          <Input
            style={{ width: 200 }}
            placeholder="请输入表名称"
            allowClear
            value={queryParams.tableName}
            onChange={(e) => setQueryParams((prev) => ({ ...prev, tableName: e.target.value }))}
            onPressEnter={handleQuery}
          />
        </Form.Item>
        <Form.Item label="表描述" name="tableComment">
          <Input
            style={{ width: 200 }}
            placeholder="请输入表描述"
            allowClear
            value={queryParams.tableComment}
            onChange={(e) => setQueryParams((prev) => ({ ...prev, tableComment: e.target.value }))}
            onPressEnter={handleQuery}
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
            搜索
          </Button>
          <Button style={{ marginLeft: 8 }} icon={<ReloadOutlined />} onClick={resetQuery}>
            重置
          </Button>
        </Form.Item>
      </Form>

      {/* 操作按钮 */}
      <div className="mb8" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <Auth roles={['admin']}>
          <Button type="primary" icon={<PlusOutlined />} onClick={openCreateDialog}>
            创建
          </Button>
          <Button type="primary" icon={<EditOutlined />} disabled={table.single} onClick={handleEditTable}>
            修改
          </Button>
          <Button danger icon={<DeleteOutlined />} disabled={table.multiple} onClick={handleDelete}>
            删除
          </Button>
          <Button type="primary" icon={<DownloadOutlined />} disabled={table.multiple} onClick={handleGenTable}>
            生成
          </Button>
        </Auth>
        <div style={{ marginLeft: 'auto' }}>
          <RightToolbar showSearch={table.showSearch} onUpdateShowSearch={(v) => setTable((prev) => ({ ...prev, showSearch: v }))} onQueryTable={getList} />
        </div>
      </div>

      {/* 生成表列表 */}
      <Table
        rowKey={(record) => String(record.id)}
        loading={table.loading}
        dataSource={table.list}
        columns={columns}
        rowSelection={{ onChange: handleSelectionChange }}
        pagination={false}
      />

      {/* 分页 */}
      <div style={{ display: table.total > 0 ? 'block' : 'none' }}>
        <Pagination
          total={table.total}
          page={queryParams.pageNum}
          limit={queryParams.pageSize}
          onPageChange={(v) => setQueryParams((prev) => ({ ...prev, pageNum: v }))}
          onLimitChange={(v) => setQueryParams((prev) => ({ ...prev, pageSize: v }))}
          onPagination={getList}
        />
      </div>

      {/* 预览界面 */}
      <Modal
        title={preview.title}
        open={preview.open}
        width="80%"
        style={{ top: '5vh' }}
        footer={null}
        onCancel={() => setPreview((prev) => ({ ...prev, open: false }))}
        destroyOnClose
      >
        <Tabs
          activeKey={preview.activeName}
          onChange={(key) => setPreview((prev) => ({ ...prev, activeName: key }))}
          items={previewItems}
        />
      </Modal>

      {/* 创建表弹窗 */}
      <Modal
        title="创建表"
        open={createDialog.visible}
        width={800}
        style={{ top: '5vh' }}
        onCancel={() => setCreateDialog((prev) => ({ ...prev, visible: false }))}
        footer={
          <div>
            <Button type="primary" onClick={handleCreateTable}>
              确 定
            </Button>
            <Button style={{ marginLeft: 8 }} onClick={() => setCreateDialog((prev) => ({ ...prev, visible: false }))}>
              取 消
            </Button>
          </div>
        }
      >
        <span>创建表语句(支持多个建表语句)：</span>
        <Input.TextArea
          rows={10}
          placeholder="请输入文本"
          value={createDialog.content}
          onChange={(e) => setCreateDialog((prev) => ({ ...prev, content: e.target.value }))}
        />
      </Modal>

      {/* 编辑代码生成信息 */}
      <EditTable ref={editRef} onOk={handleQuery} />
    </div>
  )
}
