// xxl-boot-ui/xxl-boot-ui-react/src/modules/framework/authz/user/pages/profile/ResetPwd.tsx
/**
 * 页面：ResetPwd（修改密码）
 * 功能：旧密码、新密码、确认密码表单提交，修改当前登录用户密码
 */

import { ProForm, ProFormText } from '@ant-design/pro-components';
import { App, Button } from 'antd';
import type { Rule } from 'antd/es/form';
import React from 'react';
import { updateUserPwd } from '@/modules/framework/authz/user/api';

/** 密码表单数据 */
interface PwdForm {
  oldPassword?: string;
  newPassword?: string;
  confirmPassword?: string;
}

/**
 * 新密码校验规则：必填 + 长度 6-20 + 任意字符（禁止 < > " ' \ |）
 * 说明：原设计按后端 chrtype（0-4）动态切换密码策略，但全项目无任何写入方，
 *       实际恒为默认策略 0（任意字符），故直接固定为一条规则。
 */
const INFO_PWD_RULES: Rule[] = [
  { required: true, message: '新密码不能为空' },
  { min: 6, max: 20, message: '新密码长度必须介于 6 和 20 之间' },
  { pattern: /^[^<>"'|\\]+$/, message: '密码不能包含非法字符：< > " \' \\ |' },
];

const ResetPwd = () => {
  const { message } = App.useApp();
  const [form] = ProForm.useForm();

  /** 提交保存 */
  const handleSubmit = async (values: PwdForm) => {
    await updateUserPwd(
      values.oldPassword as string,
      values.newPassword as string,
    );
    message.success('修改成功');
    form.resetFields();
  };

  return (
    <ProForm<PwdForm>
      form={form}
      layout="horizontal"
      labelCol={{ span: 4 }}
      onFinish={handleSubmit}
      submitter={{
        render: ({ submit }) => [
          <Button type="primary" key="submit" onClick={() => submit()}>
            保存
          </Button>,
          <Button
            type="default"
            key="cancel"
            onClick={() => form.resetFields()}
          >
            重置
          </Button>,
        ],
      }}
    >
      <ProFormText.Password
        name="oldPassword"
        label="旧密码"
        placeholder="请输入旧密码"
        rules={[{ required: true, message: '旧密码不能为空' }]}
      />
      <ProFormText.Password
        name="newPassword"
        label="新密码"
        placeholder="请输入新密码"
        rules={INFO_PWD_RULES}
      />
      <ProFormText.Password
        name="confirmPassword"
        label="确认密码"
        placeholder="请确认新密码"
        dependencies={['newPassword']}
        rules={[
          { required: true, message: '确认密码不能为空' },
          ({ getFieldValue }) => ({
            /* 自定义规则：返回 Promise，处理异步操作； */
            validator: (_, value) => {
              if (!value || getFieldValue('newPassword') === value) {
                return Promise.resolve();
              }
              return Promise.reject(new Error('两次输入的密码不一致'));
            },
          }),
        ]}
      />
    </ProForm>
  );
};

export default ResetPwd;

// xxl-boot-ui/xxl-boot-ui-vue/src/views/authz/user/profile/resetPwd.vue
<!--
  页面：ResetPwd（修改密码）
  功能：旧密码、新密码、确认密码表单提交，修改当前登录用户密码
-->
<template>
  <!-- 修改密码表单 -->
  <el-form ref="pwdRef" :model="user" :rules="rules" label-width="80px">
    <el-form-item label="旧密码" prop="oldPassword">
      <el-input v-model="user.oldPassword" placeholder="请输入旧密码" type="password" show-password />
    </el-form-item>
    <el-form-item label="新密码" prop="newPassword">
      <el-input v-model="user.newPassword" placeholder="请输入新密码" type="password" show-password />
    </el-form-item>
    <el-form-item label="确认密码" prop="confirmPassword">
      <el-input v-model="user.confirmPassword" placeholder="请确认新密码" type="password" show-password />
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="submit">保存</el-button>
      <el-button type="danger" @click="close">关闭</el-button>
    </el-form-item>
  </el-form>
</template>

<script setup lang="ts">
// 引入
import { updateUserPwd } from '@/api/authz/user'
import modal from '@/utils/modal'
import tab from '@/utils/tab'
import type { FormInstance, FormItemRule, FormRules } from 'element-plus'
import { reactive, ref } from 'vue'

/** 密码表单数据 */
interface PwdForm {
  oldPassword?: string
  newPassword?: string
  confirmPassword?: string
}

/**
 * 新密码校验规则：必填 + 长度 6-20 + 任意字符（禁止 < > " ' \ |）
 * 说明：原设计按后端 chrtype（0-4）动态切换密码策略，但全项目无任何写入方，
 *       实际恒为默认策略 0（任意字符），故直接固定为一条规则。
 */
const newPasswordRules: FormItemRule[] = [
  { required: true, message: '新密码不能为空', trigger: 'blur' },
  { min: 6, max: 20, message: '新密码长度必须介于 6 和 20 之间', trigger: 'blur' },
  { pattern: /^[^<>"'|\\]+$/, message: '密码不能包含非法字符：< > " \' \\ |', trigger: 'blur' }
]

// 表单 ref
const pwdRef = ref<FormInstance>()

// 密码表单数据
const user = reactive<PwdForm>({
  oldPassword: undefined,
  newPassword: undefined,
  confirmPassword: undefined
})

/** 校验两次密码是否一致 */
const equalToPassword: FormItemRule['validator'] = (rule, value, callback) => {
  if (user.newPassword !== value) {
    callback(new Error('两次输入的密码不一致'))
  } else {
    callback()
  }
}

// 表单校验规则
const rules = ref<FormRules>({
  oldPassword: [{ required: true, message: '旧密码不能为空', trigger: 'blur' }],
  newPassword: newPasswordRules,
  confirmPassword: [
    { required: true, message: '确认密码不能为空', trigger: 'blur' },
    {
      required: true,
      validator: equalToPassword,
      trigger: 'blur'
    }
  ]
})

/** 提交按钮 */
function submit() {
  pwdRef.value!.validate((valid) => {
    if (valid) {
      updateUserPwd(user.oldPassword as string, user.newPassword as string).then((res) => {
        modal.msgSuccess('修改成功')
        user.oldPassword = undefined
        user.newPassword = undefined
        user.confirmPassword = undefined
      })
    }
  })
}

/** 关闭按钮 */
function close() {
  tab.closePage()
}
</script>
