// xxl-boot-ui-vue/src/views/system/message/index.vue
<!--
  Message（站内消息管理）
-->
<template>
  <div class="app-container">
    <!-- 搜索栏 -->
    <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="table.showSearch">
      <el-form-item label="分类" prop="category">
        <el-select v-model="queryParams.category" placeholder="消息分类" clearable style="width: 200px">
          <el-option label="全部" :value="-1" />
          <el-option v-for="item in categoryOptions" :key="item.code" :label="item.title" :value="item.code" />
        </el-select>
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="queryParams.status" placeholder="消息状态" clearable style="width: 200px">
          <el-option label="全部" :value="-1" />
          <el-option v-for="item in statusOptions" :key="item.code" :label="item.title" :value="item.code" />
        </el-select>
      </el-form-item>
      <el-form-item label="标题" prop="title">
        <el-input v-model="queryParams.title" placeholder="请输入标题" clearable style="width: 200px" @keyup.enter="handleQuery" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <!-- 操作按钮 -->
    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasRole="['admin']">新增</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="success" plain icon="Edit" :disabled="table.single" @click="handleUpdate" v-hasRole="['admin']">修改</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button type="danger" plain icon="Delete" :disabled="table.multiple" @click="handleDelete" v-hasRole="['admin']">删除</el-button>
      </el-col>
      <RightToolbar v-model:showSearch="table.showSearch" @queryTable="getList"></RightToolbar>
    </el-row>

    <!-- 消息列表 -->
    <el-table v-loading="table.loading" :data="table.list" @selection-change="handleSelectionChange">
      <el-table-column type="selection" width="55" align="center" />
      <el-table-column label="序号" align="center" prop="id" width="100" />
      <el-table-column label="消息标题" align="center" :show-overflow-tooltip="true">
        <template #default="scope">
          <a class="link-type" style="cursor: pointer" @click="handleViewData(scope.row)">{{ scope.row.title }}</a>
        </template>
      </el-table-column>
      <el-table-column label="分类" align="center" width="100">
        <template #default="scope">
          <el-tag :type="scope.row.category === 0 ? 'primary' : 'warning'" size="small">
            {{ categoryText(scope.row.category) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="状态" align="center" width="100">
        <template #default="scope">
          <el-tag :type="scope.row.status === 0 ? 'success' : 'danger'" size="small">
            {{ statusText(scope.row.status) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="发送人" align="center" prop="sender" width="100" />
      <el-table-column label="发送时间" align="center" width="170">
        <template #default="scope">
          <span>{{ scope.row.addTime }}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" align="center" class-name="small-padding fixed-width">
        <template #default="scope">
          <el-button link type="primary" icon="User" @click="handleReadUsers(scope.row)" v-hasRole="['admin']">阅读用户</el-button>
          <el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)" v-hasRole="['admin']">修改</el-button>
          <el-button link type="primary" icon="Delete" @click="handleDelete(scope.row)" v-hasRole="['admin']">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <Pagination
      v-show="table.total > 0"
      :total="table.total"
      v-model:page="queryParams.pageNum"
      v-model:limit="queryParams.pageSize"
      @pagination="getList"
    />

    <!-- 添加或修改消息对话框 -->
    <el-dialog :title="formState.title" v-model="formState.visible" width="780px" append-to-body>
      <el-form ref="formRef" :model="formState.form" :rules="formState.rules" label-width="100px">
        <el-row>
          <el-col :span="12">
            <el-form-item label="消息标题" prop="title">
              <el-input v-model="formState.form.title" placeholder="请输入消息标题" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="分类" prop="category">
              <el-select v-model="formState.form.category" placeholder="请选择">
                <el-option v-for="item in categoryOptions" :key="item.code" :label="item.title" :value="item.code"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="状态">
              <el-radio-group v-model="formState.form.status">
                <el-radio v-for="item in statusOptions" :key="item.code" :value="item.code">{{ item.title }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="内容">
              <Editor v-model="formState.form.content" :min-height="192" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>
    <MessageDetailView ref="messageViewRef" />
    <ReadUsersDialog ref="readUsersRef" />
  </div>
</template>

<script setup lang="ts">
defineOptions({ name: 'Message' })
import ReadUsersDialog from './ReadUsers.vue'
import MessageDetailView from '@/layout/components/Navbar/HeaderMessageDetail.vue'
import { listMessage, getMessage, delMessage, addMessage, updateMessage } from '@/api/system/message'
import { useEnumOption } from '@/composables/useEnumOption'
import { useFormReset } from '@/composables/useFormReset'
import { usePageParams } from '@/composables/usePageParams'
import modal from '@/utils/modal'
import type { Message, MessageQuery } from '@/types/api'
import type { EnumOption, TableState, FormState } from '@/types'
import type { FormInstance, FormRules } from 'element-plus'
import { ref } from 'vue'

const resetForm = useFormReset()

// --------------------------------- ref data ---------------------------------

// 组件实例引用：模板 ref
const formRef = ref<FormInstance>() /* 编辑表单 ref */
const messageViewRef = ref<InstanceType<typeof MessageDetailView> | null>(null) /* 消息详情弹框 ref： */
const readUsersRef = ref<InstanceType<typeof ReadUsersDialog> | null>(null) /* 已读弹框 ref */

// 筛选项数据：消息分类 + 消息状态
const { MessageCategoryEnum: categoryOptions, MessageStatusEnum: statusOptions } = useEnumOption('MessageCategoryEnum', 'MessageStatusEnum')

// 搜索栏：查询参数
const queryParams = ref<MessageQuery>({
  pageNum: 1 /* 当前页码 */,
  pageSize: 10 /* 每页条数 */,
  category: -1 /* 分类（-1 全部、0 通知、1 公告） */,
  status: -1 /* 状态（-1 全部、0 正常、1 下线） */,
  title: undefined /* 标题关键词 */
})

// 表格：UI数据
const table = ref<TableState<Message>>({
  list: [], // 消息列表
  total: 0, // 总条数
  loading: true, // 加载状态
  showSearch: true, // 是否显示搜索栏
  ids: [], // 选中行 ID 数组
  single: true, // 是否单选
  multiple: true // 是否多选
})

// 编辑表单：数据状态
const formState = ref<FormState<Message>>({
  visible: false /* 对话框显隐 */,
  title: '' /* 对话框标题 */,
  form: {} /* 表单数据 */,
  rules: {
    /* 校验规则 */
    title: [{ required: true, message: '消息标题不能为空', trigger: 'blur' }],
    category: [{ required: true, message: '分类不能为空', trigger: 'change' }]
  }
})

// --------------------------------- fun ---------------------------------

/** 从后端枚举接口加载分类、状态选项 */

/** 查询消息列表 */
function getList() {
  table.value.loading = true
  // 前端分页参数 → 后端请求参数（offset/pagesize）
  const params = usePageParams(queryParams)()
  listMessage(params).then((response) => {
    table.value.list = response.data.data
    table.value.total = response.data.total
    table.value.loading = false
  })
}

/** 分类编码 → 文案 */
function categoryText(category: number) {
  const item = categoryOptions.value.find((i) => i.code === category)
  return item ? item.title : category
}

/** 状态编码 → 文案 */
function statusText(status: number) {
  const item = statusOptions.value.find((i) => i.code === status)
  return item ? item.title : status
}

/** 取消按钮 */
function cancel() {
  formState.value.visible = false
  reset()
}

/** 表单重置 */
function reset() {
  formState.value.form = {
    id: undefined,
    title: undefined,
    category: 0,
    content: undefined,
    status: 0
  }
  resetForm('formRef')
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  resetForm('queryRef')
  handleQuery()
}

/** 多选框选中数据 */
function handleSelectionChange(selection: Message[]) {
  table.value.ids = selection.map((item) => item.id as number)
  table.value.single = selection.length !== 1
  table.value.multiple = !selection.length
}

/** 新增按钮操作 */
function handleAdd() {
  reset()
  formState.value.visible = true
  formState.value.title = '新增站内消息'
}

/** 修改按钮操作（顶部按钮 @click 传事件对象，需取勾选 id） */
function handleUpdate(row: any) {
  reset()
  // 顶部按钮点击传入的是事件对象而非行数据，此时取勾选 id
  const id = row?.id ?? table.value.ids[0]
  if (id == null) {
    return
  }
  getMessage(id).then((response) => {
    formState.value.form = response.data
    formState.value.visible = true
    formState.value.title = '修改站内消息'
  })
}

/** 提交按钮 */
function submitForm() {
  formRef.value!.validate((valid) => {
    if (valid) {
      // 已有 id 走更新，否则走新增
      if (formState.value.form.id !== undefined) {
        updateMessage(formState.value.form).then((response) => {
          modal.msgSuccess('修改成功')
          formState.value.visible = false
          getList()
        })
      } else {
        addMessage(formState.value.form).then((response) => {
          modal.msgSuccess('新增成功')
          formState.value.visible = false
          getList()
        })
      }
    }
  })
}

/** 查看消息详情 */
function handleViewData(row: Message) {
  messageViewRef.value?.open(row.id as number)
}

/** 查看已读用户 */
function handleReadUsers(row: Message) {
  readUsersRef.value?.open(row)
}

/** 删除按钮操作（顶部按钮 @click 传事件对象，需取勾选 ids） */
function handleDelete(row: any) {
  const messageIds = row?.id ?? table.value.ids
  if (messageIds == null || (Array.isArray(messageIds) && messageIds.length === 0)) {
    return
  }
  modal
    .confirm('是否确认删除消息编号为"' + messageIds + '"的数据项？')
    .then(function () {
      return delMessage(messageIds)
    })
    .then(() => {
      getList()
      modal.msgSuccess('删除成功')
    })
    .catch(() => {})
}

// --------------------------------- page init ---------------------------------

// 页面初始化：加载分类/状态选项 + 消息列表
getList()
</script>

// xxl-boot-ui-react/src/views/system/message/index.tsx
/**
 * 页面：Message（站内消息管理）
 * 功能：站内消息列表查询、新增、修改、删除、查看详情、查看已读用户
 */
import { useEffect, useRef, useState } from 'react'
import { Button, Form, Input, Modal, Radio, Select, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { PlusOutlined, EditOutlined, DeleteOutlined, UserOutlined } from '@ant-design/icons'
import ReadUsers, { type ReadUsersHandle } from './ReadUsers'
import HeaderMessageDetail, { type HeaderMessageDetailHandle } from '@/layout/components/Navbar/HeaderMessageDetail'
import Editor from '@/components/Editor'
import Pagination from '@/components/Pagination'
import RightToolbar from '@/components/RightToolbar'
import Auth from '@/components/Auth'
import { listMessage, getMessage, delMessage, addMessage, updateMessage } from '@/api/system/message'
import { useEnumOption } from '@/hooks/useEnumOption'
import { buildPageParams } from '@/hooks/buildPageParams'
import modal from '@/utils/modal'
import type { Message, MessageQuery } from '@/types/api'
import type { EnumOption } from '@/types'

// --------------------------------- ref data ---------------------------------

/** 搜索栏：查询参数 */
interface MessageQueryState {
  pageNum: number
  pageSize: number
  category?: number
  status?: number
  title?: string
  [key: string]: unknown
}

/** 表格：UI数据 */
interface TableState {
  list: Message[]
  total: number
  loading: boolean
  showSearch: boolean
  ids: number[]
  single: boolean
  multiple: boolean
}

/** 编辑表单：数据状态 */
interface FormState {
  visible: boolean
  title: string
  form: Partial<Message>
}

export default function Message() {
  const messageViewRef = useRef<HeaderMessageDetailHandle>(null)
  const readUsersRef = useRef<ReadUsersHandle>(null)

  // 页面初始化：加载消息列表
  useEffect(() => {
    getList()
     
  }, [])

  // 筛选项数据：消息分类 + 消息状态
  const { MessageCategoryEnum: categoryOptions, MessageStatusEnum: statusOptions } = useEnumOption(
    'MessageCategoryEnum',
    'MessageStatusEnum'
  )

  // 搜索栏：查询参数
  const [queryParams, setQueryParams] = useState<MessageQueryState>({
    pageNum: 1,
    pageSize: 10,
    category: -1,
    status: -1,
    title: undefined
  })

  // 表格：UI数据
  const [table, setTable] = useState<TableState>({
    list: [],
    total: 0,
    loading: true,
    showSearch: true,
    ids: [],
    single: true,
    multiple: true
  })

  // 编辑表单：数据状态
  const [formState, setFormState] = useState<FormState>({
    visible: false,
    title: '',
    form: {}
  })

  // 表单实例
  const [searchForm] = Form.useForm()
  const [editForm] = Form.useForm()

  // --------------------------------- fun ---------------------------------

  /** 查询消息列表 */
  function getList() {
    setTable((prev) => ({ ...prev, loading: true }))
    const params = buildPageParams(queryParams)()
    listMessage(params).then((response) => {
      setTable((prev) => ({
        ...prev,
        list: response.data.data,
        total: response.data.total,
        loading: false
      }))
    })
  }

  /** 分类编码 → 文案 */
  function categoryText(category: number) {
    const item = categoryOptions.find((i) => i.code === category)
    return item ? item.title : category
  }

  /** 状态编码 → 文案 */
  function statusText(status: number) {
    const item = statusOptions.find((i) => i.code === status)
    return item ? item.title : status
  }

  /** 表单重置 */
  function reset() {
    setFormState((prev) => ({
      ...prev,
      form: {
        id: undefined,
        title: undefined,
        category: 0,
        content: undefined,
        status: 0
      }
    }))
    editForm.resetFields()
  }

  /** 搜索按钮操作 */
  function handleQuery() {
    setQueryParams((prev) => ({ ...prev, pageNum: 1 }))
    getList()
  }

  /** 重置按钮操作 */
  function resetQuery() {
    searchForm.resetFields()
    setQueryParams((prev) => ({
      ...prev,
      category: -1,
      status: -1,
      title: undefined,
      pageNum: 1
    }))
    handleQuery()
  }

  /** 多选框选中数据 */
  function handleSelectionChange(selectedRowKeys: React.Key[]) {
    const ids = selectedRowKeys.map((k) => Number(k))
    setTable((prev) => ({
      ...prev,
      ids,
      single: selectedRowKeys.length !== 1,
      multiple: !selectedRowKeys.length
    }))
  }

  /** 新增按钮操作 */
  function handleAdd() {
    reset()
    setFormState((prev) => ({ ...prev, visible: true, title: '新增站内消息' }))
  }

  /** 修改按钮操作 */
  function handleUpdate(row: any) {
    reset()
    // 顶部按钮点击传入的是事件对象而非行数据，此时取勾选 id
    const id = row?.id ?? table.ids[0]
    if (id == null) {
      return
    }
    getMessage(id).then((response) => {
      setFormState((prev) => ({ ...prev, form: response.data, visible: true, title: '修改站内消息' }))
    })
  }

  /** 提交按钮 */
  function submitForm() {
    editForm.validateFields().then(() => {
      // 已有 id 走更新，否则走新增
      if (formState.form.id !== undefined) {
        updateMessage(formState.form as Message).then(() => {
          modal.msgSuccess('修改成功')
          setFormState((prev) => ({ ...prev, visible: false }))
          getList()
        })
      } else {
        addMessage(formState.form as Message).then(() => {
          modal.msgSuccess('新增成功')
          setFormState((prev) => ({ ...prev, visible: false }))
          getList()
        })
      }
    })
  }

  /** 查看消息详情 */
  function handleViewData(row: Message) {
    messageViewRef.current?.open(row.id as number)
  }

  /** 查看已读用户 */
  function handleReadUsers(row: Message) {
    readUsersRef.current?.open(row)
  }

  /** 删除按钮操作 */
  function handleDelete(row: any) {
    const messageIds = row?.id ?? table.ids
    if (messageIds == null || (Array.isArray(messageIds) && messageIds.length === 0)) {
      return
    }
    modal
      .confirm('是否确认删除消息编号为"' + messageIds + '"的数据项？')
      .then(function () {
        return delMessage(messageIds)
      })
      .then(() => {
        getList()
        modal.msgSuccess('删除成功')
      })
      .catch(() => {})
  }

  // --------------------------------- 表格列 ---------------------------------

  const columns: ColumnsType<Message> = [
    { title: '序号', dataIndex: 'id', key: 'id', width: 100, align: 'center' },
    {
      title: '消息标题',
      key: 'title',
      align: 'center',
      ellipsis: true,
      render: (_v, row) => (
        <a className="link-type" style={{ cursor: 'pointer' }} onClick={() => handleViewData(row)}>
          {row.title}
        </a>
      )
    },
    {
      title: '分类',
      key: 'category',
      width: 100,
      align: 'center',
      render: (_v, row) => (
        <Tag color={row.category === 0 ? 'blue' : 'orange'}>{categoryText(Number(row.category))}</Tag>
      )
    },
    {
      title: '状态',
      key: 'status',
      width: 100,
      align: 'center',
      render: (_v, row) => (
        <Tag color={row.status === 0 ? 'green' : 'red'}>{statusText(Number(row.status))}</Tag>
      )
    },
    { title: '发送人', dataIndex: 'sender', align: 'center', width: 100 },
    {
      title: '发送时间',
      dataIndex: 'addTime',
      align: 'center',
      width: 170,
      render: (value: string) => <span>{value}</span>
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      width: 240,
      render: (_v, row) => (
        <Auth roles={['admin']}>
          <a style={{ marginRight: 8 }} onClick={() => handleReadUsers(row)}>
            <UserOutlined /> 阅读用户
          </a>
          <a style={{ marginRight: 8 }} onClick={() => handleUpdate(row)}>
            <EditOutlined /> 修改
          </a>
          <a onClick={() => handleDelete(row)}>
            <DeleteOutlined /> 删除
          </a>
        </Auth>
      )
    }
  ]

  return (
    <div className="app-container">
      {/* 搜索栏 */}
      <Form
        form={searchForm}
        layout="inline"
        style={{ display: table.showSearch ? 'flex' : 'none', marginBottom: 16, flexWrap: 'wrap', gap: '8px 0' }}
      >
        <Form.Item label="分类" name="category">
          <Select
            style={{ width: 200 }}
            placeholder="消息分类"
            allowClear
            value={queryParams.category}
            onChange={(v) => setQueryParams((prev) => ({ ...prev, category: v }))}
          >
            <Select.Option value={-1}>全部</Select.Option>
            {categoryOptions.map((item: EnumOption) => (
              <Select.Option key={item.code} value={item.code}>
                {item.title}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="状态" name="status">
          <Select
            style={{ width: 200 }}
            placeholder="消息状态"
            allowClear
            value={queryParams.status}
            onChange={(v) => setQueryParams((prev) => ({ ...prev, status: v }))}
          >
            <Select.Option value={-1}>全部</Select.Option>
            {statusOptions.map((item: EnumOption) => (
              <Select.Option key={item.code} value={item.code}>
                {item.title}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
        <Form.Item label="标题" name="title">
          <Input
            style={{ width: 200 }}
            placeholder="请输入标题"
            allowClear
            value={queryParams.title}
            onChange={(e) => setQueryParams((prev) => ({ ...prev, title: e.target.value }))}
            onPressEnter={handleQuery}
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" onClick={handleQuery}>
            搜索
          </Button>
          <Button style={{ marginLeft: 8 }} onClick={resetQuery}>
            重置
          </Button>
        </Form.Item>
      </Form>

      {/* 操作按钮 */}
      <div className="mb8" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <Auth roles={['admin']}>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            新增
          </Button>
          <Button icon={<EditOutlined />} disabled={table.single} onClick={handleUpdate}>
            修改
          </Button>
          <Button danger icon={<DeleteOutlined />} disabled={table.multiple} onClick={handleDelete}>
            删除
          </Button>
        </Auth>
        <div style={{ marginLeft: 'auto' }}>
          <RightToolbar showSearch={table.showSearch} onUpdateShowSearch={(v) => setTable((prev) => ({ ...prev, showSearch: v }))} onQueryTable={getList} />
        </div>
      </div>

      {/* 消息列表 */}
      <Table
        rowKey={(record) => String(record.id)}
        loading={table.loading}
        dataSource={table.list}
        columns={columns}
        rowSelection={{ onChange: handleSelectionChange }}
        pagination={false}
      />

      {/* 分页 */}
      <div style={{ display: table.total > 0 ? 'block' : 'none' }}>
        <Pagination
          total={table.total}
          page={queryParams.pageNum}
          limit={queryParams.pageSize}
          onPageChange={(v) => setQueryParams((prev) => ({ ...prev, pageNum: v }))}
          onLimitChange={(v) => setQueryParams((prev) => ({ ...prev, pageSize: v }))}
          onPagination={getList}
        />
      </div>

      {/* 添加或修改消息对话框 */}
      <Modal
        title={formState.title}
        open={formState.visible}
        width={780}
        onCancel={() => setFormState((prev) => ({ ...prev, visible: false }))}
        onOk={submitForm}
        okText="确 定"
        cancelText="取 消"
        destroyOnClose
      >
        <Form
          form={editForm}
          labelCol={{ span: 6 }}
          initialValues={formState.form}
          onValuesChange={(changed) => setFormState((prev) => ({ ...prev, form: { ...prev.form, ...changed } }))}
        >
          <Form.Item label="消息标题" name="title" rules={[{ required: true, message: '消息标题不能为空' }]}>
            <Input placeholder="请输入消息标题" />
          </Form.Item>
          <Form.Item label="分类" name="category" rules={[{ required: true, message: '分类不能为空' }]}>
            <Select placeholder="请选择">
              {categoryOptions.map((item: EnumOption) => (
                <Select.Option key={item.code} value={item.code}>
                  {item.title}
                </Select.Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item label="状态" name="status">
            <Radio.Group>
              {statusOptions.map((item: EnumOption) => (
                <Radio key={item.code} value={item.code}>
                  {item.title}
                </Radio>
              ))}
            </Radio.Group>
          </Form.Item>
          <Form.Item label="内容" name="content">
            <Editor minHeight={192} />
          </Form.Item>
        </Form>
      </Modal>
      <HeaderMessageDetail ref={messageViewRef} />
      <ReadUsers ref={readUsersRef} />
    </div>
  )
}
