// xxl-boot-ui/xxl-boot-ui-react/src/modules/framework/tool/pagegen/pages/CodeTypeDialog.tsx
/**
 * 组件：CodeTypeDialog（代码生成类型选择弹窗）
 * 功能：选择生成类型（页面/弹窗），导出时额外支持输入文件名
 */
import { App, Form, Input, Modal, Radio } from 'antd';
import React, { useEffect, useState } from 'react';
import { t } from '@/i18n';

/** 生成类型配置 */
const typeOptions = [
  { label: t('tool.pagegen.typeFile'), value: 'file' },
  { label: t('tool.pagegen.typeDialog'), value: 'dialog' },
];

/**
 * 生成类型选择弹窗
 * @param props.open        弹窗是否打开
 * @param props.onOpenChange 弹窗开关变化回调
 * @param props.showFileName 是否显示文件名输入（导出场景）
 * @param props.onConfirm    确认回调，参数为生成类型与文件名
 */
const CodeTypeDialog = ({
  open,
  onOpenChange,
  showFileName = false,
  onConfirm,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  showFileName?: boolean;
  onConfirm: (data: { type: string; fileName?: string }) => void;
}) => {
  const { message } = App.useApp();

  /* 生成类型选中值 */
  const [type, setType] = useState('file');
  /* 文件名 */
  const [fileName, setFileName] = useState('');

  /* 打开弹窗时重置表单，导出场景生成默认文件名 */
  useEffect(() => {
    if (open) {
      setType('file');
      setFileName(showFileName ? `${Date.now()}.tsx` : '');
    }
  }, [open, showFileName]);

  /** 关闭弹窗 */
  const handleClose = () => {
    onOpenChange(false);
  };

  /** 确认生成 */
  const handleConfirm = () => {
    if (showFileName && !fileName.trim()) {
      message.warning(t('common.inputPlaceholder', [t('tool.pagegen.fileName')]));
      return;
    }
    onConfirm({ type, fileName: fileName.trim() });
    onOpenChange(false);
  };

  return (
    <Modal
      title={t('tool.pagegen.selectGenType')}
      width={500}
      open={open}
      onCancel={handleClose}
      onOk={handleConfirm}
      okText={t('modal.confirmButton')}
      cancelText={t('modal.cancelButton')}
      destroyOnHidden
    >
      <Form layout="vertical" style={{ marginTop: 8 }}>
        <Form.Item label={t('tool.pagegen.genType')}>
          <Radio.Group
            value={type}
            onChange={(e) => setType(e.target.value)}
            options={typeOptions}
            optionType="button"
          />
        </Form.Item>
        {showFileName && (
          <Form.Item label={t('tool.pagegen.fileName')} required>
            <Input
              value={fileName}
              onChange={(e) => setFileName(e.target.value)}
              placeholder={t('common.inputPlaceholder', [t('tool.pagegen.fileName')])}
              allowClear
            />
          </Form.Item>
        )}
      </Form>
    </Modal>
  );
};

export default CodeTypeDialog;

// xxl-boot-ui/xxl-boot-ui-vue/src/modules/framework/tool/pagegen/pages/CodeTypeDialog.vue
<!--
  组件：代码生成类型选择弹窗
  功能：选择生成页面或弹窗类型，可输入文件名
-->
<template>
  <el-dialog v-model="open" width="500px" :title="t('tool.pagegen.selectGenType')" @open="onOpen" @close="onClose">
    <el-form ref="codeTypeForm" :model="formData" :rules="rules" label-width="100px">
      <!-- 生成类型选择 -->
      <el-form-item :label="t('tool.pagegen.genType')" prop="type">
        <el-radio-group v-model="formData.type">
          <el-radio-button v-for="(item, index) in typeOptions" :key="index" :label="item.value">
            {{ item.label }}
          </el-radio-button>
        </el-radio-group>
      </el-form-item>

      <!-- 文件名输入 -->
      <el-form-item v-if="showFileName" :label="t('tool.pagegen.fileName')" prop="fileName">
        <el-input v-model="formData.fileName" :placeholder="t('common.inputPlaceholder', [t('tool.pagegen.fileName')])" clearable />
      </el-form-item>
    </el-form>

    <!-- 弹窗底部按钮 -->
    <template #footer>
      <el-button type="primary" @click="handelConfirm">{{ t('modal.confirmButton') }}</el-button>
      <el-button @click="onClose">{{ t('modal.cancelButton') }}</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
/** 弹窗：显示状态 */
import { t } from '@/i18n'
import type { FormInstance } from 'element-plus'
import { ref } from 'vue'

const open = defineModel<boolean>()

// 组件属性
const props = defineProps({
  showFileName: Boolean /* 是否显示文件名输入 */
})

/**
 * 组件回调
 *
 * 组件事件：确认提交
 */
const emit = defineEmits(['confirm'])

// 响应式数据
const formData = ref<{
  fileName?: string /* 文件名 */
  type: string /* 生成类型 */
}>({
  fileName: undefined,
  type: 'file' /* 默认生成页面 */
})

// 表单 + 规则
const codeTypeForm = ref<FormInstance>() /* 表单 ref */
const rules = {
  fileName: [
    {
      required: true,
      message: t('common.inputPlaceholder', [t('tool.pagegen.fileName')]),
      trigger: 'blur'
    }
  ],
  type: [
    {
      required: true,
      message: t('common.requiredMsg', [t('tool.pagegen.genType')]),
      trigger: 'change'
    }
  ]
}

// 生成类型
const typeOptions = ref([
  { label: t('tool.pagegen.typePage'), value: 'file' },
  { label: t('tool.pagegen.typeDialog'), value: 'dialog' }
])

/** 弹窗打开：需要文件名时设置默认值 */
function onOpen() {
  if (props.showFileName) {
    formData.value.fileName = `${+new Date()}.vue`
  }
}

/** 弹窗关闭 */
function onClose() {
  open.value = false
}

/** 确认生成 */
function handelConfirm() {
  codeTypeForm.value!.validate((valid) => {
    if (!valid) return
    emit('confirm', { ...formData.value })
    onClose()
  })
}
</script>
