// xxl-boot-ui-vue/src/views/dashboard.vue
<!--
  页面：Dashboard（首页）
  功能：统计概览、日志趋势、最新消息
-->
<template>
  <div class="app-container dashboard">
    <!-- 第一排：指标卡片 -->
    <el-row :gutter="20">
      <el-col :xs="12" :sm="6" v-for="item in stats" :key="item.label">
        <el-card shadow="never" class="stat-card">
          <div class="stat-body">
            <div class="stat-icon-wrap" :style="{ background: item.bg }">
              <SvgIcon :icon-class="item.icon" class="stat-icon" :style="{ color: item.color }" />
            </div>
            <div class="stat-info">
              <span class="stat-value">{{ item.value }}</span>
              <span class="stat-label">{{ item.label }}</span>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 第二排：折线图 + 消息列表 -->
    <el-row :gutter="20" class="row-chart">
      <!-- 折线图 -->
      <el-col :xs="24" :lg="17">
        <el-card shadow="hover" class="chart-card">
          <template v-slot:header>
            <div class="card-header">
              <div class="card-header-left">
                <SvgIcon icon-class="chart" />
                <span>审计日志</span>
              </div>
              <el-radio-group v-model="chartDays" size="small" @change="loadChart">
                <el-radio-button :value="7">7天</el-radio-button>
                <el-radio-button :value="14">14天</el-radio-button>
                <el-radio-button :value="30">30天</el-radio-button>
              </el-radio-group>
            </div>
          </template>
          <div ref="chartRef" class="chart-box"></div>
        </el-card>
      </el-col>

      <!-- 消息列表 -->
      <el-col :xs="24" :lg="7">
        <el-card shadow="hover" class="msg-card">
          <template v-slot:header>
            <div class="card-header">
              <div class="card-header-left">
                <SvgIcon icon-class="list" />
                <span>站内消息</span>
              </div>
            </div>
          </template>
          <div v-if="messages.length === 0" class="msg-empty">暂无消息</div>
          <div v-else class="msg-list">
            <div v-for="item in messages" :key="item.id" class="msg-item" @click="handleMsgClick(item)">
              <div class="msg-title">{{ item.title }}</div>
              <div class="msg-meta">
                <el-tag size="small" :type="item.category === 1 ? 'warning' : 'success'">
                  {{ item.category === 1 ? '通知' : '公告' }}
                </el-tag>
                <span class="msg-time">{{ item.addTime }}</span>
              </div>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 消息详情 -->
    <MessageDetailView ref="messageDetailRef" />
  </div>
</template>

<script setup name="Index" lang="ts">
import { getStats, getLogTrend } from '@/api/dashboard'
import { listMessageTop, markMessageRead } from '@/api/system/message'
import { parseTime } from '@/utils/common'
import * as echarts from 'echarts'
import MessageDetailView from '@/layout/components/Navbar/HeaderMessageDetail.vue'
import type { ECharts } from 'echarts'
import type { Message } from '@/types/api'

/** 指标卡片项 */
interface StatItem {
  label: string
  value: number
  icon: string
  color: string
  bg: string
}

// 指标卡片
const stats = ref<StatItem[]>([
  { label: '用户数量', value: 0, icon: 'user', color: '#5b6abf', bg: '#eef0fb' },
  { label: '角色数量', value: 0, icon: 'peoples', color: '#319c8a', bg: '#e8f6f3' },
  { label: '日志数量', value: 0, icon: 'log', color: '#d4943c', bg: '#fcf4e8' },
  { label: '消息数量', value: 0, icon: 'message', color: '#c5566a', bg: '#fbeef1' }
])

const messages = ref<Message[]>([])
const chartRef = ref<HTMLElement>()
const chartDays = ref(30)
const messageDetailRef = ref<InstanceType<typeof MessageDetailView>>()
let chartInstance: ECharts | null = null

/**
 * init
 */
onMounted(() => {
  loadStats()
  loadMessages()
  nextTick(loadChart)
})

/**
 * destory
 */
onUnmounted(() => {
  chartInstance?.dispose()
})

/**
 * 指标卡片 - 数据加载
 */
function loadStats() {
  getStats().then((res) => {
    const data = res.data
    stats.value[0].value = data.userCount
    stats.value[1].value = data.roleCount
    stats.value[2].value = data.logCount
    stats.value[3].value = data.messageCount
  })
}

/**
 * 消息列表 - 数据加载
 */
function loadMessages() {
  listMessageTop().then((res) => {
    messages.value = res.data || []
  })
}

/**
 * 消息列表 - 点击查看详情，标记已读
 */
function handleMsgClick(item: Message) {
  messageDetailRef.value!.open(item.id as number)
  markMessageRead(item.id as number)
}

/**
 * 加载日志趋势折线图
 *
 * 1. 请求后端获取指定天数内的每日日志量
 * 2. 将返回的 [{date, count}] 转为 Map，便于按日期查找
 * 3. 生成完整的日期序列（从 days-1 天前 → 今天），
 *    无数据日期补 0，确保折线图连续不断点
 * 4. 初始化 ECharts 实例，配置折线图选项
 */
function loadChart() {
  const days = chartDays.value
  getLogTrend(days).then((res) => {
    // 后端返回 [{date: '2026-07-11', count: 3}, ...]
    const list = res.data || []

    // 1、转为 Map：date → count，方便按日期查找
    const dateMap: Record<string, number> = {}
    list.forEach((i) => {
      dateMap[i.date] = i.count
    })

    // 2、生成连续日期序列，每天对应一个数据点
    const dates: string[] = []
    const counts: number[] = []
    const now = new Date()
    for (let i = days - 1; i >= 0; i--) {
      // format day time
      const d = new Date(now)
      d.setDate(d.getDate() - i)
      const key = parseTime(d, '{y}-{m}-{d}')

      // write day date
      dates.push(key || '')
      counts.push(dateMap[key || ''] || 0) // 无数据日期补 0
    }

    // 3、渲染折线图（渐变面积 + 平滑曲线）
    if (chartInstance) {
      chartInstance.dispose()
    }
    chartInstance = echarts.init(chartRef.value as HTMLElement)
    chartInstance.setOption({
      tooltip: { trigger: 'axis' }, // 悬浮提示：轴触发
      grid: { left: 40, right: 20, bottom: 30, top: 20 }, // 图表边距
      // X轴：日期
      xAxis: {
        type: 'category',
        data: dates,
        axisLabel: { fontSize: 11, color: '#909399' } // X 轴标签样式
      },
      yAxis: {
        type: 'value',
        minInterval: 1, // Y 轴最小间隔为 1
        axisLabel: { fontSize: 11, color: '#909399' }
      },
      // X轴：数据
      series: [
        {
          data: counts,
          type: 'line',
          smooth: true, // 平滑曲线
          lineStyle: { width: 2, color: '#409EFF' }, // 折线样式
          areaStyle: {
            // 渐变面积填充
            color: {
              type: 'linear',
              x: 0,
              y: 0,
              x2: 0,
              y2: 1,
              colorStops: [
                { offset: 0, color: 'rgba(64,158,255,0.3)' }, // 顶部：30% 透明度
                { offset: 1, color: 'rgba(64,158,255,0.02)' } // 底部：2% 透明度
              ]
            }
          },
          itemStyle: { color: '#409EFF' } // 数据点颜色
        }
      ]
    })
  })
}
</script>

<style scoped lang="scss">
.stat-card {
  margin-bottom: 16px;
  border-radius: 8px;
  transition: box-shadow 0.2s;

  &:hover {
    box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
  }

  :deep(.el-card__body) {
    padding: 18px 20px;
  }
}

.stat-body {
  display: flex;
  align-items: center;
  gap: 14px;
}

.stat-icon-wrap {
  width: 50px;
  height: 50px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.stat-icon {
  width: 22px;
  height: 22px;
  flex-shrink: 0;
}

.stat-info {
  display: flex;
  flex-direction: column;
}

.stat-value {
  font-size: 26px;
  font-weight: 500;
  color: #1f2937;
  line-height: 1.2;
}

.stat-label {
  font-size: 13px;
  color: #909399;
  margin-top: 4px;
}

.row-chart {
  margin-top: 4px;
}

.chart-card,
.msg-card {
  margin-bottom: 20px;
  border-radius: 8px;
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 14px;
  font-weight: 600;
  color: #303133;
}

.card-header-left {
  display: flex;
  align-items: center;
  gap: 8px;
}

.chart-box {
  height: 320px;
  width: 100%;
}

.msg-empty {
  text-align: center;
  padding: 40px 0;
  color: #bbb;
  font-size: 13px;
}

.msg-list {
  display: flex;
  flex-direction: column;
  gap: 0;
}

.msg-item {
  padding: 12px 0;
  border-bottom: 1px solid #f0f0f0;
  cursor: pointer;

  &:last-child {
    border-bottom: none;
  }
}

.msg-title {
  font-size: 13px;
  color: #303133;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin-bottom: 6px;
}

.msg-meta {
  display: flex;
  align-items: center;
  gap: 8px;
}

.msg-time {
  font-size: 11px;
  color: #bbb;
}

html.dark {
  .stat-value {
    color: #e5e7eb;
  }

  .card-header {
    color: #e0e0e0;
  }

  .msg-title {
    color: #e0e0e0;
  }

  .msg-item {
    border-bottom-color: #2a2a3e;
  }
}
</style>

// xxl-boot-ui-react/src/views/dashboard.tsx
/**
 * 页面：Dashboard（首页）
 * 功能：统计概览、日志趋势、最新消息
 */
import { useEffect, useRef, useState } from 'react'
import { Card, Col, Row, Radio, Tag } from 'antd'
import * as echarts from 'echarts'
import type { ECharts } from 'echarts'
import SvgIcon from '@/components/SvgIcon'
import HeaderMessageDetail, { type HeaderMessageDetailHandle } from '@/layout/components/Navbar/HeaderMessageDetail'
import { getStats, getLogTrend } from '@/api/dashboard'
import { listMessageTop, markMessageRead } from '@/api/system/message'
import { parseTime } from '@/utils/common'
import type { Message } from '@/types/api'
import './dashboard.scss'

/** 指标卡片项 */
interface StatItem {
  label: string
  value: number
  icon: string
  color: string
  bg: string
}

export default function Dashboard() {
  // 指标卡片
  const [stats, setStats] = useState<StatItem[]>([
    { label: '用户数量', value: 0, icon: 'user', color: '#5b6abf', bg: '#eef0fb' },
    { label: '角色数量', value: 0, icon: 'peoples', color: '#319c8a', bg: '#e8f6f3' },
    { label: '日志数量', value: 0, icon: 'log', color: '#d4943c', bg: '#fcf4e8' },
    { label: '消息数量', value: 0, icon: 'message', color: '#c5566a', bg: '#fbeef1' }
  ])
  const [messages, setMessages] = useState<Message[]>([])
  const [chartDays, setChartDays] = useState(30)
  const chartRef = useRef<HTMLDivElement>(null)
  const messageDetailRef = useRef<HeaderMessageDetailHandle>(null)
  const chartInstanceRef = useRef<ECharts | null>(null)

  /**
   * 指标卡片 - 数据加载
   */
  const loadStats = () => {
    getStats().then((res) => {
      const data = res.data
      setStats((prev) => {
        const next = [...prev]
        next[0].value = data.userCount
        next[1].value = data.roleCount
        next[2].value = data.logCount
        next[3].value = data.messageCount
        return next
      })
    })
  }

  /**
   * 消息列表 - 数据加载
   */
  const loadMessages = () => {
    listMessageTop().then((res) => {
      setMessages(res.data || [])
    })
  }

  /**
   * 消息列表 - 点击查看详情，标记已读
   */
  const handleMsgClick = (item: Message) => {
    messageDetailRef.current?.open(item.id as number)
    markMessageRead(item.id as number)
  }

  /**
   * 加载日志趋势折线图
   */
  const loadChart = () => {
    const days = chartDays
    getLogTrend(days).then((res) => {
      const list = res.data || []

      // 1、转为 Map：date → count
      const dateMap: Record<string, number> = {}
      list.forEach((i: any) => {
        dateMap[i.date] = i.count
      })

      // 2、生成连续日期序列
      const dates: string[] = []
      const counts: number[] = []
      const now = new Date()
      for (let i = days - 1; i >= 0; i--) {
        const d = new Date(now)
        d.setDate(d.getDate() - i)
        const key = parseTime(d, '{y}-{m}-{d}') || ''
        dates.push(key)
        counts.push(dateMap[key] || 0)
      }

      // 3、渲染折线图（渐变面积 + 平滑曲线）
      if (chartInstanceRef.current) {
        chartInstanceRef.current.dispose()
      }
      if (!chartRef.current) return
      chartInstanceRef.current = echarts.init(chartRef.current)
      chartInstanceRef.current.setOption({
        tooltip: { trigger: 'axis' },
        grid: { left: 40, right: 20, bottom: 30, top: 20 },
        xAxis: {
          type: 'category',
          data: dates,
          axisLabel: { fontSize: 11, color: '#909399' }
        },
        yAxis: {
          type: 'value',
          minInterval: 1,
          axisLabel: { fontSize: 11, color: '#909399' }
        },
        series: [
          {
            data: counts,
            type: 'line',
            smooth: true,
            lineStyle: { width: 2, color: '#409EFF' },
            areaStyle: {
              color: {
                type: 'linear',
                x: 0,
                y: 0,
                x2: 0,
                y2: 1,
                colorStops: [
                  { offset: 0, color: 'rgba(64,158,255,0.3)' },
                  { offset: 1, color: 'rgba(64,158,255,0.02)' }
                ]
              }
            },
            itemStyle: { color: '#409EFF' }
          }
        ]
      })
    })
  }

  /**
   * init
   */
  useEffect(() => {
    loadStats()
    loadMessages()
    loadChart()
    return () => {
      chartInstanceRef.current?.dispose()
    }
     
  }, [])

  // 图表天数切换
  useEffect(() => {
    if (chartRef.current) {
      loadChart()
    }
     
  }, [chartDays])

  return (
    <div className="app-container dashboard">
      {/* 第一排：指标卡片 */}
      <Row gutter={20}>
        {stats.map((item) => (
          <Col xs={12} sm={6} key={item.label}>
            <Card className="stat-card" styles={{ body: { padding: '18px 20px' } }}>
              <div className="stat-body">
                <div className="stat-icon-wrap" style={{ background: item.bg }}>
                  <SvgIcon iconClass={item.icon} className="stat-icon" style={{ color: item.color }} />
                </div>
                <div className="stat-info">
                  <span className="stat-value">{item.value}</span>
                  <span className="stat-label">{item.label}</span>
                </div>
              </div>
            </Card>
          </Col>
        ))}
      </Row>

      {/* 第二排：折线图 + 消息列表 */}
      <Row gutter={20} className="row-chart">
        <Col xs={24} lg={17}>
          <Card
            className="chart-card"
            title={
              <div className="card-header">
                <div className="card-header-left">
                  <SvgIcon iconClass="chart" />
                  <span>审计日志</span>
                </div>
                <Radio.Group
                  size="small"
                  value={chartDays}
                  onChange={(e) => setChartDays(e.target.value)}
                  options={[
                    { label: '7天', value: 7 },
                    { label: '14天', value: 14 },
                    { label: '30天', value: 30 }
                  ]}
                />
              </div>
            }
          >
            <div ref={chartRef} className="chart-box" />
          </Card>
        </Col>

        {/* 消息列表 */}
        <Col xs={24} lg={7}>
          <Card
            className="msg-card"
            title={
              <div className="card-header">
                <div className="card-header-left">
                  <SvgIcon iconClass="list" />
                  <span>站内消息</span>
                </div>
              </div>
            }
          >
            {messages.length === 0 ? (
              <div className="msg-empty">暂无消息</div>
            ) : (
              <div className="msg-list">
                {messages.map((item) => (
                  <div key={item.id} className="msg-item" onClick={() => handleMsgClick(item)}>
                    <div className="msg-title">{item.title}</div>
                    <div className="msg-meta">
                      <Tag color={item.category === 1 ? 'orange' : 'green'} style={{ marginRight: 8 }}>
                        {item.category === 1 ? '通知' : '公告'}
                      </Tag>
                      <span className="msg-time">{item.addTime}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Card>
        </Col>
      </Row>

      {/* 消息详情 */}
      <HeaderMessageDetail ref={messageDetailRef} />
    </div>
  )
}
