// xxl-boot-ui/xxl-boot-ui-vue/src/views/authz/user/profile/index.vue
<!--
  页面：Profile（个人中心）
  功能：展示个人信息与基本资料/修改密码 tab 切换
-->
<template>
  <div class="app-container">
    <el-row :gutter="20">
      <el-col :span="6" :xs="24">
        <!-- 个人信息 -->
        <el-card class="box-card">
          <template v-slot:header>
            <div class="clearfix">
              <span>个人信息</span>
            </div>
          </template>

          <div>
            <!-- 用户信息列表 -->
            <ul class="list-group list-group-striped">
              <li class="list-group-item">
                <SvgIcon icon-class="user" />
                用户账号
                <div class="pull-right">{{ state.user.username }}</div>
              </li>
              <li class="list-group-item">
                <SvgIcon icon-class="phone" />
                手机号码
                <div class="pull-right">{{ state.user.phone }}</div>
              </li>
              <li class="list-group-item">
                <SvgIcon icon-class="email" />
                用户邮箱
                <div class="pull-right">{{ state.user.email }}</div>
              </li>
              <li class="list-group-item">
                <SvgIcon icon-class="tree" />
                所属部门
                <div class="pull-right">{{ state.user.orgName }}</div>
              </li>
              <li class="list-group-item">
                <SvgIcon icon-class="peoples" />
                所属角色
                <div class="pull-right">{{ state.roleNames }}</div>
              </li>
              <li class="list-group-item">
                <SvgIcon icon-class="date" />
                创建日期
                <div class="pull-right">{{ state.user.addTime }}</div>
              </li>
            </ul>
          </div>
        </el-card>
      </el-col>

      <!-- 基本资料 / 修改密码 -->
      <el-col :span="18" :xs="24">
        <el-card>
          <template v-slot:header>
            <div class="clearfix">
              <span>基本资料</span>
            </div>
          </template>
          <el-tabs v-model="selectedTab">
            <!-- 基本资料 -->
            <el-tab-pane label="基本资料" name="userinfo">
              <userInfo :user="state.user" />
            </el-tab-pane>

            <!-- 修改密码 -->
            <el-tab-pane label="修改密码" name="resetPwd">
              <resetPwd />
            </el-tab-pane>
          </el-tabs>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
defineOptions({ name: 'Profile' })
// 引入
import userInfo from './userInfo.vue'
import resetPwd from './resetPwd.vue'
import { getUserProfile } from '@/api/authz/user'
import type { User } from '@/types/api'
import { onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { SvgIcon } from '@/components'

const route = useRoute() // 路由
const selectedTab = ref('userinfo') // 当前选中的 tab
const state = reactive<{
  // 用户信息、角色数据
  user: User
  roleNames: string
}>({
  user: {}, // 用户信息
  roleNames: '' // 角色名称列表
})

/** 获取当前登录用户个人信息 */
function getUser() {
  getUserProfile().then((res) => {
    state.user = res.data
    state.roleNames = ((state.user.roleNames as string[]) || []).join(', ')
  })
}

// 初始化：根据路由参数激活 tab，并加载用户信息
onMounted(() => {
  const activeTab = route.params && route.params.activeTab
  if (activeTab) {
    selectedTab.value = activeTab as string
  }
  getUser()
})
</script>

// xxl-boot-ui-react/src/pages/account/profile/index.tsx
/**
 * 页面：Profile（个人中心）
 * 功能：展示个人信息与基本资料/修改密码 tab 切换
 */
import {
  CalendarOutlined,
  MailOutlined,
  PhoneOutlined,
  TeamOutlined,
  UserOutlined,
} from '@ant-design/icons';
import { PageContainer, ProCard } from '@ant-design/pro-components';
import { App, Card, Descriptions, Spin, Tabs } from 'antd';
import React, { useEffect, useState } from 'react';
import { getUserProfile } from '@/services/authz/user';
import ResetPwd from './ResetPwd';
import UserInfo from './UserInfo';

const Profile: React.FC = () => {
  const { message } = App.useApp();
  const [user, setUser] = useState<API.User>({});
  const [roleNames, setRoleNames] = useState('');
  const [loading, setLoading] = useState(false);

  /** 获取当前登录用户个人信息 */
  const loadUser = () => {
    setLoading(true);
    getUserProfile()
      .then((res) => {
        setUser(res.data || {});
        setRoleNames(((res.data?.roleNames as string[]) || []).join(', '));
      })
      .catch(() => {
        message.error('个人信息加载失败');
      })
      .finally(() => {
        setLoading(false);
      });
  };

  useEffect(() => {
    loadUser();
  }, []);

  return (
    <PageContainer ghost title={false}>
      <Spin spinning={loading}>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
          {/* 个人信息 */}
          <Card
            title="个人信息"
            style={{ width: 300, flexShrink: 0 }}
            styles={{ body: { paddingTop: 8 } }}
          >
            <Descriptions column={1} size="middle">
              <Descriptions.Item
                label={
                  <span>
                    <UserOutlined style={{ marginRight: 4 }} />
                    用户账号
                  </span>
                }
              >
                {user.username}
              </Descriptions.Item>
              <Descriptions.Item
                label={
                  <span>
                    <PhoneOutlined style={{ marginRight: 4 }} />
                    手机号码
                  </span>
                }
              >
                {user.phone || '-'}
              </Descriptions.Item>
              <Descriptions.Item
                label={
                  <span>
                    <MailOutlined style={{ marginRight: 4 }} />
                    用户邮箱
                  </span>
                }
              >
                {user.email || '-'}
              </Descriptions.Item>
              <Descriptions.Item
                label={
                  <span>
                    <TeamOutlined style={{ marginRight: 4 }} />
                    所属部门
                  </span>
                }
              >
                {user.orgName || '-'}
              </Descriptions.Item>
              <Descriptions.Item
                label={
                  <span>
                    <TeamOutlined style={{ marginRight: 4 }} />
                    所属角色
                  </span>
                }
              >
                {roleNames || '-'}
              </Descriptions.Item>
              <Descriptions.Item
                label={
                  <span>
                    <CalendarOutlined style={{ marginRight: 4 }} />
                    创建日期
                  </span>
                }
              >
                {user.addTime || '-'}
              </Descriptions.Item>
            </Descriptions>
          </Card>

          {/* 基本资料 / 修改密码 */}
          <ProCard
            style={{ flex: 1, minWidth: 420 }}
            styles={{ body: { paddingTop: 8 } }}
          >
            <Tabs
              defaultActiveKey="userinfo"
              items={[
                {
                  key: 'userinfo',
                  label: '基本资料',
                  children: <UserInfo user={user} onSuccess={loadUser} />,
                },
                {
                  key: 'resetPwd',
                  label: '修改密码',
                  children: <ResetPwd />,
                },
              ]}
            />
          </ProCard>
        </div>
      </Spin>
    </PageContainer>
  );
};

export default Profile;
