// xxl-boot-ui-react/src/layout/components/Navbar/SizeSelect.tsx
/**
 * 组件：SizeSelect（布局尺寸选择器）
 * 功能：顶部导航栏下拉菜单，切换 large / default / small 三种布局尺寸
 */
import { useState } from 'react'
import { Dropdown } from 'antd'
import type { MenuProps } from 'antd'
import { useAppStore } from '@/stores'
import modal from '@/utils/modal'
import SvgIcon from '@/components/SvgIcon'

/** 可选尺寸列表 */
const sizeOptions = [
  { label: '较大', value: 'large' },
  { label: '默认', value: 'default' },
  { label: '稍小', value: 'small' }
]

/**
 * 布局尺寸选择器
 */
export default function SizeSelect() {
  const appStore = useAppStore()
  const size = appStore.size

  /*
   * 切换布局尺寸：保存后刷新页面生效
   */
  const handleSetSize = (size: string) => {
    modal.loading('正在设置布局大小，请稍候...')
    appStore.setSize(size)
    setTimeout(function () {
      window.location.reload()
    }, 500)
  }

  const items: MenuProps['items'] = sizeOptions.map((item) => ({
    key: item.value,
    label: item.label,
    disabled: size === item.value
  }))

  return (
    <div>
      <Dropdown
        menu={{ items, onClick: ({ key }) => handleSetSize(key) }}
        trigger={['click']}
        placement="bottomRight"
      >
        <div className="size-icon--style">
          <SvgIcon iconClass="size" className="size-icon" />
        </div>
      </Dropdown>
    </div>
  )
}

// xxl-boot-ui/xxl-boot-ui-vue/src/layout/components/Navbar/SizeSelect.vue
<!--
  组件：SizeSelect（布局尺寸选择器）
  功能：顶部导航栏下拉菜单，切换 large / default / small 三种布局尺寸
-->
<template>
  <div>
    <el-dropdown trigger="click" @command="handleSetSize">
      <!-- icon -->
      <div class="size-icon--style">
        <SvgIcon class-name="size-icon" icon-class="size" />
      </div>
      <!-- 下拉菜单 -->
      <template #dropdown>
        <el-dropdown-menu>
          <!-- 当前选中项 disabled，不可再点击 -->
          <el-dropdown-item v-for="item of sizeOptions" :key="item.value" :disabled="size === item.value" :command="item.value">
            {{ item.label }}
          </el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>
  </div>
</template>

<script setup lang="ts">
import { useAppStore } from '@/store'
import modal from '@/utils/modal'
import { computed, ref } from 'vue'
import { SvgIcon } from '@/components'

const appStore = useAppStore()
const size = computed(() => appStore.size)
/* 可选尺寸列表 */
const sizeOptions = ref([
  { label: '较大', value: 'large' },
  { label: '默认', value: 'default' },
  { label: '稍小', value: 'small' }
])

/*
 * 切换布局尺寸：保存后刷新页面生效
 */
function handleSetSize(size: string) {
  modal.loading('正在设置布局大小，请稍候...')
  appStore.setSize(size)
  setTimeout(function () {
    window.location.reload()
  }, 500)
}
</script>

<style lang="scss" scoped>
.size-icon--style {
  font-size: 18px;
  line-height: 50px;
  padding-right: 7px;
}
</style>
