// xxl-boot-ui/src/views/org/user/index.vue
<!--
  User（用户管理）
  左侧组织结构，选中组织后传递该组织及全部子组织作为查询条件
-->
<template>
  <div class="app-container tree-sidebar-manage-wrap">
    <TreePanel title="组织机构" :tree-data="deptOptions" :tree-props="{ label: 'name', children: 'children' }" :filter-method="filterOrg" search-placeholder="请输入组织名称" storage-key="boot-user-org-sidebar-width" :defaultExpandAll="true" @node-click="handleNodeClick" @refresh="getDeptTree" ref="deptTreeRef" />
    <div class="tree-sidebar-content">
      <div class="content-inner">
        <!-- 搜索栏 -->
        <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="table.showSearch">
          <el-form-item label="用户名称" prop="username">
            <el-input v-model="queryParams.username" placeholder="请输入用户名称" clearable style="width: 200px" @keyup.enter="handleQuery" />
          </el-form-item>
          <el-form-item label="状态" prop="status">
            <el-select v-model="queryParams.status" placeholder="用户状态" clearable style="width: 200px">
              <el-option label="全部" :value="-1" />
              <el-option v-for="item in statusOptions" :key="item.code" :label="item.title" :value="item.code" />
            </el-select>
          </el-form-item>
          <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
          </el-form-item>
        </el-form>

        <!-- 操作按钮 -->
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['org:user']">新增</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button type="success" plain icon="Edit" :disabled="table.single" @click="handleUpdate" v-hasPermi="['org:user']">修改</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button type="danger" plain icon="Delete" :disabled="table.multiple" @click="handleDelete" v-hasPermi="['org:user']">删除</el-button>
          </el-col>
          <RightToolbar v-model:showSearch="table.showSearch" @queryTable="getList"></RightToolbar>
        </el-row>

        <!-- 用户列表 -->
        <el-table v-loading="table.loading" :data="table.list" @selection-change="handleSelectionChange">
          <el-table-column type="selection" width="45" align="center" />
          <el-table-column label="用户编号" align="center" prop="id" width="80" />
          <el-table-column label="账号" align="center" prop="username" width="110" :show-overflow-tooltip="true">
            <template #default="scope">
              <a class="link-type" style="cursor:pointer" @click="handleViewData(scope.row)">{{ scope.row.username }}</a>
            </template>
          </el-table-column>
          <el-table-column label="用户名称" align="center" prop="realName" width="110" :show-overflow-tooltip="true" />
          <el-table-column label="所属组织" align="center" prop="orgName" width="120" :show-overflow-tooltip="true" />
          <el-table-column label="状态" align="center" width="100">
            <template #default="scope">
              <el-switch
                v-model="scope.row.status"
                :active-value="0"
                :inactive-value="1"
                @change="handleStatusChange(scope.row)"
              ></el-switch>
            </template>
          </el-table-column>
          <el-table-column label="创建时间" align="center" width="170">
            <template #default="scope">
              <span>{{ parseTime(scope.row.addTime) }}</span>
            </template>
          </el-table-column>
          <el-table-column label="操作" align="center" width="190" class-name="small-padding fixed-width">
            <template #default="scope">
              <el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)" v-hasPermi="['org:user']">修改</el-button>
              <el-button link type="primary" icon="Delete" @click="handleDelete(scope.row)" v-hasPermi="['org:user']">删除</el-button>
              <el-dropdown trigger="click" @command="() => handleResetPwd(scope.row)">
                <el-button link type="primary" icon="DArrowRight">更多</el-button>
                <template #dropdown>
                  <el-dropdown-menu>
                    <el-dropdown-item icon="Key">重置密码</el-dropdown-item>
                  </el-dropdown-menu>
                </template>
              </el-dropdown>
            </template>
          </el-table-column>
        </el-table>

        <!-- 分页 -->
        <Pagination
          v-show="table.total > 0"
          :total="table.total"
          v-model:page="queryParams.pageNum"
          v-model:limit="queryParams.pageSize"
          @pagination="getList"
        />
      </div>
    </div>

    <!-- 添加或修改用户对话框 -->
    <el-dialog :title="formState.title" v-model="formState.visible" width="640px" append-to-body>
      <el-form ref="formRef" :model="formState.form" :rules="formState.rules" label-width="90px">
        <el-row>
          <el-col :span="12">
            <el-form-item label="账号" prop="username">
              <el-input v-model="formState.form.username" placeholder="请输入账号" maxlength="20" :disabled="formState.form.id !== undefined" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="密码" prop="password" :rules="formState.form.id === undefined ? passwordRules : []">
              <el-input v-model="formState.form.password" placeholder="请输入密码" type="password" maxlength="20" show-password :disabled="formState.form.id !== undefined" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="用户名称" prop="realName">
              <el-input v-model="formState.form.realName" placeholder="请输入用户名称" maxlength="50" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="角色">
              <el-select v-model="formState.form.roleIds" multiple placeholder="请选择角色" style="width: 100%">
                <el-option v-for="item in roleOptions" :key="item.id" :label="item.name" :value="item.id as number" :disabled="item.status == 1" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="归属组织" prop="orgId">
              <el-tree-select
                v-model="formState.form.orgId"
                :data="orgOptions"
                :props="{ label: 'name', children: 'children' }"
                value-key="id"
                placeholder="请选择归属组织"
                clearable
                check-strictly
              />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="formState.form.email" placeholder="请输入邮箱" maxlength="100" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="手机号" prop="phone">
              <el-input v-model="formState.form.phone" placeholder="请输入手机号" maxlength="20" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态">
              <el-radio-group v-model="formState.form.status">
                <el-radio v-for="item in statusOptions" :key="item.code" :value="item.code">{{ item.title }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>

    <!-- 用户详情抽屉 -->
    <UserViewDrawer ref="userViewRef" />
  </div>
</template>

<script setup name="User" lang="ts">
import UserViewDrawer from "./view.vue"
import { listUser, addUser, updateUser, delUser } from "@/api/org/user"
import { listRole } from "@/api/org/role"
import { listOrg } from "@/api/org/org"
import { useEnumOption } from "@/composables/useEnumOption"
import { useFormReset } from '@/composables/useFormReset'
import { handleTree, parseTime } from '@/utils/common'
import modal from '@/utils/modal'
import { ElMessageBox } from 'element-plus'
import type { User, Org, Role, UserQuery } from '@/types/api'
import type { EnumOption } from '@/types'
import type { FormInstance, FormItemRule, FormRules } from 'element-plus'

const resetForm = useFormReset()

/** 表格状态 */
interface TableState {
  list: User[]
  total: number
  loading: boolean
  showSearch: boolean
  ids: number[]
  single: boolean
  multiple: boolean
}

/** 编辑表单数据（User 基础上补充表单用到的附加字段） */
interface UserFormData extends User {
  phone?: string
  email?: string
  roleIds?: number[]
}

/** 编辑弹窗状态 */
interface FormState {
  visible: boolean
  title: string
  form: UserFormData
  rules: FormRules
}

// --------------------------------- ref data ---------------------------------

// 组件实例引用：模板 ref
const formRef = ref<FormInstance>()   /* 编辑表单 ref */
const deptTreeRef = ref<any>()        /* 左侧组织树 ref */
const userViewRef = ref<any>()        /* 用户详情抽屉 ref */

// 用户状态枚举选项（UserStatuEnum）
const { UserStatuEnum: statusOptions } = useEnumOption('UserStatuEnum')

// 角色选项（编辑表单角色多选）
const roleOptions = ref<Role[]>([])

// 组织树：左侧树形结构 + 编辑表单归属组织下拉树
const deptOptions = ref<Org[]>([])    /* 左侧组织树 */
const orgOptions = ref<Org[]>([])     /* 编辑表单归属组织下拉树 */

// 搜索栏：查询参数
const queryParams = ref<UserQuery>({
  pageNum: 1,          /* 当前页码 */
  pageSize: 10,        /* 每页条数 */
  username: undefined, /* 用户名称关键词 */
  status: -1,          /* 状态（-1 全部、0 正常、1 停用） */
  orgIds: []           /* 选中的组织及其全部子组织 ID 列表 */
})

// 表格：UI数据
const table = ref<TableState>({
  list: [],          /* 用户列表 */
  total: 0,          /* 总条数 */
  loading: true,     /* 加载状态 */
  showSearch: true,  /* 是否显示搜索栏 */
  ids: [],           /* 选中行 ID 数组 */
  single: true,      /* 是否单选 */
  multiple: true     /* 是否多选 */
})

// 编辑表单：数据状态
const formState = ref<FormState>({
  visible: false,  /* 对话框显隐 */
  title: "",       /* 对话框标题 */
  form: {},        /* 表单数据 */
  rules: {         /* 校验规则 */
    username: [
      { required: true, message: "账号不能为空", trigger: "blur" },
      { pattern: /^[a-z][a-z0-9]*$/, message: "格式：小写字母开头，字母/数字", trigger: "blur" }
    ],
    realName: [{ required: true, message: "用户名称不能为空", trigger: "blur" }],
    phone: [{ pattern: /^1[3|4|5|6|7|8|9][0-9]\d{8}$/, message: "手机号码格式不正确", trigger: "blur" }],
    email: [{ type: "email", message: "邮箱格式不正确", trigger: ["blur", "change"] }]
  }
})
// 密码校验规则（仅新增时生效，编辑时密码只读不校验）
const passwordRules: FormItemRule[] = [
  { required: true, message: "密码不能为空", trigger: "blur" },
  { min: 4, max: 20, message: "密码长度 4-20", trigger: "blur" }
]


// --------------------------------- fun ---------------------------------

/** 从后端枚举接口加载用户状态选项 */


/** 加载角色选项（用于编辑表单角色多选） */
function loadRoleOptions() {
  listRole({ offset: 0, pagesize: 999 }).then(response => {
    roleOptions.value = response.data.data
  })
}

/** 查询组织树列表 */
function getDeptTree() {
  listOrg({}).then(response => {
    // handleTree 会就地修改数组并填充 children，需对原始数据分别深拷贝，避免相互污染导致子节点重复
    deptOptions.value = handleTree(JSON.parse(JSON.stringify(response.data)), 'id')
    // 归属组织下拉树：默认追加「未选择」节点（id=0），对齐后端 org_id 默认值 0
    orgOptions.value = [
      { id: 0, name: '未选择', parentId: -1, children: [] },
      ...handleTree(JSON.parse(JSON.stringify(response.data)), 'id')
    ]
  })
}

/** 组织树节点过滤方法（字段为 name，非 TreePanel 默认的 label） */
function filterOrg(value: string, data: Org) {
  if (!value) return true
  return data.name && data.name.indexOf(value) !== -1
}

/** 递归收集节点及其全部子节点 ID */
function collectOrgIds(node: Org): number[] {
  const ids = [node.id as number]
  if (node.children && node.children.length) {
    node.children.forEach(child => {
      ids.push(...collectOrgIds(child))
    })
  }
  return ids
}

/** 节点单击事件：选中组织及其全部子组织作为查询条件 */
function handleNodeClick(data: Org) {
  queryParams.value.orgIds = collectOrgIds(data)
  handleQuery()
}

/** 查询用户列表 */
function getList() {
  table.value.loading = true
  // 前端分页参数 → 后端分页参数（offset/pagesize）
  const { pageNum, pageSize, orgIds, ...rest } = queryParams.value
  const params = {
    ...rest,
    orgIds: orgIds.join(',') || undefined,
    offset: (pageNum - 1) * pageSize,
    pagesize: pageSize
  }
  listUser(params).then(response => {
    table.value.list = response.data.data
    table.value.total = response.data.total
    table.value.loading = false
  })
}

/** 搜索按钮操作 */
function handleQuery() {
  queryParams.value.pageNum = 1
  getList()
}

/** 重置按钮操作 */
function resetQuery() {
  resetForm("queryRef")
  queryParams.value.orgIds = []
  deptTreeRef.value.setCurrentKey(null)
  handleQuery()
}

/** 多选框选中数据 */
function handleSelectionChange(selection: User[]) {
  table.value.ids = selection.map(item => item.id as number)
  table.value.single = selection.length !== 1
  table.value.multiple = !selection.length
}

/** 取消按钮 */
function cancel() {
  formState.value.visible = false
  reset()
}

/** 表单重置 */
function reset() {
  formState.value.form = {
    id: undefined,
    username: undefined,
    realName: undefined,
    orgId: 0,
    password: '123456',
    phone: undefined,
    email: undefined,
    status: 0,
    roleIds: []
  }
  resetForm("formRef")
}

/** 新增按钮操作 */
function handleAdd() {
  reset()
  getDeptTree()
  loadRoleOptions()
  formState.value.visible = true
  formState.value.title = "新增用户"
}

/** 修改按钮操作（顶部按钮 @click 传事件对象，需取勾选 id） */
function handleUpdate(row: any) {
  reset()
  getDeptTree()
  loadRoleOptions()
  // 顶部按钮点击传入的是事件对象而非行数据，此时取勾选 id
  const id = row && row.id != null ? row.id : table.value.ids[0]
  if (id == null) {
    return
  }
  const current = table.value.list.find(item => item.id === id)
  if (!current) {
    return
  }
  formState.value.form = { ...current }
  formState.value.visible = true
  formState.value.title = "修改用户"
}

/** 提交按钮 */
function submitForm() {
  formRef.value!.validate(valid => {
    if (valid) {
      // 后端 update 会自动维护 update_time，回传 addTime/updateTime 会导致 Date 绑定失败
      const submitData = { ...formState.value.form }
      delete submitData.addTime
      delete submitData.updateTime
      delete submitData.orgName
      delete submitData.roleNames
      submitData.orgId = submitData.orgId || 0

      // 已有 id 走更新，否则走新增
      if (formState.value.form.id !== undefined) {
        updateUser(submitData).then(() => {
          modal.msgSuccess("修改成功")
          formState.value.visible = false
          getList()
        })
      } else {
        addUser(submitData).then(() => {
          modal.msgSuccess("新增成功")
          formState.value.visible = false
          getList()
        })
      }
    }
  })
}

/** 删除按钮操作（顶部按钮 @click 传事件对象，需取勾选 ids） */
function handleDelete(row: any) {
  const userIds = row && row.id != null ? row.id : table.value.ids
  if (userIds == null || (Array.isArray(userIds) && userIds.length === 0)) {
    return
  }
  modal.confirm('是否确认删除用户编号为"' + userIds + '"的数据项？').then(function() {
    return delUser(userIds)
  }).then(() => {
    getList()
    modal.msgSuccess("删除成功")
  }).catch(() => {})
}

/** 重置密码按钮操作（通过 update 接口传递 id + password，需带上其余字段避免覆盖为空；密码校验与表单规则一致） */
function handleResetPwd(row: User) {
  ElMessageBox.prompt(`请输入「${row.username}」的新密码`, "重置密码", {
    confirmButtonText: "确定",
    cancelButtonText: "取消",
    closeOnClickModal: false,
    inputValidator: (value) => {
      if (!value) return "密码不能为空"
      if (value.length < 4 || value.length > 20) return "密码长度 4-20"
      return true
    }
  }).then(({ value }) => {
    const submitData: User = { ...row, password: value }
    delete submitData.addTime
    delete submitData.updateTime
    delete submitData.orgName
    delete submitData.roleNames
    updateUser(submitData).then(() => {
      modal.msgSuccess("修改成功，新密码是：" + value)
    })
  }).catch(() => {})
}

/** 用户状态快速切换（通过 update 接口传递完整行数据，避免其余字段被覆盖） */
function handleStatusChange(row: User) {
  const text = Number(row.status) === 0 ? "正常" : "停用"
  const submitData: User = { ...row, status: Number(row.status) }
  delete submitData.addTime
  delete submitData.updateTime
  delete submitData.orgName
  delete submitData.roleNames
  updateUser(submitData).then(() => {
    modal.msgSuccess(text + "成功")
  }).catch(() => {
    // 失败时回滚开关状态
    row.status = Number(row.status) === 0 ? 1 : 0
  })
}

/** 详情按钮操作（点击账号展示用户详情抽屉） */
function handleViewData(row: User) {
  userViewRef.value.open(row)
}


// --------------------------------- page init ---------------------------------

// 页面初始化：加载状态枚举、组织树与用户列表
getDeptTree()
getList()
</script>

<style scoped>
/* 操作列：下拉容器与相邻按钮垂直对齐，保持同一水平线 */
:deep(.el-dropdown) {
  vertical-align: middle;
}
</style>

// xxl-boot-ui-react/src/views/org/user/index.tsx
/**
 * 页面：User（用户管理）
 * 功能：左侧组织结构，选中组织后传递该组织及全部子组织作为查询条件；用户增删改查、重置密码、状态切换
 */
import { useEffect, useRef, useState } from 'react'
import { Button, Dropdown, Form, Input, InputNumber, Modal, Radio, Select, Switch, Table, TreeSelect } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  SearchOutlined,
  ReloadOutlined,
  DownOutlined,
  KeyOutlined
} from '@ant-design/icons'
import TreePanel, { type TreePanelHandle } from '@/components/TreePanel'
import RightToolbar from '@/components/RightToolbar'
import Auth from '@/components/Auth'
import Pagination from '@/components/Pagination'
import UserViewDrawer, { type UserViewHandle } from './view'
import { listUser, addUser, updateUser, delUser } from '@/api/org/user'
import { listRole } from '@/api/org/role'
import { listOrg } from '@/api/org/org'
import { useEnumOption } from '@/hooks/useEnumOption'
import { handleTree, parseTime } from '@/utils/common'
import modal from '@/utils/modal'
import type { User, Org, Role, UserQuery } from '@/types/api'

/** 编辑表单数据 */
interface UserFormData {
  id?: number
  username?: string
  realName?: string
  orgId?: number
  password?: string
  phone?: string
  email?: string
  status?: number
  roleIds?: number[]
  [key: string]: unknown
}

/** 表格状态 */
interface TableState {
  list: User[]
  total: number
  loading: boolean
  showSearch: boolean
  ids: number[]
  single: boolean
  multiple: boolean
}

export default function User() {
  const deptTreeRef = useRef<TreePanelHandle>(null)
  const userViewRef = useRef<UserViewHandle>(null)

  // 用户状态枚举选项
  const { UserStatuEnum: statusOptions } = useEnumOption('UserStatuEnum')

  // 角色选项
  const [roleOptions, setRoleOptions] = useState<Role[]>([])
  // 组织树
  const [deptOptions, setDeptOptions] = useState<Org[]>([])
  const [orgOptions, setOrgOptions] = useState<Org[]>([])

  // 搜索栏：查询参数
  const [queryParams, setQueryParams] = useState<{ [key: string]: unknown }>({
    pageNum: 1,
    pageSize: 10,
    username: undefined,
    status: -1,
    orgIds: []
  })

  // 表格：UI数据
  const [table, setTable] = useState<TableState>({
    list: [],
    total: 0,
    loading: true,
    showSearch: true,
    ids: [],
    single: true,
    multiple: true
  })

  // 编辑表单：数据状态
  const [formState, setFormState] = useState<{ visible: boolean; title: string; form: UserFormData }>({
    visible: false,
    title: '',
    form: {}
  })

  const [queryForm] = Form.useForm()
  const [editForm] = Form.useForm()

  // 页面初始化
  useEffect(() => {
    getDeptTree()
    getList()
     
  }, [])

  /** 加载角色选项 */
  function loadRoleOptions() {
    listRole({ offset: 0, pagesize: 999 } as any).then((response) => {
      setRoleOptions(response.data.data)
    })
  }

  /** 查询组织树列表 */
  function getDeptTree() {
    listOrg({}).then((response) => {
      setDeptOptions(handleTree(JSON.parse(JSON.stringify(response.data)), 'id'))
      setOrgOptions([
        { id: 0, name: '未选择', parentId: -1, children: [] },
        ...handleTree(JSON.parse(JSON.stringify(response.data)), 'id')
      ])
    })
  }

  /** 组织树节点过滤方法 */
  function filterOrg(value: string, data: any) {
    if (!value) return true
    return data.name && data.name.indexOf(value) !== -1
  }

  /** 递归收集节点及其全部子节点 ID */
  function collectOrgIds(node: Org): number[] {
    const ids = [node.id as number]
    if (node.children && node.children.length) {
      node.children.forEach((child) => {
        ids.push(...collectOrgIds(child))
      })
    }
    return ids
  }

  /** 节点单击事件 */
  function handleNodeClick(data: Org) {
    setQueryParams((prev) => ({ ...prev, orgIds: collectOrgIds(data) }))
    handleQuery()
  }

  /** 查询用户列表 */
  function getList() {
    setTable((prev) => ({ ...prev, loading: true }))
    const { pageNum, pageSize, orgIds, ...rest } = queryParams
    const params = {
      ...rest,
      orgIds: (orgIds as number[]).join(',') || undefined,
      offset: ((pageNum as number) - 1) * (pageSize as number),
      pagesize: pageSize
    }
    listUser(params as any).then((response) => {
      setTable((prev) => ({
        ...prev,
        list: response.data.data,
        total: response.data.total,
        loading: false
      }))
    })
  }

  /** 搜索按钮操作 */
  function handleQuery() {
    setQueryParams((prev) => ({ ...prev, pageNum: 1 }))
    getList()
  }

  /** 重置按钮操作 */
  function resetQuery() {
    queryForm.resetFields()
    setQueryParams((prev) => ({ ...prev, username: undefined, status: -1, orgIds: [], pageNum: 1 }))
    deptTreeRef.current?.setCurrentKey(null)
    handleQuery()
  }

  /** 多选框选中数据 */
  function handleSelectionChange(selectedRowKeys: React.Key[]) {
    const ids = selectedRowKeys.map((k) => Number(k))
    setTable((prev) => ({
      ...prev,
      ids,
      single: selectedRowKeys.length !== 1,
      multiple: !selectedRowKeys.length
    }))
  }

  /** 表单重置 */
  function reset() {
    setFormState((prev) => ({
      ...prev,
      form: { id: undefined, username: undefined, realName: undefined, orgId: 0, password: '123456', phone: undefined, email: undefined, status: 0, roleIds: [] }
    }))
    editForm.resetFields()
  }

  /** 新增按钮操作 */
  function handleAdd() {
    reset()
    getDeptTree()
    loadRoleOptions()
    setFormState((prev) => ({ ...prev, visible: true, title: '新增用户' }))
  }

  /** 修改按钮操作 */
  function handleUpdate(row: any) {
    reset()
    getDeptTree()
    loadRoleOptions()
    const id = row?.id ?? table.ids[0]
    if (id == null) {
      return
    }
    const current = table.list.find((item) => item.id === id)
    if (!current) {
      return
    }
    setFormState((prev) => ({ ...prev, form: { ...current }, visible: true, title: '修改用户' }))
  }

  /** 提交按钮 */
  function submitForm() {
    editForm.validateFields().then(() => {
      const submitData: any = { ...formState.form }
      delete submitData.addTime
      delete submitData.updateTime
      delete submitData.orgName
      delete submitData.roleNames
      submitData.orgId = submitData.orgId || 0

      if (formState.form.id !== undefined) {
        updateUser(submitData).then(() => {
          modal.msgSuccess('修改成功')
          setFormState((prev) => ({ ...prev, visible: false }))
          getList()
        })
      } else {
        addUser(submitData).then(() => {
          modal.msgSuccess('新增成功')
          setFormState((prev) => ({ ...prev, visible: false }))
          getList()
        })
      }
    })
  }

  /** 删除按钮操作 */
  function handleDelete(row: any) {
    const userIds = row?.id ?? table.ids
    if (userIds == null || (Array.isArray(userIds) && userIds.length === 0)) {
      return
    }
    modal
      .confirm('是否确认删除用户编号为"' + userIds + '"的数据项？')
      .then(function () {
        return delUser(userIds)
      })
      .then(() => {
        getList()
        modal.msgSuccess('删除成功')
      })
      .catch(() => {})
  }

  /** 重置密码按钮操作 */
  function handleResetPwd(row: User) {
    let inputValue = ''
    Modal.confirm({
      title: '重置密码',
      content: (
        <div>
          <div style={{ marginBottom: 8 }}>请输入「{row.username}」的新密码</div>
          <Input.Password placeholder="请输入新密码" onChange={(e) => (inputValue = e.target.value)} />
        </div>
      ),
      okText: '确定',
      cancelText: '取消',
      centered: true,
      onOk: () => {
        if (!inputValue) {
          modal.msgError('密码不能为空')
          return Promise.reject()
        }
        if (inputValue.length < 4 || inputValue.length > 20) {
          modal.msgError('密码长度 4-20')
          return Promise.reject()
        }
        const submitData: any = { ...row, password: inputValue }
        delete submitData.addTime
        delete submitData.updateTime
        delete submitData.orgName
        delete submitData.roleNames
        return updateUser(submitData).then(() => {
          modal.msgSuccess('修改成功，新密码是：' + inputValue)
        })
      }
    })
  }

  /** 用户状态快速切换 */
  function handleStatusChange(row: User) {
    const text = Number(row.status) === 0 ? '正常' : '停用'
    const submitData: any = { ...row, status: Number(row.status) }
    delete submitData.addTime
    delete submitData.updateTime
    delete submitData.orgName
    delete submitData.roleNames
    updateUser(submitData)
      .then(() => {
        modal.msgSuccess(text + '成功')
      })
      .catch(() => {
        // 失败时回滚开关状态
        row.status = Number(row.status) === 0 ? 1 : 0
        setTable((prev) => ({ ...prev }))
      })
  }

  /** 详情按钮操作 */
  function handleViewData(row: User) {
    userViewRef.current?.open(row)
  }

  const columns: ColumnsType<User> = [
    { title: '用户编号', dataIndex: 'id', align: 'center', width: 80 },
    {
      title: '账号',
      dataIndex: 'username',
      align: 'center',
      width: 110,
      ellipsis: true,
      render: (_v, row) => (
        <a className="link-type" style={{ cursor: 'pointer' }} onClick={() => handleViewData(row)}>
          {row.username}
        </a>
      )
    },
    { title: '用户名称', dataIndex: 'realName', align: 'center', width: 110, ellipsis: true },
    { title: '所属组织', dataIndex: 'orgName', align: 'center', width: 120, ellipsis: true },
    {
      title: '状态',
      key: 'status',
      width: 100,
      align: 'center',
      render: (_v, row) => (
        <Switch
          size="small"
          checkedChildren="正常"
          unCheckedChildren="停用"
          checked={row.status === 0}
          onChange={() => {
            row.status = Number(row.status) === 0 ? 1 : 0
            setTable((prev) => ({ ...prev }))
            handleStatusChange(row)
          }}
        />
      )
    },
    {
      title: '创建时间',
      dataIndex: 'addTime',
      align: 'center',
      width: 170,
      render: (value: string) => <span>{parseTime(value)}</span>
    },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      width: 190,
      render: (_v, row) => (
        <Auth perms={['org:user']}>
          <a style={{ marginRight: 8 }} onClick={() => handleUpdate(row)}>
            <EditOutlined /> 修改
          </a>
          <a style={{ marginRight: 8 }} onClick={() => handleDelete(row)}>
            <DeleteOutlined /> 删除
          </a>
          <Dropdown
            menu={{
              items: [{ key: 'resetPwd', label: <span><KeyOutlined /> 重置密码</span> }],
              onClick: () => handleResetPwd(row)
            }}
            trigger={['click']}
          >
            <a onClick={(e) => e.preventDefault()}>
              更多 <DownOutlined style={{ fontSize: 12 }} />
            </a>
          </Dropdown>
        </Auth>
      )
    }
  ]

  // 组织树 TreeSelect 数据
  const orgTreeData = (list: Org[]): any[] =>
    list.map((item) => ({
      value: item.id,
      title: item.name,
      children: item.children && item.children.length ? orgTreeData(item.children) : undefined
    }))

  return (
    <div className="app-container tree-sidebar-manage-wrap">
      {/* 左侧组织树 */}
      <TreePanel
        title="组织机构"
        treeData={deptOptions}
        treeProps={{ label: 'name', children: 'children' }}
        filterMethod={filterOrg}
        searchPlaceholder="请输入组织名称"
        storageKey="boot-user-org-sidebar-width"
        defaultExpandAll
        onNodeClick={handleNodeClick}
        onRefresh={getDeptTree}
        ref={deptTreeRef}
      />

      <div className="tree-sidebar-content">
        <div className="content-inner">
          {/* 搜索栏 */}
          <Form form={queryForm} layout="inline" style={{ display: table.showSearch ? 'flex' : 'none', marginBottom: 16, flexWrap: 'wrap' }}>
            <Form.Item label="用户名称" name="username">
              <Input
                style={{ width: 200 }}
                placeholder="请输入用户名称"
                allowClear
                value={queryParams.username as string}
                onChange={(e) => setQueryParams((prev) => ({ ...prev, username: e.target.value }))}
                onPressEnter={handleQuery}
              />
            </Form.Item>
            <Form.Item label="状态" name="status">
              <Select
                style={{ width: 200 }}
                placeholder="用户状态"
                allowClear
                value={queryParams.status}
                onChange={(v) => setQueryParams((prev) => ({ ...prev, status: v }))}
              >
                <Select.Option value={-1}>全部</Select.Option>
                {statusOptions.map((item) => (
                  <Select.Option key={item.code} value={item.code}>
                    {item.title}
                  </Select.Option>
                ))}
              </Select>
            </Form.Item>
            <Form.Item>
              <Button type="primary" icon={<SearchOutlined />} onClick={handleQuery}>
                搜索
              </Button>
              <Button style={{ marginLeft: 8 }} icon={<ReloadOutlined />} onClick={resetQuery}>
                重置
              </Button>
            </Form.Item>
          </Form>

          {/* 操作按钮 */}
          <div className="mb8" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Auth perms={['org:user']}>
              <Button icon={<PlusOutlined />} onClick={handleAdd}>
                新增
              </Button>
              <Button icon={<EditOutlined />} disabled={table.single} onClick={handleUpdate}>
                修改
              </Button>
              <Button danger icon={<DeleteOutlined />} disabled={table.multiple} onClick={handleDelete}>
                删除
              </Button>
            </Auth>
            <div style={{ marginLeft: 'auto' }}>
              <RightToolbar showSearch={table.showSearch} onUpdateShowSearch={(v) => setTable((prev) => ({ ...prev, showSearch: v }))} onQueryTable={getList} />
            </div>
          </div>

          {/* 用户列表 */}
          <Table
            rowKey={(record) => String(record.id)}
            loading={table.loading}
            dataSource={table.list}
            columns={columns}
            rowSelection={{ onChange: handleSelectionChange }}
            pagination={false}
          />

          {/* 分页 */}
          <div style={{ display: table.total > 0 ? 'block' : 'none' }}>
            <Pagination
              total={table.total}
              page={queryParams.pageNum as number}
              limit={queryParams.pageSize as number}
              onPageChange={(v) => setQueryParams((prev) => ({ ...prev, pageNum: v }))}
              onLimitChange={(v) => setQueryParams((prev) => ({ ...prev, pageSize: v }))}
              onPagination={getList}
            />
          </div>
        </div>
      </div>

      {/* 添加或修改用户对话框 */}
      <Modal
        title={formState.title}
        open={formState.visible}
        width={640}
        onCancel={() => setFormState((prev) => ({ ...prev, visible: false }))}
        onOk={submitForm}
        okText="确 定"
        cancelText="取 消"
        destroyOnClose
      >
        <Form
          form={editForm}
          labelCol={{ span: 6 }}
          initialValues={formState.form}
          onValuesChange={(changed) => setFormState((prev) => ({ ...prev, form: { ...prev.form, ...changed } }))}
        >
          <Form.Item label="账号" name="username" rules={[{ required: true, message: '账号不能为空' }, { pattern: /^[a-z][a-z0-9]*$/, message: '格式：小写字母开头，字母/数字' }]}>
            <Input placeholder="请输入账号" maxLength={20} disabled={formState.form.id !== undefined} />
          </Form.Item>
          <Form.Item
            label="密码"
            name="password"
            rules={formState.form.id === undefined ? [{ required: true, message: '密码不能为空' }, { min: 4, max: 20, message: '密码长度 4-20' }] : []}
          >
            <Input.Password placeholder="请输入密码" maxLength={20} disabled={formState.form.id !== undefined} />
          </Form.Item>
          <Form.Item label="用户名称" name="realName" rules={[{ required: true, message: '用户名称不能为空' }]}>
            <Input placeholder="请输入用户名称" maxLength={50} />
          </Form.Item>
          <Form.Item label="角色" name="roleIds">
            <Select mode="multiple" placeholder="请选择角色" value={formState.form.roleIds}>
              {roleOptions.map((item) => (
                <Select.Option key={item.id} value={item.id} disabled={item.status === 1}>
                  {item.name}
                </Select.Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item label="归属组织" name="orgId">
            <TreeSelect
              treeData={orgTreeData(orgOptions)}
              placeholder="请选择归属组织"
              allowClear
              treeDefaultExpandAll
              value={formState.form.orgId}
              onChange={(v) => setFormState((prev) => ({ ...prev, form: { ...prev.form, orgId: v } }))}
            />
          </Form.Item>
          <Form.Item label="邮箱" name="email" rules={[{ type: 'email', message: '邮箱格式不正确' }]}>
            <Input placeholder="请输入邮箱" maxLength={100} />
          </Form.Item>
          <Form.Item label="手机号" name="phone" rules={[{ pattern: /^1[3|4|5|6|7|8|9][0-9]\d{8}$/, message: '手机号码格式不正确' }]}>
            <Input placeholder="请输入手机号" maxLength={20} />
          </Form.Item>
          <Form.Item label="状态" name="status">
            <Radio.Group>
              {statusOptions.map((item) => (
                <Radio key={item.code} value={item.code}>
                  {item.title}
                </Radio>
              ))}
            </Radio.Group>
          </Form.Item>
        </Form>
      </Modal>

      {/* 用户详情抽屉 */}
      <UserViewDrawer ref={userViewRef} />
    </div>
  )
}
