// xxl-boot-ui/src/views/org/user/view.vue
<!--
  UserView（用户详情抽屉）
  展示用户基本信息、角色信息及账号相关数据
-->
<template>
  <el-drawer
    title="用户详情"
    v-model="visible"
    direction="rtl"
    size="680px"
    append-to-body
    :before-close="handleClose"
    class="detail-drawer"
  >
    <div v-loading="loading" class="drawer-content">
      <!-- 基本信息 -->
      <h4 class="section-header">基本信息</h4>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">用户编号：</label>
            <span class="info-value plaintext">{{ info.id }}</span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">账号：</label>
            <span class="info-value plaintext">{{ info.username }}</span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">用户名称：</label>
            <span class="info-value plaintext">{{ info.realName }}</span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">所属组织：</label>
            <span class="info-value plaintext">{{ info.orgName }}</span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">手机号：</label>
            <span class="info-value plaintext">{{ info.phone }}</span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">邮箱：</label>
            <span class="info-value plaintext">{{ info.email }}</span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">用户状态：</label>
            <span class="info-value plaintext">
              <el-tag size="small" :type="info.status === 0 ? 'success' : 'danger'">{{ statusText(info.status) }}</el-tag>
            </span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">角色：</label>
            <span class="info-value plaintext">{{ roleNames || '无角色' }}</span>
          </div>
        </el-col>
      </el-row>
      <!-- 其他信息 -->
      <h4 class="section-header">其他信息</h4>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">创建时间：</label>
            <span class="info-value plaintext">{{ parseTime(info.addTime as string) }}</span>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="20" class="mb8">
        <el-col :span="24">
          <div class="info-item">
            <label class="info-label">更新时间：</label>
            <span class="info-value plaintext">{{ parseTime(info.updateTime as string) }}</span>
          </div>
        </el-col>
      </el-row>
    </div>
  </el-drawer>
</template>

<script setup name="UserView" lang="ts">
import { listRole } from '@/api/org/role'
import { loadEnumItem } from '@/api/system/dict/data'
import { parseTime } from '@/utils/common'
import type { User, Role } from '@/types/api'
import type { EnumOption } from '@/types'

const visible = ref(false)
const loading = ref(false)
const info = ref<User>({})
const statusOptions = ref<EnumOption[]>([])
const roleOptions = ref<Role[]>([])

const roleNames = computed(() => {
  const roleIds = info.value.roleIds as number[] | undefined
  if (!roleIds || !roleIds.length) return ''
  return (
    roleOptions.value
      .filter((r) => roleIds.includes(r.id as number))
      .map((r) => r.name)
      .join('、') || ''
  )
})

/** 状态编码 → 文案 */
function statusText(status?: number) {
  const item = statusOptions.value.find((i) => i.code === status)
  return item ? item.title : status
}

/** 打开详情抽屉 */
function open(row: User) {
  visible.value = true
  loading.value = true
  info.value = { ...row }
  listRole({ offset: 0, pagesize: 999 }).then((response) => {
    roleOptions.value = response.data.data
  })
  loadEnumItem('UserStatuEnum')
    .then((res) => {
      statusOptions.value = res.data
    })
    .finally(() => {
      loading.value = false
    })
}

/** 关闭详情抽屉 */
function handleClose() {
  visible.value = false
}

defineExpose({
  open
})
</script>

// xxl-boot-ui-react/src/views/org/user/view.tsx
/**
 * 组件：UserView（用户详情抽屉）
 * 功能：展示用户基本信息、角色信息及账号相关数据
 */
import { forwardRef, useImperativeHandle, useState } from 'react'
import { Drawer, Spin, Tag } from 'antd'
import { listRole } from '@/api/org/role'
import { loadEnumItem } from '@/api/system/dict/data'
import { parseTime } from '@/utils/common'
import type { User, Role } from '@/types/api'
import type { EnumOption } from '@/types'

export interface UserViewHandle {
  /** 打开详情抽屉 */
  open: (row: User) => void
}

/**
 * 用户详情抽屉
 */
const UserView = forwardRef<UserViewHandle>(function UserView(_, ref) {
  const [visible, setVisible] = useState(false)
  const [loading, setLoading] = useState(false)
  const [info, setInfo] = useState<User>({})
  const [statusOptions, setStatusOptions] = useState<EnumOption[]>([])
  const [roleOptions, setRoleOptions] = useState<Role[]>([])

  const roleNames = (() => {
    const roleIds = info.roleIds as number[] | undefined
    if (!roleIds || !roleIds.length) return ''
    return (
      roleOptions
        .filter((r) => roleIds.includes(r.id as number))
        .map((r) => r.name)
        .join('、') || ''
    )
  })()

  /** 状态编码 → 文案 */
  function statusText(status?: number) {
    const item = statusOptions.find((i) => i.code === status)
    return item ? item.title : status
  }

  /** 打开详情抽屉 */
  function open(row: User) {
    setVisible(true)
    setLoading(true)
    setInfo({ ...row })
    listRole({ offset: 0, pagesize: 999 } as any).then((response) => {
      setRoleOptions(response.data.data)
    })
    loadEnumItem('UserStatuEnum')
      .then((res) => {
        setStatusOptions(res.data)
      })
      .finally(() => {
        setLoading(false)
      })
  }

  /** 关闭详情抽屉 */
  function handleClose() {
    setVisible(false)
  }

  useImperativeHandle(ref, () => ({ open }))

  return (
    <Drawer title="用户详情" open={visible} width={680} onClose={handleClose} className="detail-drawer">
      <Spin spinning={loading}>
        <div className="drawer-content">
          {/* 基本信息 */}
          <h4 className="section-header">基本信息</h4>
          <div className="info-item">
            <label className="info-label">用户编号：</label>
            <span className="info-value plaintext">{info.id}</span>
          </div>
          <div className="info-item">
            <label className="info-label">账号：</label>
            <span className="info-value plaintext">{String(info.username ?? "")}</span>
          </div>
          <div className="info-item">
            <label className="info-label">用户名称：</label>
            <span className="info-value plaintext">{String(info.realName ?? "")}</span>
          </div>
          <div className="info-item">
            <label className="info-label">所属组织：</label>
            <span className="info-value plaintext">{String(info.orgName ?? "")}</span>
          </div>
          <div className="info-item">
            <label className="info-label">手机号：</label>
            <span className="info-value plaintext">{String(info.phone ?? "")}</span>
          </div>
          <div className="info-item">
            <label className="info-label">邮箱：</label>
            <span className="info-value plaintext">{String(info.email ?? "")}</span>
          </div>
          <div className="info-item">
            <label className="info-label">用户状态：</label>
            <span className="info-value plaintext">
              <Tag color={info.status === 0 ? 'green' : 'red'}>{statusText(Number(info.status))}</Tag>
            </span>
          </div>
          <div className="info-item">
            <label className="info-label">角色：</label>
            <span className="info-value plaintext">{roleNames || '无角色'}</span>
          </div>
          {/* 其他信息 */}
          <h4 className="section-header">其他信息</h4>
          <div className="info-item">
            <label className="info-label">创建时间：</label>
            <span className="info-value plaintext">{parseTime(info.addTime as string)}</span>
          </div>
          <div className="info-item">
            <label className="info-label">更新时间：</label>
            <span className="info-value plaintext">{parseTime(info.updateTime as string)}</span>
          </div>
        </div>
      </Spin>
    </Drawer>
  )
})

UserView.displayName = 'UserView'
export default UserView
