// xxl-boot-ui-vue/src/layout/index.vue
<!--
  Layout：布局主框架
  功能：整体页面骨架，组合侧边栏/顶部导航/标签页/主内容区/设置面板，
        处理桌面端与移动端布局切换、侧边栏收展联动、主题变量注入
-->
<template>
  <div
    :class="classObj"
    class="app-wrapper"
    :style="{
      '--current-color': theme,
      '--current-color-light': theme + '1a',
      '--current-color-dark-bg': theme + '33'
    }"
  >
    <!-- 移动端遮罩：侧栏展开时显示，点击关闭侧栏 -->
    <div v-if="device === 'mobile' && sidebar.opened" class="drawer-bg" @click="handleClickOutside" />

    <!-- 侧边栏（左侧） -->
    <Sidebar v-if="!sidebar.hide" class="sidebar-container" />

    <!-- 主内容区（中间） -->
    <div :class="{ hasTagsView: needTagsView, sidebarHide: sidebar.hide }" class="main-container">
      <!-- 固定头部（中间：顶部）：含导航栏和标签页 -->
      <div :class="{ 'fixed-header': fixedHeader }">
        <!-- 导航栏：含面包屑/菜单搜索/用户菜单等 -->
        <Navbar @setLayout="setLayout" />
        <!-- 多标签页 -->
        <TagsView v-if="needTagsView" />
      </div>

      <!-- 路由页面出口（中间：主内容区） -->
      <AppMain />

      <!-- 布局设置面板（中间：右侧边栏） -->
      <Settings ref="settingRef" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useWindowSize } from '@vueuse/core'
import { AppMain, Navbar, Settings, TagsView, Sidebar } from './components'
import { useAppStore, useSettingsStore } from '@/store'
import { computed, ref, watch } from 'vue'

const settingsStore = useSettingsStore()
const appStore = useAppStore()
const theme = computed(() => settingsStore.theme)
const sidebar = computed(() => appStore.sidebar)
const device = computed(() => appStore.device)
const needTagsView = computed(() => settingsStore.tagsView)
const fixedHeader = computed(() => settingsStore.fixedHeader)

/*
 * 布局 CSS 类名组合：侧栏收展状态 + 设备类型
 */
const classObj = computed(() => ({
  hideSidebar: !sidebar.value.opened,
  openSidebar: sidebar.value.opened,
  withoutAnimation: sidebar.value.withoutAnimation,
  mobile: device.value === 'mobile'
}))

const { width, height } = useWindowSize()
const WIDTH = 992 // refer to Bootstrap's responsive design

/*
 * 设备切换：切换到 mobile 时收起侧栏
 */
watch(
  () => device.value,
  () => {
    if (device.value === 'mobile' && sidebar.value.opened) {
      appStore.closeSideBar({ withoutAnimation: false })
    }
  }
)

/*
 * 窗口响应式：宽度 < 992 切换 mobile，无动画收起侧栏
 * 桌面端加载时尊重侧栏的持久化状态，不自动展开
 */
if (width.value - 1 < WIDTH) {
  appStore.toggleDevice('mobile')
  appStore.closeSideBar({ withoutAnimation: true })
}

watch(width, (newVal, oldVal) => {
  if (newVal - 1 < WIDTH && oldVal >= WIDTH) {
    appStore.toggleDevice('mobile')
    appStore.closeSideBar({ withoutAnimation: true })
  } else if (newVal - 1 >= WIDTH && oldVal < WIDTH) {
    appStore.toggleDevice('desktop')
    appStore.openSideBar({ withoutAnimation: true })
  }
})

/*
 * 移动端遮罩点击 -> 关闭侧栏
 */
function handleClickOutside() {
  appStore.closeSideBar({ withoutAnimation: false })
}

const settingRef = ref<InstanceType<typeof Settings> | null>(null)
/*
 * 打开布局设置面板
 */
function setLayout() {
  settingRef.value?.openSetting()
}
</script>

<!-- 组件私有样式 -->
<style lang="scss" scoped>
@use '@/assets/styles/variables.module.scss' as vars;

.app-wrapper {
  &:after {
    content: '';
    display: table;
    clear: both;
  }
  position: relative;
  height: 100%;
  width: 100%;

  &.mobile.openSidebar {
    position: fixed;
    top: 0;
  }
}

.main-container:has(.fixed-header) {
  height: 100vh;
  overflow: hidden;
}

.drawer-bg {
  background: #000;
  opacity: 0.3;
  width: 100%;
  top: 0;
  height: 100%;
  position: absolute;
  z-index: 999;
}

.fixed-header {
  position: fixed;
  top: 0;
  right: 0;
  z-index: 9;
  width: calc(100% - #{vars.$base-sidebar-width});
  transition: width 0.28s;
}

.hideSidebar .fixed-header {
  width: calc(100% - 54px);
}

.sidebarHide .fixed-header {
  width: 100%;
}

.mobile .fixed-header {
  width: 100%;
}
</style>

<!--
  布局组件专属样式：需要影响全局/子组件的样式
-->
<style lang="scss">
@use '@/assets/styles/variables.module.scss' as vars;

#app {
  .main-container {
    min-height: 100%;
    transition: margin-left 0.28s;
    margin-left: vars.$base-sidebar-width;
    position: relative;
  }

  .sidebarHide {
    margin-left: 0 !important;
  }

  .sidebar-container {
    transition: width 0.28s;
    width: vars.$base-sidebar-width !important;
    height: 100%;
    position: fixed;
    font-size: 0px;
    top: 0;
    bottom: 0;
    left: 0;
    z-index: 1001;
    overflow: hidden;
    -webkit-box-shadow: 2px 0 6px rgba(0, 21, 41, 0.35);
    box-shadow: 0px 0px 8px 0px rgba(0, 0, 0, 0.1);

    .horizontal-collapse-transition {
      transition:
        0s width ease-in-out,
        0s padding-left ease-in-out,
        0s padding-right ease-in-out;
    }

    .scrollbar-wrapper {
      overflow-x: hidden !important;
    }

    .el-scrollbar__bar.is-vertical {
      right: 0px;
    }

    .el-scrollbar {
      height: 100%;
    }

    &.has-logo {
      .el-scrollbar {
        height: calc(100% - 50px);
      }
    }

    .is-horizontal {
      display: none;
    }

    a {
      display: inline-block;
      width: 100%;
      overflow: hidden;
    }

    .svg-icon {
      margin-right: 10px !important;
    }

    .el-menu {
      border: none;
      height: 100%;
      width: 100% !important;
    }

    .el-menu-item,
    .menu-title {
      overflow: hidden !important;
      text-overflow: ellipsis !important;
      white-space: nowrap !important;
      height: 44px !important;
      line-height: 44px !important;
      font-weight: 600 !important;
    }

    .el-menu-item .el-menu-tooltip__trigger {
      display: inline-block !important;
    }

    .sub-menu-title-noDropdown,
    .el-sub-menu__title {
      &:hover {
        background-color: rgba(0, 0, 0, 0.06);
      }
    }

    & .theme-dark .is-active > .el-sub-menu__title {
      color: vars.$base-menu-color-active !important;
    }

    & .nest-menu .el-sub-menu > .el-sub-menu__title,
    & .el-sub-menu .el-menu-item {
      min-width: vars.$base-sidebar-width !important;

      &:hover {
        background-color: rgba(0, 0, 0, 0.06);
      }
    }

    & .theme-dark .nest-menu .el-sub-menu > .el-sub-menu__title,
    & .theme-dark .el-sub-menu .el-menu-item {
      background-color: vars.$base-sub-menu-background;

      &:hover {
        background-color: vars.$base-sub-menu-hover !important;
      }
    }

    &.theme-dark {
      box-shadow: 2px 0 8px rgba(0, 0, 0, 0.4);
      border-right: none;

      .el-menu-item.is-active {
        position: relative;

        &::before {
          content: '';
          position: absolute;
          inset: 0;
          background-color: var(--current-color-dark-bg, rgba(64, 158, 255, 0.2));
          pointer-events: none;
          z-index: 1;
          border-right: 3px solid var(--current-color, #409eff);
        }
      }

      .el-sub-menu.is-active > .el-sub-menu__title {
        color: var(--current-color, #409eff) !important;
      }

      .el-menu-item:not(.is-active),
      .submenu-title-noDropdown,
      .el-sub-menu__title {
        position: relative;

        &::before {
          content: '';
          position: absolute;
          inset: 0;
          background-color: transparent;
          pointer-events: none;
          z-index: 1;
          transition: background-color 0.2s;
        }

        &:hover::before {
          background-color: var(--current-color-dark-bg, rgba(64, 158, 255, 0.2));
        }
      }
    }

    &.theme-light {
      border-right: 1px solid #e8eaf0;
      box-shadow: none;

      .el-menu-item,
      .el-sub-menu__title {
        color: rgba(0, 0, 0, 0.65);
      }

      .el-menu-item.is-active {
        color: var(--current-color, #409eff) !important;
        position: relative;

        &::before {
          content: '';
          position: absolute;
          inset: 0;
          background-color: var(--current-color-light, #ecf5ff);
          pointer-events: none;
          z-index: 1;
          border-right: 3px solid var(--current-color, #409eff);
        }
      }

      .el-sub-menu.is-active > .el-sub-menu__title {
        color: var(--current-color, #409eff) !important;
      }

      .el-menu-item:not(.is-active):hover,
      .submenu-title-noDropdown:hover,
      .el-sub-menu__title:hover {
        background-color: #f5f7fa;
        color: rgba(0, 0, 0, 0.85) !important;
      }

      .nest-menu .el-sub-menu > .el-sub-menu__title,
      .el-sub-menu .el-menu-item {
        background-color: #fafafa;

        &:hover {
          background-color: #f0f5ff;
        }
      }
    }
  }

  .hideSidebar {
    .sidebar-container {
      width: 54px !important;
    }

    .main-container {
      margin-left: 54px;
    }

    .sub-menu-title-noDropdown {
      padding: 0 !important;
      position: relative;

      .el-tooltip {
        padding: 0 !important;

        .svg-icon {
          margin-left: 20px;
        }
      }
    }

    .el-sub-menu {
      overflow: hidden;

      & > .el-sub-menu__title {
        padding: 0 !important;

        .svg-icon {
          margin-left: 20px;
        }
      }
    }

    .el-menu--collapse {
      .el-sub-menu {
        & > .el-sub-menu__title {
          & > span {
            height: 0;
            width: 0;
            overflow: hidden;
            visibility: hidden;
            display: inline-block;
          }
          & > i {
            height: 0;
            width: 0;
            overflow: hidden;
            visibility: hidden;
            display: inline-block;
          }
        }
      }
    }
  }

  .el-menu--collapse .el-menu .el-sub-menu {
    min-width: vars.$base-sidebar-width !important;
  }

  .mobile {
    .main-container {
      margin-left: 0px;
    }

    .sidebar-container {
      transition: transform 0.28s;
      width: vars.$base-sidebar-width !important;
    }

    &.hideSidebar {
      .sidebar-container {
        pointer-events: none;
        transition-duration: 0.3s;
        transform: translate3d(-(vars.$base-sidebar-width), 0, 0);
      }
    }
  }

  .withoutAnimation {
    .main-container,
    .sidebar-container {
      transition: none;
    }
  }
}

.el-menu--vertical {
  & > .el-menu {
    .svg-icon {
      margin-right: 16px;
    }
  }

  .nest-menu .el-sub-menu > .el-sub-menu__title,
  .el-menu-item {
    &:hover {
      background-color: rgba(0, 0, 0, 0.06) !important;
    }
  }

  > .el-menu--popup {
    max-height: 100vh;
    overflow-y: auto;

    &::-webkit-scrollbar-track-piece {
      background: #d3dce6;
    }

    &::-webkit-scrollbar {
      width: 6px;
    }

    &::-webkit-scrollbar-thumb {
      background: #99a9bf;
      border-radius: 20px;
    }
  }
}
</style>

// xxl-boot-ui-react/src/layout/index.tsx
/**
 * Layout：布局主框架
 * 功能：整体页面骨架，组合侧边栏/顶部导航/标签页/主内容区/设置面板，
 *        处理桌面端与移动端布局切换、侧边栏收展联动、主题变量注入
 */
import { useEffect, useRef, useState } from 'react'
import Navbar from './components/Navbar'
import TagsView from './components/TagsView'
import Settings, { type SettingsHandle } from './components/Settings'
import Sidebar from './components/Sidebar'
import AppMain from './components/AppMain'
import { useAppStore, useSettingsStore } from '@/stores'
import './layout.scss'

// 移动端断点（参考 Bootstrap 响应式设计）
const WIDTH = 992

/**
 * 布局主框架
 */
export default function Layout() {
  const settingsStore = useSettingsStore()
  const appStore = useAppStore()
  const theme = settingsStore.theme
  const sidebar = appStore.sidebar
  const device = appStore.device
  const needTagsView = settingsStore.tagsView
  const fixedHeader = settingsStore.fixedHeader

  // 设置面板 ref
  const settingRef = useRef<SettingsHandle>(null)

  /*
   * 布局 CSS 类名组合：侧栏收展状态 + 设备类型
   */
  const classObj = {
    hideSidebar: !sidebar.opened,
    openSidebar: sidebar.opened,
    withoutAnimation: sidebar.withoutAnimation,
    mobile: device === 'mobile'
  }

  /*
   * 窗口响应式：宽度 < 992 切换 mobile，无动画收起侧栏
   */
  useEffect(() => {
    const handleResize = (isFirst = false) => {
      const width = document.body.clientWidth
      if (isFirst) {
        if (width - 1 < WIDTH) {
          appStore.toggleDevice('mobile')
          appStore.closeSideBar({ withoutAnimation: true })
        }
        return
      }
      // 使用 ResizeObserver 或跨断点切换判断
    }
    handleResize(true)

    let previousWidth = document.body.clientWidth
    const observer = new ResizeObserver(() => {
      const newWidth = document.body.clientWidth
      if (newWidth - 1 < WIDTH && previousWidth >= WIDTH) {
        // 桌面 → 移动
        appStore.toggleDevice('mobile')
        appStore.closeSideBar({ withoutAnimation: true })
      } else if (newWidth - 1 >= WIDTH && previousWidth < WIDTH) {
        // 移动 → 桌面
        appStore.toggleDevice('desktop')
        appStore.openSideBar({ withoutAnimation: true })
      }
      previousWidth = newWidth
    })
    observer.observe(document.body)
    return () => {
      observer.disconnect()
    }
     
  }, [])

  /*
   * 设备切换：切换到 mobile 时收起侧栏
   */
  useEffect(() => {
    if (appStore.device === 'mobile' && sidebar.opened) {
      appStore.closeSideBar({ withoutAnimation: false })
    }
     
  }, [appStore.device])

  /*
   * 移动端遮罩点击 -> 关闭侧栏
   */
  const handleClickOutside = () => {
    appStore.closeSideBar({ withoutAnimation: false })
  }

  /*
   * 打开布局设置面板
   */
  const setLayout = () => {
    settingRef.current?.openSetting()
  }

  return (
    <div className={`app-wrapper ${classObj.hideSidebar ? 'hideSidebar' : ''} ${classObj.openSidebar ? 'openSidebar' : ''} ${classObj.withoutAnimation ? 'withoutAnimation' : ''} ${classObj.mobile ? 'mobile' : ''}`}
      style={{
        '--current-color': theme,
        '--current-color-light': theme + '1a',
        '--current-color-dark-bg': theme + '33'
      } as React.CSSProperties}
    >
      {/* 移动端遮罩：侧栏展开时显示，点击关闭侧栏 */}
      {device === 'mobile' && sidebar.opened && <div className="drawer-bg" onClick={handleClickOutside} />}

      {/* 侧边栏（左侧） */}
      {!sidebar.hide && (
        <div className="sidebar-container">
          <Sidebar />
        </div>
      )}

      {/* 主内容区（中间） */}
      <div className={`main-container ${needTagsView ? 'hasTagsView' : ''} ${sidebar.hide ? 'sidebarHide' : ''}`}>
        {/* 固定头部（含导航栏和标签页） */}
        <div className={fixedHeader ? 'fixed-header' : ''}>
          <Navbar onSetLayout={setLayout} />
          {needTagsView && <TagsView />}
        </div>

        {/* 路由页面出口 */}
        <AppMain />

        {/* 布局设置面板 */}
        <Settings ref={settingRef} />
      </div>
    </div>
  )
}
