// xxl-boot-backup/ui/src/layout/index.vue
<!--
  名称：Layout 主框架布局组件（src/layout/index.vue）
  功能项摘要：
    1. 统一后台整体骨架（侧边栏 / 顶部导航 / 标签页 / 主内容 / 设置面板）。
    2. 处理桌面端与移动端的布局切换与侧边栏收展联动。
    3. 按主题与布局状态输出动态样式类与 CSS 变量。
-->
<template>
  <!-- 布局骨架：根容器汇总布局状态类与主题变量，作为页面主承载区。 -->
  <div :class="classObj" class="app-wrapper" :style="{ '--current-color': theme, '--current-color-light': theme + '1a', '--current-color-dark-bg': theme + '33' }">
    <!-- 实现细节：移动端侧栏展开时显示遮罩，点击遮罩触发侧栏关闭。 -->
    <div v-if="device === 'mobile' && sidebar.opened" class="drawer-bg" @click="handleClickOutside"/>
    <!-- 实现细节：侧边栏按 hide 状态按需渲染，避免无效节点。 -->
    <sidebar v-if="!sidebar.hide" class="sidebar-container" />
    <!-- 主内容区：根据标签页和侧栏隐藏状态切换容器样式。 -->
    <div :class="{ hasTagsView: needTagsView, sidebarHide: sidebar.hide }" class="main-container">
      <!-- 实现细节：头部固定样式由 fixedHeader 控制。 -->
      <div :class="{ 'fixed-header': fixedHeader }">
        <!-- 实现细节：导航栏通过 setLayout 事件打开设置面板。 -->
        <navbar @setLayout="setLayout" />
        <!-- 实现细节：标签页按配置开关显示。 -->
        <tags-view v-if="needTagsView" />
      </div>
      <!-- 实现细节：路由页面主体出口。 -->
      <app-main />
      <!-- 实现细节：设置面板通过 ref 暴露打开方法。 -->
      <settings ref="settingRef" />
    </div>
  </div>
</template>

<script setup>
import { useWindowSize } from '@vueuse/core'
import Sidebar from './components/Sidebar/index.vue'
import { AppMain, Navbar, Settings, TagsView } from './components'
import useAppStore from '@/store/modules/app'
import useSettingsStore from '@/store/modules/settings'

const settingsStore = useSettingsStore()
const theme = computed(() => settingsStore.theme)
const sidebar = computed(() => useAppStore().sidebar)
const device = computed(() => useAppStore().device)
const needTagsView = computed(() => settingsStore.tagsView)
const fixedHeader = computed(() => settingsStore.fixedHeader)

// 布局状态映射：将 store 状态映射为容器 class，统一驱动页面样式。
const classObj = computed(() => ({
  hideSidebar: !sidebar.value.opened,
  openSidebar: sidebar.value.opened,
  withoutAnimation: sidebar.value.withoutAnimation,
  mobile: device.value === 'mobile'
}))

const { width, height } = useWindowSize()
const WIDTH = 992 // refer to Bootstrap's responsive design

// 设备切换处理：切换到 mobile 时，若侧栏已展开则主动收起，避免遮挡内容。
watch(() => device.value, () => {
  if (device.value === 'mobile' && sidebar.value.opened) {
    useAppStore().closeSideBar({ withoutAnimation: false })
  }
})

// 窗口响应式处理：根据宽度阈值切换设备类型，并同步侧栏状态。
watchEffect(() => {
  if (width.value - 1 < WIDTH) {
    // 实现细节：移动端采用无动画收起，减少窗口缩放时的抖动。
    useAppStore().toggleDevice('mobile')
    useAppStore().closeSideBar({ withoutAnimation: true })
  } else {
    useAppStore().toggleDevice('desktop')
  }
})

function handleClickOutside() {
  // 交互细节：遮罩点击只执行侧栏关闭，不影响其他布局状态。
  useAppStore().closeSideBar({ withoutAnimation: false })
}

const settingRef = ref(null)
// 设置面板入口：响应导航栏事件，通过组件实例方法打开设置抽屉。
function setLayout() {
  settingRef.value.openSetting()
}
</script>

<style lang="scss" scoped>
@use "@/assets/styles/variables.module.scss" as vars;

.app-wrapper {
  &:after {
    content: "";
    display: table;
    clear: both;
  }
  position: relative;
  height: 100%;
  width: 100%;

  &.mobile.openSidebar {
    position: fixed;
    top: 0;
  }
}

.main-container:has(.fixed-header) {
  height: 100vh;
  overflow: hidden;
}

.drawer-bg {
  background: #000;
  opacity: 0.3;
  width: 100%;
  top: 0;
  height: 100%;
  position: absolute;
  z-index: 999;
}

.fixed-header {
  position: fixed;
  top: 0;
  right: 0;
  z-index: 9;
  width: calc(100% - #{vars.$base-sidebar-width});
  transition: width 0.28s;
}

.hideSidebar .fixed-header {
  width: calc(100% - 54px);
}

.sidebarHide .fixed-header {
  width: 100%;
}

.mobile .fixed-header {
  width: 100%;
}
</style>

// xxl-boot-ui-react/src/layout/index.tsx
/**
 * Layout：布局主框架
 * 功能：整体页面骨架，组合侧边栏/顶部导航/标签页/主内容区/设置面板，
 *        处理桌面端与移动端布局切换、侧边栏收展联动、主题变量注入
 */
import { useEffect, useRef, useState } from 'react'
import Navbar from './components/Navbar'
import TagsView from './components/TagsView'
import Settings, { type SettingsHandle } from './components/Settings'
import Sidebar from './components/Sidebar'
import AppMain from './components/AppMain'
import { useAppStore, useSettingsStore } from '@/stores'
import './layout.scss'

// 移动端断点（参考 Bootstrap 响应式设计）
const WIDTH = 992

/**
 * 布局主框架
 */
export default function Layout() {
  const settingsStore = useSettingsStore()
  const appStore = useAppStore()
  const theme = settingsStore.theme
  const sidebar = appStore.sidebar
  const device = appStore.device
  const needTagsView = settingsStore.tagsView
  const fixedHeader = settingsStore.fixedHeader

  // 设置面板 ref
  const settingRef = useRef<SettingsHandle>(null)

  /*
   * 布局 CSS 类名组合：侧栏收展状态 + 设备类型
   */
  const classObj = {
    hideSidebar: !sidebar.opened,
    openSidebar: sidebar.opened,
    withoutAnimation: sidebar.withoutAnimation,
    mobile: device === 'mobile'
  }

  /*
   * 窗口响应式：宽度 < 992 切换 mobile，无动画收起侧栏
   */
  useEffect(() => {
    const handleResize = (isFirst = false) => {
      const width = document.body.clientWidth
      if (isFirst) {
        if (width - 1 < WIDTH) {
          appStore.toggleDevice('mobile')
          appStore.closeSideBar({ withoutAnimation: true })
        }
        return
      }
      // 使用 ResizeObserver 或跨断点切换判断
    }
    handleResize(true)

    let previousWidth = document.body.clientWidth
    const observer = new ResizeObserver(() => {
      const newWidth = document.body.clientWidth
      if (newWidth - 1 < WIDTH && previousWidth >= WIDTH) {
        // 桌面 → 移动
        appStore.toggleDevice('mobile')
        appStore.closeSideBar({ withoutAnimation: true })
      } else if (newWidth - 1 >= WIDTH && previousWidth < WIDTH) {
        // 移动 → 桌面
        appStore.toggleDevice('desktop')
        appStore.openSideBar({ withoutAnimation: true })
      }
      previousWidth = newWidth
    })
    observer.observe(document.body)
    return () => {
      observer.disconnect()
    }
     
  }, [])

  /*
   * 设备切换：切换到 mobile 时收起侧栏
   */
  useEffect(() => {
    if (appStore.device === 'mobile' && sidebar.opened) {
      appStore.closeSideBar({ withoutAnimation: false })
    }
     
  }, [appStore.device])

  /*
   * 移动端遮罩点击 -> 关闭侧栏
   */
  const handleClickOutside = () => {
    appStore.closeSideBar({ withoutAnimation: false })
  }

  /*
   * 打开布局设置面板
   */
  const setLayout = () => {
    settingRef.current?.openSetting()
  }

  return (
    <div className={`app-wrapper ${classObj.hideSidebar ? 'hideSidebar' : ''} ${classObj.openSidebar ? 'openSidebar' : ''} ${classObj.withoutAnimation ? 'withoutAnimation' : ''} ${classObj.mobile ? 'mobile' : ''}`}
      style={{
        '--current-color': theme,
        '--current-color-light': theme + '1a',
        '--current-color-dark-bg': theme + '33'
      } as React.CSSProperties}
    >
      {/* 移动端遮罩：侧栏展开时显示，点击关闭侧栏 */}
      {device === 'mobile' && sidebar.opened && <div className="drawer-bg" onClick={handleClickOutside} />}

      {/* 侧边栏（左侧） */}
      {!sidebar.hide && (
        <div className="sidebar-container">
          <Sidebar />
        </div>
      )}

      {/* 主内容区（中间） */}
      <div className={`main-container ${needTagsView ? 'hasTagsView' : ''} ${sidebar.hide ? 'sidebarHide' : ''}`}>
        {/* 固定头部（含导航栏和标签页） */}
        <div className={fixedHeader ? 'fixed-header' : ''}>
          <Navbar onSetLayout={setLayout} />
          {needTagsView && <TagsView />}
        </div>

        {/* 路由页面出口 */}
        <AppMain />

        {/* 布局设置面板 */}
        <Settings ref={settingRef} />
      </div>
    </div>
  )
}
